### ISSUE TITLE
Improved IE11 Support - Distributing a pre-processed IE11-compatible stylesheet?

### ISSUE THREAD

**Issue by mturley** [patternfly/patternfly#1547]
I noticed some discussion on the ManageIQ UI gitter channel about the IE11 support solution detailed on the wiki here: https://github.com/patternfly/patternfly-next/wiki/IE11-Support

@himdel and @skateman had some concerns they wanted to share, so I'm opening this issue as a place to have that discussion. I think the main ask is to have IE11 compatible styles provided as part of the patternfly build, so consumers don't have to rely on a custom script to modify the CSS.

@seanforyou23 FYI. I'm not clear on all the moving pieces here.

**Comment by skateman** [comment]
We have people who run our stuff on IE11 due to the fact that they aren't allowed to use any other browser in their environment. This whole self-built thing sounds like a hack and I am afraid it might end up as an "unsupported practice" that we cannot really use safely. I would definitely use it for my hobby project, but not for something bigger, which is actually the case right now.

Even if you provide us the ready-to-use CSS, it might be not enough ... actually I don't mind doing it on our side. The thing I would rather see is some kind of guarantee that it will support the same stuff as the original version. What do you think about adding some kind of regression testing to your CI pipeline? Something that compares screenshots of the pages with IE11 compatible CSS with the original CSS running on Edge.

Also, we would like to see some kind of PoC of this IE11 support...

**Comment by mcoker** [comment]
We've dropped support for IE11 and the IE11 CSS we used to provide.
