### ISSUE TITLE
Explore alternative to the Modal Header Truncating

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1825]
issue #1819 explores how titles overflow, it appears as though the modal is the one component with a title that truncates when it overflows (no more than 1 line).

We should keep our components consistent, and explore whether it is necessary for the title to truncate, ideally the heading text would wrap to the next line.

It seems like the reason for the truncation is that if the modal has a really long title, and the viewport height is short, the body text isn't seen, so by keeping the title to one line, it prioritizes the body content. I think we should revisit this concept, and also maybe revisit the modal body scrolling since I don't think the scrollbar is visible on mobile without knowing that the body has overflown its container. Could all content in the modal scroll?

What do you think about that @mcarrano ?

<img width="557" alt="Screen Shot 2019-05-15 at 4 28 40 PM" src="https://user-images.githubusercontent.com/20118816/57807535-584b2a00-772f-11e9-91f0-b68fe162327e.png">

**Comment by mcarrano** [comment]
@christiemolloy there was a discussion of this issue a while ago and we did not want to wrap the title for the reasons you pointed out. My feeling then and is now that titles should be concise and short. The body of the modal should contain any detailed information. Are you aware of any use cases where this is actually a problem? As for why we only set scrolling on the body content, the feeling was that is we did have a long dialog where the content overflows the max height, we did not want the buttons to scroll off the bottom of the page. You are right that this may not be obvious to mobile users, but again IMO it is good design practice to keep the modal message dialogs short and to the point.

**Comment by rachael-phillips** [comment]
Hi @christiemolloy any thoughts for @mcarrano here? I'm trying to determine next steps on this issue.

**Comment by mcarrano** [comment]
I do remember discussing this with @mcoker and @kybaker a few months back and arriving at the current design approach. There were problems with allowing the title to wrap as you point of @christiemolloy . From a design standpoint, I feel like modal titles should be short and the body should be used to convey more content. We don't scroll the entire modal as a way to always keep the action buttons visible. 

Unless the current approach causes a problem that I am not aware of, I'd vote to keep this implementation as is.

**Comment by christiemolloy** [comment]
Thanks for responding @mcarrano 
The arguments I can see for changing this component is:
- in our documentation we have a rule that when text truncates there needs to be a way to see the rest of the text that is truncated, currently we cant do that in that component. It also says that truncating words can cause awkward words by the way its truncated: https://www.patternfly.org/v4/design-guidelines/content/grammar-and-terminology 
- we should strive for consistency across components, and currently its odd that the modal is the only component with a header that truncates.
- could we instead make a suggestion in the documentation that the text in the header should be kept to one line where possible?

**Comment by mcarrano** [comment]
I guess we could just handle this by providing design guidance @christiemolloy . But before I say yes to this, @mcoker do you recall exactly why we did this? Was there a problem other than preventing messy run-on dialog titles?

**Comment by mcoker** [comment]
> could we instead make a suggestion in the documentation that the text in the header should be kept to one line where possible?

Agreed, I think we should be flexible and encourage users how to best use the component. Seems like a 2 line modal title is fair, especially as you size down or are on mobile.

> do you recall exactly why we did this? Was there a problem other than preventing messy run-on dialog titles?

I think that's basically it and what @christiemolloy illustrated. During testing, we try edge cases, and if you have a long title with a short viewport, this happens.

<img width="691" alt="Screen Shot 2019-06-20 at 12 47 51 PM" src="https://user-images.githubusercontent.com/35148959/59869838-e7181b80-9359-11e9-8b12-57210671e036.png">

And here's an example of what it might look like on mobile, too. This also shows how a 1-2 line modal title would become 2-4 lines on mobile, and it would be odd if that text truncated instead of just wrapping to the next line. 

<img width="355" alt="Screen Shot 2019-06-20 at 12 47 03 PM" src="https://user-images.githubusercontent.com/35148959/59869874-f8f9be80-9359-11e9-8672-cbe68c01506a.png">

And fwiw, mobile/landscape.

<img width="889" alt="Screen Shot 2019-06-20 at 12 52 40 PM" src="https://user-images.githubusercontent.com/35148959/59870051-51c95700-935a-11e9-9716-323d14749827.png">

**Comment by mcarrano** [comment]
OK. Then I'm good to accept this one @christiemolloy and @rachael-phillips . I don't think there is any design needed here. This can go direct to CSS.

**Comment by rachael-phillips** [comment]
@christiemolloy @mcoker what priority would you give this issue?

**Comment by mcoker** [comment]
AFAIK, no one has asked for it and it isn't breaking anything, so it isn't a P1. Though I'd love to see it in sooner rather than later, and I imagine it's a change users would like to see, too. Maybe a P2 or P3? That said, I wonder if this would be a breaking change since some modal headers may be truncating currently, and this would change the layout/height of their modals.

**Comment by rachael-phillips** [comment]
Thanks @mcoker @christiemolloy is there anyway to accomplish this without a breaking change?

**Comment by mcoker** [comment]
Just revisiting this. In a recent PR, we added support for truncation via css `line-clamp` which allows you to specify the number of lines shown before truncation happens (eg, truncate after 2 or 3 lines of text). Maybe we could support that feature on the modal title, too? And potentially an opt-in for setting no truncation?
