### ISSUE TITLE
Accordion: Focus border renders outside of accordion item

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly#1850]
![image](https://user-images.githubusercontent.com/11633780/58123787-a8683780-7bda-11e9-8f61-cf0958b97ccf.png)

related: https://github.com/patternfly/patternfly-react/issues/2053

**Comment by michpetrov** [comment]
@jeff-phillips-18 Can you clarify what's the expected look?

**Comment by jeff-phillips-18** [comment]
I wouldn't expect the focus border to draw to the left of the selection indicator (blue vertical line).

**Comment by michpetrov** [comment]
I see, browsers draw the outline outside the borders of the element.
It can be changed but it would require shuffling the CSS classes around.
![Screenshot from 2019-06-21 13-56-00](https://user-images.githubusercontent.com/1999074/59921200-4bf07600-942d-11e9-8ca6-dd0140248246.png)
However this would also make it so that the outline on the collapsed toggles would not extend all the way to the left.
![Screenshot from 2019-06-21 13-56-04](https://user-images.githubusercontent.com/1999074/59921209-4f83fd00-942d-11e9-9283-488d7cbd915e.png)

**Comment by mcoker** [comment]
@jeff-phillips-18 like @michpetrov mentioned, the focus indicator is on the clickable element (`<button>`), and the button has a left border to indicate that it's expanded, which is why the focus ring goes around the blue line.

I suppose we could create the expanded indicator differently by removing the border and creating the expanded indicator using a pseudo element instead, then apply a `margin-left` to the `<button>` that matches the width of the border. But the way it behaves now seems fine to me, and using the technique I mentioned would add code and technically reduce the clickable area, so I'm OK leaving it as it is.

@mcarrano @jgiardino curious what you think?

**Comment by mcarrano** [comment]
I'm not bothered by it. @mceledonia do you have any concerns?

**Comment by serenamarie125** [comment]
IMO the other examples don't seem to be outside the boundary of the element

This is a zoomed in piece of @jeff-phillips-18's image.  It feels odd to me, since the vertical line "feels" like it's left boundary, and the focus is outside the boundary:
<img width="182" alt="Screen Shot 2019-07-23 at 4 39 21 PM" src="https://user-images.githubusercontent.com/12504403/61745901-828d1980-ad68-11e9-8f56-5b9033834c4d.png">

**Comment by jgiardino** [comment]
I don't have a super strong opinion on this yet—these are just some initial thoughts. Ultimately I trust the opinion of the visual designers on this.

I pasted below @michpetrov's second example from his [comment](https://github.com/patternfly/patternfly-next/issues/1850#issuecomment-504403418) above:

![Screenshot from 2019-06-21 13-56-04](https://user-images.githubusercontent.com/1999074/59921209-4f83fd00-942d-11e9-9283-488d7cbd915e.png)

As for the visual presentation and experience of this, I might have a stronger opinion one way or another if I could actually see and interact with the proposed solution, but it does seem odd that there would essentially be a white border to the left of the toggle when not expanded (i.e. the hover area and focus area would be identical, so on hover, the gray would not extend to the edge).

Also without seeing the implementation for this, I'm always hesitant to add more complexity to how things are built to accommodate minor visual refinements like this (i.e. makes things less maintainable, easier to break, more fragile, etc...). Not saying that this fix would add complexity, but just wanted to mention that would be a red flag in my opinion.

All that said, I do see @serenamarie125's point about other cases where the blue border is not part of the toggle. I'm also hesitant to say we should strive for consistency on that given the points above, and would suggest instead that we are mindful of two distinct patterns for the expand/collapse patterns: 
1. This pattern show a toggle that expands the full width of the component (and therefore the hover and focus states also expand the full width). 
2. Other patterns we have include other things besides the toggle in the collapsed state, so the focus and hover states are only on the toggle, and the expand border is on the parent container that includes the toggle. 

I think these two patterns are fine because they seem distinct enough, but we should make sure we don't start to do a weird blending of the two patterns where it starts to seem inconsistent.

**Comment by tqle** [comment]
Hi. 
Question on Patternfly focus guidelines. 

The issue you are seeing is the default focus ring  outline from Safari and Chrome which is offset by 5px.  
Are you allowed to re-adjust this per component or are you defaulting to the browser's focus offset?  
This is causing your issue and other focus ring issues. 
You can adjust the outline offset per item you want to target with css. Outline outset does not add anything to the element border or width. It actually grows with the size of your element.

Also, how are you handling focus for Firefox and IE? Both do not have the focus ring.  
I've worked on UI frameworks with issues with focus and focus fallbacks. For focus fallbacks we use the outline styling.  However, we had an extra level of specificity to know what browser the user is using a data attribute. 
Ex:

Suggested Fix for Mac Safari/Chrome:
// Fix accordion focus by changing offset to either -3px or up to -5px. Depending on how you want the offset to match on top of the accordion.
.pf-c-accordion .pf-c-accordion__toggle.pf-m-focus, 
.pf-c-accordion .pf-c-accordion__toggle:focus {
    background-color: var(--pf-c-accordion__toggle--focus--BackgroundColor);
    outline-offset: -3px; //<-- add this or some var with this value. -3px or -4px will work.
}
If you want to target what is selected or not selected, you can add more specificity and change the outline offset as needed.

**Comment by mceledonia** [comment]
@tqle Thanks for the information, that's very helpful. I would be ok with adjusting per-component as it seems like a one-time adjustment, though I would want to double back to Jenn to make sure there are no concerns with this for accessibility. Tien's suggested values look good to me! Any concerns with that approach @jgiardino @jeff-phillips-18 ?

**Comment by mcoker** [comment]
ping @jgiardino @jeff-phillips-18 @jessiehuff what do you think about the feedback ^? Or have a recommended way to proceed?

**Comment by jgiardino** [comment]
@tqle Thanks for making the suggestion! This could be a decent work-around to the issue described. I'm not aware if we have anyway of detecting the user's browser currently, so the final solution might be affected by that. 

Currently, the default browser styles for focus are used for html elements. For example, this is firefox:

![image](https://user-images.githubusercontent.com/21063328/64553456-6426b180-d307-11e9-8238-91bf953837da.png)

And this is how the `outline-offset: -3px` that you mentioned above would display in Firefox (if we did not target this style for only Chrome and Safari, as you also suggested 😉):

![image](https://user-images.githubusercontent.com/21063328/64553569-9cc68b00-d307-11e9-9ca0-65601768ab2f.png)


Ultimately, my question would go back to @mcoker or anyone on the team who might know if we are able to target specific browsers with specific styles. If so, can we use that approach here? If not, is it worth looking into that approach (and are there any risks or downside to using this approach)? Also are there other approaches we could consider that might be more minimal? And then once we know what our options are, I would want feedback from @mceledonia and other visual designers on what approach they would recommend.

Also, I haven't done much testing with `:focus-visible` which might be a valid solution (if it were better supported) assuming that this is primarily an issue from the perspective of mouse-only users (i.e. maybe the keyboard-only users who rely on this indication are more forgiving over how the focus indication is drawn 🤷‍♀).
