### ISSUE TITLE
Update to Tabs

### ISSUE THREAD

**Issue by rachael-phillips** [patternfly/patternfly#1855]
Changes made to both primary and secondary tabs. @kybaker do you mind adding the mockups and other details? Thanks!

**Comment by mceledonia** [comment]
The digital design team has a nice concept for primary/secondary tabs. There may be situations where we need a "condensed" version of these with tighter spacing, for situations limited in width such as side panels. Overall though these are a nice improvement over our previous design, I will attach a screenshot preview below.

![image](https://user-images.githubusercontent.com/30935938/58653333-78f4b180-82e3-11e9-860c-9c74ab82a8ce.png)
![image](https://user-images.githubusercontent.com/30935938/58653346-7eea9280-82e3-11e9-97b8-0df85341e28d.png)

We need to make some small updates when adding this to the library for example switching the active tab color to our primary blue rather than the red.

**Comment by kybaker** [comment]
@mcarrano @mceledonia I made an update to the tabs. This includes changing the primary style to use the underline instead of the boxed traditional shape. This design fits much better in the header area where it most commonly appears. I also adjusted spacing to fit within our containers.

https://marvelapp.com/416e0jh

**Comment by mcarrano** [comment]
New tab styling looks great @kybaker .  Based on discussion today with @kybaker and @mcoker there are a few considerations we should keep in mind:

* Intent is to replace current tab styling with these new variations. Further investigation is needed to determine whether this will be a breaking change. In any case, it will be a visual change that should be vetted with stakeholders so they are not surprised when new primary tab style is introduced.

* Current examples use the terms "Primary" and "Secondary" to call out tab styles. This is misleading because the correct variant to use is more about context (i.e. placement on the page) and less about logical hierarchy. Should identify a better naming for these variations.

* We should create a Tabs demo that shows some examples of tabs usage and helps answer the question of what tabs style should I be using. I've created a new issue for that here: #2016 .

@rachael-phillips @LHinson FYI

**Comment by mcarrano** [comment]
Want to also consider request to include icons in tabs as a new variant. See https://github.com/patternfly/patternfly-react/issues/2536

**Comment by mcarrano** [comment]
Per discussion on Aug 4, shifting this to CSS backlog so details of tab layouts with and without icons can happen there.

**Comment by mcarrano** [comment]
Designs from @kybaker [https://app.zenhub.com/files/122507459/627d77bc-4dce-49f0-9792-5caac3fe5840/download](https://app.zenhub.com/files/122507459/627d77bc-4dce-49f0-9792-5caac3fe5840/download)

**Comment by mceledonia** [comment]
https://github.com/patternfly/patternfly-next/issues/2256

**Comment by mceledonia** [comment]
We should consider a compact modifier for tight spaces like cards and side panels.

**Comment by mcarrano** [comment]
Current tab designs

![Tabs Specs.png](https://images.zenhubusercontent.com/5ce816524e6c594dc1b0df4d/807b2e6a-439f-4cac-a96c-ae6ca3b45816)

**Comment by ajacobs21e** [comment]
Code question - is it possible to keep the tab width the same in the default and selected states? Normally the bold text would make the tab slightly wider in the selected state, resulting in a visible shift. We want to avoid that.

**Comment by mcoker** [comment]
@ajacobs21e generally speaking, if the width of a container is defined by the width of the text inside of it, if the text is made bold, the width of the container will grow in size.

There are some [hacky workarounds](https://codepen.io/mcoker/pen/LYVPmYR?editors=1100) to keep that from happening, but I'd like to avoid those if possible.

**Comment by ajacobs21e** [comment]
Thanks @mcoker 
If that's the case, @kybaker how do you feel about using the same font weight for both states?

@coreyvickery fyi

**Comment by kybaker** [comment]
@ajacobs21e Using the same weight is fine with me

**Comment by ajacobs21e** [comment]
Final design spec for tabs update: https://sketch.cloud/s/3WK1w/v/m12Y18/p/tabs/
@mcoker please let me know if there are any specs I missed.

@mcarrano should I add the specs for dark theme tabs here as well or would that be a separate story to create those? Needed for web use cases.

**Comment by mcarrano** [comment]
@ajacobs21e I'm not sure what we should do about dark-theme elements for now. We don't really have our dark theme story figured out for PF overall, so when new component get introduced, they are generally for light-theme, only. @mcoker @mceledonia @LHinson thoughts?

**Comment by mcoker** [comment]
@ajacobs21e @mcarrano this looks good, though on the overflow tabs we have this issue that came up around the UX of the scroll buttons in the nav disappearing (same principle applies to tabs) - https://github.com/patternfly/patternfly-next/issues/2435

The solution was to make the scroll buttons appear inline with the list instead of positioned over the first/last tabs, and they would always be visible as long as there is content in the list that overflows. And instead of disappearing, the buttons would appear as disabled. 

Should we update these designs to match? Also will we have overflow scroll buttons for the vertical tabs?

**Comment by ajacobs21e** [comment]
@mcoker thanks for sharing that other story. Makes sense to me in theory - is this roughly how it would work? My main question is about the truncation of tabs on the right side
![overflow arrows](https://user-images.githubusercontent.com/6415742/74681172-b5797d80-5190-11ea-88bb-6b3cfbc2f7de.png)

@coreyvickery is that ok with you?

I think you took out your question about vertical tabs and I don't expect those to have an overflow but rather the page would just get as long as it needs to. And ideally the designer doesn't create something with 30 vertical tabs!

**Comment by mcoker** [comment]
@ajacobs21e what about the shadow treatment we use on tertiary nav? https://www.patternfly.org/v4/documentation/core/components/nav/tertiary-overflow

We use a similar treatment on the horizontal nav (with a black shadow) https://www.patternfly.org/v4/documentation/core/components/nav#horizontal-overflow-in-masthead

> I think you took out your question about vertical tabs and I don't expect those to have an overflow but rather the page would just get as long as it needs to. And ideally the designer doesn't create something with 30 vertical tabs!

Yeah, I thought about it and I assume it would behave like vertical navigation and wizard and scroll normally.

**Comment by ajacobs21e** [comment]
@mcoker I assume when you're scrolled all the way to the left side and the arrow is disabled, there's no shadow? If so then yeah I think that pattern works

**Comment by ajacobs21e** [comment]
@mceledonia or @lboehling would the overflow arrows still have 4px of space on the left/right sides of the icon button [bottom example]? or be flush with the tab [top example]?
![Screen Shot 2020-02-18 at 1 38 45 PM](https://user-images.githubusercontent.com/6415742/74766985-030aee80-5254-11ea-887e-ea6c856dc52b.png)

**Comment by mcarrano** [comment]
Per this issue (https://github.com/patternfly/patternfly-next/issues/2435) the overflow design will be updated slightly to avoid overlap between the end tab and the scroll button. Revised visual approach is previewed here: https://patternfly-next-pr-2757.surge.sh/documentation/core/components/tabs

**Comment by coreyvickery** [comment]
@ajacobs21e So with Matt's edits, are we losing the white fade and just using a white box with a left or right gray border?

**Comment by coreyvickery** [comment]
@mcarrano: Noticed that you fixed the 1px of space between the tabs in your PR link. One last thing, the highlight/thick bar color appears to be incorrect on hover, it needs to be #b8bbbe instead of #d2d2d2, that is what Allie and I spec'd a week or so ago.

**Comment by mcarrano** [comment]
@coreyvickery Feel free to comment on the PR here: https://github.com/patternfly/patternfly-next/pull/2757 although I think @ajacobs21e already left this comment. I'm not actually the developer working on this, just the messenger :)

**Comment by mattnolting** [comment]
closed by #2757
