### ISSUE TITLE
Alert 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#19]
Update the alerts component and variations with patternfly.next styling.

**Comment by mcarrano** [comment]
@LHinson what is the intended scope of this issue? In PatternFly today we have Inline Notifications and Toast Notifications that are both forms of alerts. We should also consider terminology we want to use. Are alerts and notifications different names for the same thing? I think that most libraries use the term Alert over Notification so I'm Ok to change. But we should make sure there is consensus. Thoughts?

**Comment by kybaker** [comment]
@mcarrano @matthewcarleton I finished the first version of the alert. For consistency I kept the alert style the same for the inline and toast notifications which is much more modular than what we have now. I added a shadow to both to standout from the content and float over the content as a toast. This also uses the theme colors defined in an earlier story. You will notice I used a white background for the inline alert, the reason for this is to ensure there is enough contrast.

https://drive.google.com/open?id=1lk4frU4i1vqnRxblMmFPmZTmhnJ3GTrn

**Comment by mcarrano** [comment]
@kybaker I have a few comments/questions about the features included here:

* In the current PF designs, we do have inconsistencies in the way we represent actions between the inline notification and the toaster alert. If we are going to include the kabob option, then I think this should be available from both the inline and toast version of the alert. Any reason the kabob can't be included in the single line toast alert? What if I only have one action that can be performed? Could we offer an action link as an alternative to the kabob?

* The date should be optional and only makes sense (if needed at all) for the inline version of the alert.

* I think that the colored text is useful for the 2-line alert since it helps distinguish the header from the body of the alert. But for the single line, I wonder if we should just go with black text. I'm worried about readability, especially with the yellow warning and green success alert. 

Thoughts?

**Comment by kybaker** [comment]
@mcarrano:

- I think the best option for now is to remove the kebob when this goes to development so it more closely mirrors the current functionality. 
- We can keep the date as optional in the development phase.
- I think we need to use the colored text so it draws more attention especially when used on a white background (not yet shown). All of the colors pass accessibility requirements.

**Comment by mcarrano** [comment]
Agree with removing the kebab. Doesn't seem like good practice to expose lots of actions in alerts. But we may have cases where we would embed a link to take action or navigate within the body of a message. Can we modify the examples to show this and remove the kabob @kybaker ? Otherwise I fear it will just continue to raise questions.

**Comment by kybaker** [comment]
[Updated PDF](https://drive.google.com/open?id=1bW6bdat30nfKKv_1NinFOc5F3CXY4YYx)

**Comment by LHinson** [comment]
Assigning myself as well to start looking into contributing design docs

**Comment by mcarrano** [comment]
@LHinson on the subject of design docs, this is the template @stacymcauliffe and I had worked out for design documentation (usage guidelines) for components (and patterns?). https://docs.google.com/document/d/1L0YnKwJimjpO81mwDpigkOq81qX97LikwlR9Edq1JN0/edit?usp=sharing

Please try to follow this as you draft documentation for alerts. Besides usage guidance, I think that providing some content guidelines (i.e. writing good alert messages) would be important.

**Comment by matthewcarleton** [comment]
@kybaker These are looking solid. I have a few thoughts:

@mceledonia is pulling these designs into the notification drawer. In our current alerts we have an inline link, do you see these changing? In the version Michael did it is separate from the text, which might be ok if we want a different style for the drawer.
There is no info alert here, are we keeping that?
I've also tested the different colours here and the icons don't have enough contrast to pass AA. Also the Success green text doesn't pass on the white background. 
In our current alerts we also have an option for a button, I am assuming that will just take the place of the "X" but should we consider that now?

**Comment by kybaker** [comment]
@matthewcarleton 
[Here are the latest updates - Invision link](https://redhat.invisionapp.com/share/U9JBCP3YWZ4)

[Editable File](https://drive.google.com/open?id=1Hmt3IFCktv2fHj2E3F28Xm8VTNv40oeK)
