### ISSUE TITLE
Can we remove the Icon Color Var

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#1903]
@gdoyle1 bought up to me that the only place we're using `--pf-global--icon--Color--dark` is in the login main footer links brand icons. can we just use the text color here: `pf-global--Color--100` like we do for other icons?

**Comment by mcoker** [comment]
They were added here - https://github.com/patternfly/patternfly-next/pull/1281

@matthewcarleton what do you think?

**Comment by matthewcarleton** [comment]
I think the main reason was to ensure there was consistency with icon colours and possibly to set it up for future icon colours.
I would suggest we use the variable rather than the text colour throughout. I talked to @mcoker about this and I think he's going to pull @mceledonia into the discussion as well :)

**Comment by mceledonia** [comment]
Yeah, it would be good to ensure icon colors are consistent rather than relying on people to remember which text color variable the icon should be... With that being said, is there a reason why we aren't using the icon color variable throughout the system? Ideally we should have our actionable icons a consistent style.

**Comment by mcoker** [comment]
> is there a reason why we aren't using the icon color variable throughout the system?

@mceledonia I don't think so. Probably just that we added the icon color vars fairly recently and only used them in new components, and didn't refactor any existing components to use them.

Currently `$pf-global--icon--Color--dark` is the same hex value as `$pf-global--Color--100` (text color 100) and `$pf-global--icon--Color--light` is the same hex as `$pf-global--Color--200` (text color 200). Assuming we want those to match, we can also assign `$pf-global--icon--Color--dark = $pf-global--Color--100` and  `$pf-global--icon--Color--light = $pf-global--Color--200` in the variable system, so that they always match. If we update the global text colors, the icon colors change automatically. We do something similar for link colors by defining `$pf-global--link--Color = $pf-global--primary-color--100` and `$pf-global--link--Color--hover = $pf-global--primary-color--200`, for example. What do you think about that?

**Comment by mceledonia** [comment]
That sounds good to me @mcoker, it will keep things cleaner down the line if we ever make adjustments to our text colors.

**Comment by mcoker** [comment]
I think we can revisit this with the dark theme global variable audit.
