### ISSUE TITLE
Investigate use of .pf-c-form__helper-text-icon in login component

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1959]
https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/components/Login/login.scss#L214-L217

`.pf-c-form__helper-text-icon` doesn't exist in the form component. Should we add it? Maybe update the class to be an element of the login component instead?

**Comment by mcoker** [comment]
@mcarrano we have this icon in the form helper text on the login example. This currently only works in the login component. Do you see any reason not to move support this icon and its vertical alignement/spacing into the form component, so that it can be used in the context of any form (not just on the login screen)?

**Comment by mcarrano** [comment]
Is this what you are referring to @mcoker ?

![Screen Shot 2020-04-06 at 9 44 03 AM](https://user-images.githubusercontent.com/6619860/78564973-36e1a980-77eb-11ea-96e7-50e883dceeab.png)

If so, I don't see any harm in that, although we don't have any specific pattern that requires it. I think this was unique to login because we did not want to use an inline alert to conserve space.

**Comment by mcoker** [comment]
@mcarrano that's it, and thanks!
