### ISSUE TITLE
Update <small> in data list example

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#1960]
The `<small>` in the data list example is 13.333px, and it should be 14px. We're relying on the browser's styles there.

Some options:

* Should we add `<small>` to the global reset styles?
* Maybe we can update the data list demo to use the `pf-c-content` version of the `<small>` element? 
  * Should the `<small>` be a lighter color by default, or should that be a variation?
* Should we add a component for `<small>` and potentially all of the elements we style in the content component like `blockquote`, `hr` (divider component, which we should add ), `dl` (will be in https://github.com/patternfly/patternfly-next/issues/1919)? We already have components for `ul`, `ol`, `.pf-c-title` for headings, `a` is styled in the global stylesheet...

**Comment by tqle** [comment]
1. If you are going to use <small> in other controls. I would reset or normalize it like you are in your global css.  Since you are setting the font size, normalizing all these fields is how most frameworks approach it. In frameworks I've worked on we just had all the font size variables defined and scaled. So if <small> is the same as an an <h6> both elements used the same variable.

2. Does the data list need to use the <small> ? as the data list label or value? Or do you allow for any html element like a <label>, a heading like <h5>, etc...  The color variation should be separate property or class you apply.  Unless there is a typography guideline you must follow.  Is there a special meaning if the font is small, does adding the lighter color add value to the user or usability. Those guidelines should be defined by your style guide or visual design.

From experience in other frameworks, most developers are not aware of <small> or use small. The just use some class to indicate the text has smaller size.  But in anywise, you should normalize it and reset the font if it ever appears or is being used.
