### ISSUE TITLE
Missing documentation for content wrapping in tables

### ISSUE THREAD

**Issue by ncameronbritt** [patternfly/patternfly#1994]
I would like to see documentation somewhere around how content is handled within cells in tables. Does long content wrap by default? Does the layout switch to the stacked? It's not clear what the ootb behavior is or what options are available.

The behavior is not consistent across the [data table demos](https://www.patternfly.org/v4/documentation/core/demos/datatable). For example the simple and sortable demos handle wrapping differently. Sortable wraps; simple doesn't.

**Comment by rachael-phillips** [comment]
Thanks for posting this @ncameronbritt! Making you aware @mcarrano @christiemolloy

**Comment by rachael-phillips** [comment]
@ncameronbritt do you have a timeline around when you will need this information by?

**Comment by mcarrano** [comment]
I'm not sure that I can explain the difference between the two examples. Perhaps @christiemolloy can shed some light on that?  But in answer to your question, @ncameronbritt , yes long content in a cell should wrap unless there is code added to do otherwise. Is that what you want to happen? The stacking has nothing to do with cell content but is rather based on crossing a breakpoint as you shrink the viewport.

@christiemolloy anything to add?

**Comment by christiemolloy** [comment]
@ncameronbritt  sorry for the late response.

The simple table changes display from table to grid at `pf-m-grid-lg` and the sortable table changes at `pf-m-grid-md`, this is because the sortable table has more columns, therefore it must wrap earlier so that it doesnt break. This documentation is at the very bottom of this link, but if you still don't think it clarifies it properly Id be happy to update it: https://pf4.patternfly.org/components/Table/examples/

And then all table-cell content is set to :  ` td { word-break: break-word; }` which means: To prevent overflow, word may be broken at arbitrary points.

**Comment by rachael-phillips** [comment]
@ncameronbritt do you have a timeline around when you will need this information by?

**Comment by ncameronbritt** [comment]
Thanks @christiemolloy 

So which should I be looking at? 
https://pf4.patternfly.org/components/Table/examples/
or
https://www.patternfly.org/v4/documentation/react/components/table/
or
https://www.patternfly.org/v4/documentation/core/components/table

On www.patternfly, Core has that documentation; React doesn't.

**Comment by mcoker** [comment]
Hey @ncameronbritt, just wanted to check back in about this. We've added some new table features, including documentation on wrapping/white space behavior. The core documentation tends to be more usage/design oriented, and the react documentation is more developer focused.

Here is the core documentation around ways to manipulate table text - https://www.patternfly.org/v4/documentation/core/components/table#controlling-text

The same example, with less documentation in the react docs - https://www.patternfly.org/v4/documentation/react/components/table#controlling-text

Do you think we still need to update the documentation?
