### ISSUE TITLE
Revisit form layout

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#2044]
Currently, spacing between the login form header and body is created by a hidden error message. I think we need to revisit this approach because it's pretty fragile and relies on developers to limit text, etc. Also, other forms are going to require several different validation messages and this isn't reusable/scalable.

**Comment by mcoker** [comment]
cc @matthewcarleton @mcarrano I believe this work was originally implemented in https://github.com/patternfly/patternfly-next/issues/1063

**Comment by matthewcarleton** [comment]
I agree with everything you are saying @mattnolting 
From what I recall this was a difficult decision and came with some issues. Happy to be part of the discussion to push this along.

**Comment by mcarrano** [comment]
I know that this is a very controversial topic and the current approach was arrived at following multiple design iterations. We were getting lots of push back from certain product teams that complained about the way the login form would accordion when errors were reported so this was a compromise. Unless we have specific product feedback that says this is a problem, I'd like to not revisit this. 

@LHinson FYI

**Comment by rhamilto** [comment]
@mcarrano, since you're looking for specific product feedback...

The assumption that every immediate child of `.pf-c-form` will be a `.pf-c-form__group` is very short sighted.  We have numerous forms in OpenShift where we need to insert nodes (e.g., a wrapping `div`) in to a form that are not simple form label/group combos (i.e., `.pf-c-form__group`s ).  The workaround we've identified is to insert a `<div class="pf-c-form">` around `.pf-c-form__group`s that are nested in the inserted nodes.  This is far from ideal because the new `<div class="pf-c-form">` should not be needed and is semantically poor (nested forms).  https://github.com/rhamilto/console/blob/3dad0870ceb6b882c79aa451367d19f056c4c02c/frontend/public/components/deploy-image.tsx#L330-L452 is an example of a form I started to migrate to PF4 when I identified this problem (note it did not merge as we identified it was going to be too much work to migrate all our forms prior to feature freeze and we did not want to ship two differently styled forms).  Further, spacing between form buttons is also dependent on `.pf-c-form`.  So in order to adopt PF4 buttons for use in our existing PF3 forms, we had to add `.pf-c-form` to `.pf-c-form-group` in order to get properly spaced buttons (e.g.,  https://github.com/sg00dwin/console/blob/a8dbd34060e5b4fac1d1d860281089f0020da7df/frontend/public/components/cluster-settings/basicauth-idp-form.tsx#L190).

cc: @spadgett, @alimobrem, @sg00dwin
