### ISSUE TITLE
select dropdown opens an empty div when no children are specified

### ISSUE THREAD

**Issue by jenny-s51** [patternfly/patternfly#2132]
When I set the select dropdown to have no children (delete the `options` object from `CheckboxSelectInput` in `Select.md`) and I try to expand, it expands to an empty div.
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/32821331/62562072-761bbd00-b84e-11e9-8e5b-d5b8db48b588.gif)

See below for link to the original comment and related react issue resolved by @boaz0. 
https://github.com/patternfly/patternfly-react/pull/2647#issuecomment-518769240

**Comment by SpyTec** [comment]
@mcoker @mcarrano - continuing here from https://github.com/patternfly/patternfly-react/pull/2647

> Can you give me an example use case of how/where this would show up?

Particularly if we load from an API we would not have any children until the data has been fetched. I don't think this would be an issue if it could be disabled or replaced with a skeleton-view of the component.

For the time being though most of the Select components in my application has empty children for a good 2-5 seconds before data is loaded

**Comment by mcarrano** [comment]
This issue was earlier raised here: https://github.com/patternfly/patternfly-next/issues/2007 I think that disabling the select list could be a quick fix, however we ultimately do want to establish a skeleton loading pattern for cases like this. Five seconds can be a long time without any feedback about what's happening.

What's your timeline for needing this @SpyTec ? @rachael-phillips @LHinson take note.

**Comment by SpyTec** [comment]
I would love to have some kind of feedback that it's disabled. Forgot to mention, sometimes we might not even get data populated in certain Select components, so they would remain having empty children despite the data being loaded.

For the timeline, the sooner the better. We will roll out our first PF4-based release sometime next week, and I don't think this change would make it before then; Having the feature ready for our next feature, 3-4 weeks from now, would be even better

**Comment by rachael-phillips** [comment]
Thanks for the info, @SpyTec . @mcarrano do we need skeleton loading to move forward with fixing this bug or do you think it would be a better option given the timeline to offer a quicker bug fix?

**Comment by mcarrano** [comment]
I guess that depends on what constitutes a quick fix @rachael-phillips .  The current behavior occurs since this was a case we did not originally design for. If we could do something like this that allowed you to set a loading state, would that address this @SpyTec ?

![Select-loading](https://user-images.githubusercontent.com/6619860/62715753-17ca1800-b9cf-11e9-80c8-2bee05ca3f2e.png)

**Comment by SpyTec** [comment]
That would definitely help the loading situation which is what I care most about.

Not so much if data returned is empty and no children are available, though that's minor

**Comment by mcoker** [comment]
@mcarrano should we investigate a loading state for the menu?

**Comment by mcarrano** [comment]
Yes. I think that would make sense as part of the menu work.

**Comment by mcoker** [comment]
@mcarrano do you mean that this would be a feature of the context menu component?

**Comment by mcarrano** [comment]
Yes, but does that make sense? Thought that's what you were asking.

**Comment by mcoker** [comment]
@mcarrano yep, that works for me! Wasn't sure if we wanted to add this to the existing select component or not. This issue is pretty old, so maybe we hold off on updating an existing component unless we get a specific request for it. Does this need to go to design, or is there a design to work from?

**Comment by mcarrano** [comment]
@doruskova Did any of your designs consider this case of what to show while the menu is loading? If not, maybe another thing to address or I can open a separate issue. Thanks.

**Comment by doruskova** [comment]
@mcarrano I didn't consider this situation, but it's definitely needed. Thank you! I'll add it to mocks and share it with you.

**Comment by doruskova** [comment]
@mcarrano I've added an empty state and loading state for the drill-down menu (also usable for tree view etc.) https://marvelapp.com/prototype/66b0059/screen/71918537

**Comment by mcarrano** [comment]
Thanks @doruskova Looks good. Can you specify whether there is specific spacing to be used?

**Comment by doruskova** [comment]
@mcarrano yeah, the spec with padding is here https://marvelapp.com/prototype/66b0059/screen/72079923
