### ISSUE TITLE
Modal body overflow 

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly#2194]
When using a dropdown in a modal there is an overflow issue b/c of the positioning of the dropdown menu. 
This is caused by 
``` 
overflow-x: hidden; 
overflow-y: auto;
```
on
`.pf-c-modal-box__body`
This is what you get when an expanded menu is seen in the modal. I believe this is still the case in React unless there is some magic determining height.
<img width="591" alt="Screen Shot 2019-08-26 at 6 23 07 PM" src="https://user-images.githubusercontent.com/287880/63724993-8d3b4280-c82f-11e9-9ba1-4e2030242930.png">
From what I recall this overflow was applied to avoid long scrolling viewports on smaller screens.

**Comment by matthewcarleton** [comment]
> @matthewcarleton is this blocking you? Also, do you have a release in mind that this would go in for?

sorry I missed this comment. This was not blocking yet b/c we don't have the modal in the console AFAIK. It came up as an issue with PF3 as well but was fixed in the console so I added this to hopefully fix it ahead of time :)

**Comment by mcoker** [comment]
@mcarrano because of the way the dropdown menu is presented when it's expanded (it displays on top of the content below it), it will not push around other content on the page when it is displayed. Therefore if the dropdown is at the bottom of the modal body, and the dropdown is expanded, the expanded menu doesn't push the bottom of the modal down to accommodate. Instead, the modal body displays a scrollbar to view the expanded dropdown menu. There is a demonstration of this issue in this comment https://github.com/patternfly/patternfly-react/issues/2790#issuecomment-531809448

There is potentially a react fix that is mentioned in https://github.com/patternfly/patternfly-react/issues/2790 would allow for a user to attach a dropdown component's expanded menu code to the body of the page (or a specified container), effectively moving it outside of the modal body in the code, but still presenting it visually directly underneath the dropdown toggle with no visual change compared to the current behavior. That would allow the expanded dropdown menu to appear properly in the modal (effectively on top of the modal instead of "inside" of it, requiring a scrollbar). That would be a react-only fix, though considering that the dropdown requires react to function properly, that seems like an acceptable approach.

Adding this enhancement to the react dropdown seems like a great idea for other cases when you want the expanded dropdown menu to appear on top of other content that may have a similar problem as the one described in this issue.

Another option could be to re-visit the modal body overflow behavior so that we don't limit the modal to the height of the viewport and cause the modal body content to overflow with a scrollbar. Since we've talked about issues with the current implementation in the past around how on short viewports, in a modal with a modal title and actions, this can create a very short modal body requiring scrolling within a short visible area, I thought I would mention that as well.

Do you think it's worth revisiting the modal body's overflow behavior, or do you think that is OK and we should explore the react fix mentioned above?

**Comment by mcarrano** [comment]
@mcoker If I understand this correctly, I think that the React solution is the best approach. So in that case, the dropdown panel will display over the top of the modal, is that correct? That's what I would expect. I don't think that changing the overflow behavior of the modal in general is the right approach. Do you agree?

**Comment by mcoker** [comment]
@mcarrano yep, if you’re ok with the overflow behavior as it is, I think the react enhancement is likely the best approach.

**Comment by mcoker** [comment]
We chatted about this at the F2F and agreed the modal body should support a variation that disables the modal body overflow scroll for cases like this, which would allow the dropdown menu to overflow outside of the body section and on top of the footer.

**Comment by christianvogt** [comment]
While a fix for the modal body can help this specific use case. We still need modal bodies to be scrollable and support drop downs at the same time.
Also, I would like to see the react dropdown support parenting the dropdown menu to the body so that it can be positioned by libraries like popper.js.
This would require the menu css to support rendering a dropdown menu externally to the dropdown button itself.

**Comment by dalaicam** [comment]
Hello,
Currently this situation is happening in some of the modals we are using.
Until this situation is fixed, is there a temporary workaround that could be used to minimize the impact of the use of select?

Thanks for the help

**Comment by rachael-phillips** [comment]
Hi @dalaicam we are looking into this from a design perspective, and therefore don't have a workaround at this time, but we will be back soon with an update. Thank you!

**Comment by LHinson** [comment]
related issues: 
- There is a design issue to address the modular dropdown related to this issue. See: https://github.com/patternfly/patternfly-design/issues/789
- The react follow up to this is here: https://github.com/patternfly/patternfly-react/issues/2790

**Comment by mcoker** [comment]
Closing per https://github.com/patternfly/patternfly-react/issues/2790 and https://github.com/patternfly/patternfly-react/pull/4348
