### ISSUE TITLE
Dark nav - inconsistent behavior/missing documentation

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly#2345]
In Red Hat Cloud Services, blue underline has several different ways of implementation and there is no documentation which one is correct. 

Here is no space under blue line. 
![Screen Shot 2019-10-08 at 09 27 02](https://user-images.githubusercontent.com/36040135/66375535-e90bf600-e9ad-11e9-934a-3dce821d494b.png)

Here is some space under blue line.
![Screen Shot 2019-10-08 at 09 27 24](https://user-images.githubusercontent.com/36040135/66375541-ec06e680-e9ad-11e9-95f2-90acc79ac9c3.png)

Which one should be used? Reading through the documentation, it is not clear either. Once its is with no margin and the second time with a margin. This is confusing and we are not being consistent. I recommend keeping the space under the blue line - everywhere. 
![Screen Shot 2019-10-08 at 09 36 08](https://user-images.githubusercontent.com/36040135/66376150-42285980-e9af-11e9-997a-e0c8ef615ea9.png)

**Comment by mcoker** [comment]
@kybaker @mceledonia

**Comment by mceledonia** [comment]
It looks like there is no space when subnav is expanded and space when it is just a parent item. 

I would be in favor of, instead of moving the blue line, moving the background highlight bottom edge up to meet the bottom of the blue line. Then leaving it how it is currently for expanded subnav. Here is a quick before/after mockup what do you think @kybaker?

![image](https://user-images.githubusercontent.com/30935938/66410651-78220980-e9c0-11e9-886e-5148634e3014.png)

**Comment by kybaker** [comment]
@mceledonia @mcoker We opted to have the two different displays for the expanded item background one taller one when open and a shorter one when closed. It is more like having a hover or an open state. The problem is we just need to document this in a way that is more understandable. @mcoker

**Comment by terezanovotna** [comment]
Can you share some visuals @kybaker to support what you mean?
