### ISSUE TITLE
Navigation - TertiaryList: Disappearing scroll button causes UX issue

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#2435]
Rapidly clicking the scroll button can result in the first or last tab being selected, which can be confusing (see below).  In my OpenShift console prototype, I accounted for this by not overlaying the scroll buttons on top of the tabs.

![rYKy0zMiSx](https://user-images.githubusercontent.com/895728/67515839-779a9b80-f66d-11e9-859f-a979f6d74ca9.gif)

**Comment by mcoker** [comment]
@mcarrano looks like this is an interaction issue.

**Comment by mcarrano** [comment]
Can we about @nicolethoen 's approach? Do we need to reconsider the design?

**Comment by mcoker** [comment]
I'm not sure how to handle it. It's an issue with the tabs, too. Because the arrows disappear once you get to the first/last item in the row, it's easy to click the arrows rapidly, then accidentally click a nav/tab item when the arrow disappears.

**Comment by mceledonia** [comment]
Can we have the arrows be persistent and not included in the total space for the tabs? We lose some horizontal space but it is a solution to this issue. We can have them switch to a disabled state (probably a custom one here as it's dark themed) when you reach either end.

**Comment by mcoker** [comment]
@mcarrano and I chatted about this and this is what we were thinking.

* When the horizontal nav items are fully visible (no overflow/hidden items), no scroll buttons
* When there is overflow, we display both scroll buttons
  * Whenever you're at the end of one side of the nav, we disable that button
* The scroll buttons display beside the nav items instead of on top of them

Does that capture the changes we'd like to make?

I also made some mockups for how to treat the disabled button. We currently have a dark themed button design that we implemented when we last aligned with the digital teams colors. The disabled color for an icon button in the dark theme is `#d2d2d2` (black-500).

<img width="256" alt="Screen Shot 2019-12-03 at 1 54 39 PM" src="https://user-images.githubusercontent.com/35148959/70085663-4dc28600-15d6-11ea-98ef-6c01dee51944.png">

You can barely tell the difference between the normal color (`#fff`) and the disabled color. Also, it's worth noting that the nav item color in the horizontal nav is `#d2d2d2`, so it wouldn't make sense for the disabled button to be `#d2d2d2` since that is the same color as the nav item.

Here, I've changed the disabled icon button to `#8a8d90` (black-500).

<img width="269" alt="Screen Shot 2019-12-03 at 1 55 02 PM" src="https://user-images.githubusercontent.com/35148959/70085895-c45f8380-15d6-11ea-989e-bfee47e7318c.png">

Here is what the nav looks like if the first button is disabled as `#d2d2d2`

<img width="657" alt="Screen Shot 2019-12-03 at 1 59 08 PM" src="https://user-images.githubusercontent.com/35148959/70085959-eb1dba00-15d6-11ea-97d8-987401f09a1b.png">

And here it's `#8a8d90`

<img width="682" alt="Screen Shot 2019-12-03 at 1 59 28 PM" src="https://user-images.githubusercontent.com/35148959/70085969-f2dd5e80-15d6-11ea-9628-47266e20d4bd.png">

And here it's 50% opacity

<img width="689" alt="Screen Shot 2019-12-03 at 1 59 16 PM" src="https://user-images.githubusercontent.com/35148959/70085986-fec92080-15d6-11ea-9b8e-c18d1fa62d67.png">

50% opacity and `#8a8d90` look pretty similar.

Also another consideration could be to use `#fff` as the default horizontal nav item color instead of `#d2d2d2`. It makes more sense for the vertical nav item color to be `#d2d2d2`, since on hover/focus/active in vertical nav, we change the color to `#fff`. However in horizontal nav, the hover/focus/active color is blue. Below is with that change:

<img width="649" alt="Screen Shot 2019-12-03 at 2 00 10 PM" src="https://user-images.githubusercontent.com/35148959/70086282-acd4ca80-15d7-11ea-958c-23b42d45f7bc.png">


Also wanted to loop in @lboehling and get her thoughts. Let me know if there was anything I missed @mcarrano

**Comment by kybaker** [comment]
@mcarrano @mcoker I like Michael's solution shown above. I suspect the current disabled state color was an oversight. Users should also get a cursor change indicating the arrow is disabled.

**Comment by lboehling** [comment]
Sorry for the (very late) response @mcoker ! I'm +1 for changing the default horizontal nav item color to #fff instead of #d2d2d2 and also darkening the disabled icon to black-500! much better contrast.
