### ISSUE TITLE
Does the tab content component always need to have a focus ring?

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#2484]
In some of the products that are using tab content under their tab components, they are getting a large focus ring around the content which is looking quite odd. 

My question is, is it necessary to have tab content with the tabs? And is it necessary to have a focus ring around the content ?

<img width="1072" alt="Screen Shot 2019-12-02 at 3 08 04 PM" src="https://user-images.githubusercontent.com/20118816/69991416-9c5c1b80-1515-11ea-8e0a-0471d67d1ab4.png">

@mfrances17

**Comment by mcoker** [comment]
@jessiehuff wdyt about this one?

**Comment by jessiehuff** [comment]
I was talking to @jgiardino about this one, and it looks like she used this [article](https://inclusive-components.design/tabbed-interfaces/#keyboardbehavior) from a pretty well known accessibility thought leader, Heydon Pickering, in determining the keyboard interactions here, particularly the "keyboard behavior" section. I think Jenn can explain it far better than I'm able to, but if I understood the logic right, it helps keyboard users better control what content they interact with.

**Comment by jgiardino** [comment]
To add some context for the article that Jessie mentions, this is the behavior recommended in the [WAI ARIA authoring practices for Tabs](https://www.w3.org/TR/wai-aria-practices-1.2/#keyboard-interaction-20):
> Tab: When focus moves into the tab list, places focus on the active tab element. When the tab list contains the focus, moves focus to the next element in the page tab sequence outside the tablist, which is typically either the first focusable element inside the tab panel or the tab panel itself.  

As a side note, we deviate from this a bit, in that we haven't implemented the Arrow key interaction (which we could always add as an enhancement to our Tabs component). So for now, the Tab key shifts focus among all the tabs, then on the last tab, shifts focus to the tab panel.

The only explanation provided for this is in the [example page](https://www.w3.org/TR/wai-aria-practices-1.2/examples/tabs/tabs-2/tabs.html#rps_label), where `tabindex="0"` is listed:
> - Facilitates movement to panel content for assistive technology users.
> - Especially helpful if there are panels that do not contain a focusable element.

The article that Jessie mentioned provides a little more explanation about why this is recommended. This [sub section](https://inclusive-components.design/tabbed-interfaces/#aproblemreadingpanels) starts to explain why this interaction is important:
> ### A problem reading panels
>
> Now that pressing Tab bypasses the tabs, it's trivial for keyboard users to move focus to the first of any links or other interactive elements in the open panel.
> 
> The experience for screen reader users is not currently as optimal. Although they too can focus elements inside the panel directly from the selected tab, blind users cannot see any content that comes before or after that interactivity. If there is no interactive content in the panel at all, they will unwittingly focus the first interactive element outside and below the tab interface.

So essentially, the Tab key take the screen reader user to the beginning of the content in the tab panel. This interaction would be more streamlined in our Tabs component if we enabled the Left/Right Arrow key interaction.

Aside from the screen reader use case, the only other use case I could think of where focusing the tab panel could be important is in the situation where the tab panel is a scrollable container. Whenever a scrollable div exists on a page, it's important to make sure the div can receive focus, so that keyboard-only users can use the arrow keys to scroll the contents in the div. This isn't a use case we support currently with the Tabs component, but just something to keep in mind.

**Comment by jgiardino** [comment]
P.S. The WAI ARIA authoring practice includes the phrase "which is typically either the first focusable element inside the tab panel or the tab panel itself." In the context of the PF react component for Tabs, I don't think we can detect if the consumer has included any focusable elements inside the tab panel. I think we're limited to only placing focus on the tab panel inself, since we provide that as part of the component. I could be wrong about this.

But it might be worth discussing if there is an option to enable the consumer to specify the first focusable element. So in the example above, the consumer would state that the first focusable element in the tab is "Repository" link. But if this isn't defined, then the default behavior is to have the tab panel receive focus.

If we do add this functionality, it would be worth explaining when the consumer should use the default. For example, the example above is probably fine, but if there are a lot of contents that precede the first focusable element, then they should probably default to focusing on the tab panel.

**Comment by jgiardino** [comment]
@mcarrano What are your thoughts on reopening this issue in pf-react?

@lboehling had pointed this out in [one of the UIs](https://docs.google.com/presentation/d/1wzr_gn4oc9SbjBbsLeDxEu2dovg9dcOOicuBS0JqgXw/edit#slide=id.gd48e8562ad_0_105) we were working on, and it's definitely odd behavior to see (even after we address the misc layout issues, it's still a bit odd that clicking anywhere in the tab panel places focus on it). 

But there are a couple of ways that we could address this so that this focus ring isn't popping up when we don't want/need it but we still support accessibility:
1. We replace `tabIndex="0"` with `tabIndex="-1"` and when focus is on the last tab, we listen for the Tab key press and programmatically place focus on the tab panel. This means the tab panel only receives focus via the Tab key and not via mouse click which most users find a bit odd.
2. We allow consumers to opt-out of having `tabIndex="0"`, and explain that they should only do this if the first element in the tab can receive focus. For example, in our case, our first element is a search field, so we don't need the tab panel to even be focusable, but we have no way to disable that behavior in the react component.

I kinda prefer the first solution since that requires no effort from the consumer (i.e. doesn't rely on the consumer to understand these rules and how to implement them).

cc @jessiehuff Since we were discussing this, but I only just now thought of option #1.

**Comment by mcarrano** [comment]
I agree that this is odd @jgiardino . @jessiehuff @tlabaj @mcoker what do you think? I'm all for re-opening it if there is a viable solution. Is this strictly a React issue?
