### ISSUE TITLE
Spacing for radio buttons is incorrect

### ISSUE THREAD

**Issue by serenamarie125** [patternfly/patternfly#2489]
Radio buttons should have appropriate spacing so the developer doesn't need to adjust

In the OpenShift Developer perspective, we have an open bug (https://jira.coreos.com/browse/ODC-2411) against the Deploy Image form.  Spacing can be seen here:
<img width="1009" alt="Screen Shot 2019-11-23 at 1 02 08 PM" src="https://user-images.githubusercontent.com/12504403/69483616-7dfc6e80-0df7-11ea-88ba-3d6334f50ccb.png">

They mentioned that this is a PatternFly issue.

**Comment by mcoker** [comment]
Thanks @serenamarie125 @christianvogt. The spacing for the vertical space between stacked radio components (and checkbox components, since it's nearly identical) should come from the layout it's used within instead of the component itself. Assuming this layout is used in the context of a form, we currently have an epic for forms (https://github.com/patternfly/patternfly-next/issues/919) that includes adding space between stacked form elements when placed within the same form-group. We'll discuss whether we should go ahead and introduce this versus scheduling the work in #919 and addressing it as part of that epic.

In the mean time, you can see in our [horizontal form demo](https://www.patternfly.org/v4/documentation/core/demos/basicforms#horizontal) where we have stacked checkbox components that have space between them from being placed within unique form group elements.

You can also see use of the inline form group layout in the [basic form demo](https://www.patternfly.org/v4/documentation/core/demos/basicforms#basic), which might be an option if you were to change the label for the radio options so that there is a main label for the group of radios that is the main description, then the label beside each radio is just "internal" or "external".

If this is a more custom layout outside of the context of a form, an option could be to use the stack or flex layouts, which would give you more flexibility over the spacing.

cc @mcarrano @rachael-phillips

**Comment by mcarrano** [comment]
See comment from @kybaker here: https://github.com/patternfly/patternfly-design/issues/776 We should be good to move forward with this and can adjust spacing as needed upon review.

**Comment by mcarrano** [comment]
We will address this as part of the Form demo updates we need to do. I've linked this to the design issue here: https://github.com/patternfly/patternfly-design/issues/858 and will close this.
