### ISSUE TITLE
Form Control textbox borders aren't clear

### ISSUE THREAD

**Issue by dsesami** [patternfly/patternfly#2581]
Here is an example from the [AWX Patternfly](https://github.com/ansible/awx/tree/devel/awx/ui_next) project:

![Screenshot from 2020-01-15 10-23-50](https://user-images.githubusercontent.com/19942822/72464020-88f1d080-37a2-11ea-8f42-4ce19b5caac0.png)

Borders in the top few fields have varying weight and are hard to discern. The "Labels" and "Credentials" fields, which appear to be a different type of Form Control (chip holder and multi-select types), are much clearer.

All of the form fields should be more uniform in their visibility. In my personal taste, the chip-holder in the "labels" field has the best border, so they should be closer to that perhaps, but at the very least they need to be improved.

**Comment by dsesami** [comment]
as @marshmalien pointed out, the multiselect border is actually hardcoded in AWX. See [here](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/MultiSelect/MultiSelect.jsx#L13). However, this issue stands for normal boxes.

**Comment by rachael-phillips** [comment]
@mcoker would you mind taking a quick look?

**Comment by mcoker** [comment]
@dsesami just so I'm clear, are you referring to the top/left/right borders on [form control](https://www.patternfly.org/v4/documentation/core/components/formcontrol) elements not being visible enough since they are thin and light grey in color?

**Comment by dsesami** [comment]
@mcoker that is correct.

**Comment by mcoker** [comment]
cc @kybaker @mceledonia

**Comment by kybaker** [comment]
@dsesami Understand your concern and we know it is a bit different than other design systems. We use the lighter borders on the side and top because accessibility standards require high enough contrast that made the field borders almost black. It was very hard to scan longer forms with a high density of fields using a full black border. 

One thing I noticed in the screenshot you posted above is you have a mix full black borders and the underline border style. You can see how we are using the consistent form style here in PF - https://www.patternfly.org/v4/documentation/core/components/form

**Comment by dsesami** [comment]
We changed our form style and it is now consistent within the application.
