### ISSUE TITLE
Update icon color variables

### ISSUE THREAD

**Issue by ajacobs21e** [patternfly/patternfly#2687]
The problem I noticed is we have a variables for two icon colors
`--pf-global--icon--Color--light` = secondary = black-600 = #6A6E73
`--pf-global--icon--Color--dark` = dark-100 = black-900 = #151515

We are missing one for white icons (used on dark theme). 

I talked with @mcoker and we propose revising the icon color variable names to something like this:
--pf-global--icon--Color: primary icon color, probably black-600
--pf-global--icon--Color--hover: probably our black color
--pf-global--icon--Color--light: white or light grey (used in the dark theme)
--pf-global--icon--Color--light--hover: whatever color changes to if you hover an icon in a dark theme
--pf-global--icon--Color--dark: copy of --pf-global--icon--Color
--pf-global--icon--Color--dark--hover: copy of --pf-global--icon--Color--hover

Another option is to set `--pf-global--icon--Color` to black since that's the majority of our icons, and then have something like
`--pf-global--icon--Color--secondary` = #6A6E73
`--pf-global--icon--Color--light` = #fff
and associated hover colors.

**Comment by gdoyle1** [comment]
@ajacobs21e I think I prefer the second option you listed there! It's more consistent with our text style variables which I think makes more sense for icons since sometimes they are in a component with text.

**Comment by ajacobs21e** [comment]
@mcoker @mcarrano Can this be prioritized please? This impacts the sketch library, which we currently have to use a text style color for white icons.

**Comment by mcarrano** [comment]
@mcoker is this an easy fix? Can't we also just fix the Sketch library if that's the hangup here @gdoyle1 ?

**Comment by mcoker** [comment]
We can't change any of the existing variables without that being a breaking change for users. I think in order to assign a variable for use in a dark theme, we would use `--pf-global--icon--Color--light` set to `#fff` as you suggested, but that would be a breaking change.

Though for what it's worth, icons take on the same CSS color property as regular text by default. So icons are black (`#151515`) by default, and if used in a dark theme, they become white since we change the default text color from `--pf-color-black-900` to `--pf-global--Color--light-100`. I'm not sure when we would use the black/white icon color vars in patternfly as the colors already change as expected.

The var block above with the hover states is something I mentioned and that's around our use of icons in buttons (like the plain button variation), since we currently use `--pf-global--Color--200` for those icons' colors and `--pf-global--Color--100` for the hover states, and it might make sense for those to use their own variables, but it sounds like that isn't necessarily related to the problem in sketch.

**Comment by ajacobs21e** [comment]
This was fixed in the sketch library. Do we need an update to the CSS if icons take on the text color in code?

**Comment by mcoker** [comment]
I don't think we need to make any updates. We're using `pf-global--icon--Color--light` in a few places, but that could just as easily be changed to `pf-global--Color--200` (text color) instead. Though we would want to do that in a breaking change release. Do we still need the `--icon` global color vars? They might be useful in the context of theming, but seems like they should be renamed to something like you have in your original description, which would also need to happen in a breaking change.
