### ISSUE TITLE
Global reset might be a problem

### ISSUE THREAD

**Issue by andresgalante** [patternfly/patternfly#285]
PF next depend on a rest, either pfnext reset or a reset coming from pf3 if the user is migrating.

@christianvogt spotted that this reset is too aggressive (as in not scoped) and might be a problem for applications running different frameworks alongside Patternfly.

This task is to investigate what's the better approach we have on scoping Patternfly reset, so an author can optin Patternfly styles in an aera or the whole application instead of been global by default.

**Comment by matthewcarleton** [comment]
This still needs some thought. We can refer to what @priley86 has been doing in the openshift space.

**Comment by rachael-phillips** [comment]
@matthewcarleton do we need to revisit this issue or have we resolved this?

**Comment by christianvogt** [comment]
There seems to have been many improvements with the resets since. However I still noticed there is a global reset. If the global reset isn't used, do PF4 components all look correct?
https://github.com/patternfly/patternfly-next/blob/ddf0b11b6c1f24cff38f925f27a5840bc862de79/src/patternfly/_base.scss#L135

**Comment by mcoker** [comment]
@christianvogt they do not, there are many styles in the reset that we rely upon for the base styling of PF4 components. @dgutride what do you think? We had talked about making the global reset a requirement.

**Comment by dgutride** [comment]
I thought we also needed to have the global reset as a requirement - I recommend if that's the way you want to go @mcoker - we just close this and add documentation to indicate that.

**Comment by mcoker** [comment]
Going to go ahead and close this since the global styles are a requirement at this point. We've never fully supported the presentation of components & layouts without the global reset. And with the v4 release, removing the shield styles makes it even more important to adopt the global styles to ensure components and layouts look as they should.
