### ISSUE TITLE
Improve responsive behavior of pages with vertical nav

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2907]
Want to improve the way our page responds as the viewport width is reduced. This is especially true for pages with tables that have lots of rows and content. Content becomes compressed before navigation sidebar hides leaving an unusable page. Need to investigate this problem together with Core to explore alternative approaches.

Here is an example of what this currently looks like: https://slack-files.com/T0FA4HM8D-F010YDKLLVB-6ecfe221e7

cc @kybaker @LHinson

**Comment by mcoker** [comment]
@mcarrano @kybaker and I met today and agreed to change the breakpoint at which the page sidebar collapses from `$pf-global--breakpoint--md` to `$pf-global--breakpoint--xl`.

This will also involve updating the left/right component and page chrome padding changes that happen at `$pf-global--breakpoint--md`, so that they happen at `$pf-global--breakpoint--xl` instead.
