### ISSUE TITLE
Expandable table rows on mobile/tablet have the arrow pointing up rather than down

### ISSUE THREAD

**Issue by gdoyle1** [patternfly/patternfly#2932]
When expandable tables become responsive, the expand icon ends up pointing up with that row is expanded. On desktop, it points down and same with all states in data list. Proposing we rotate that arrow so it points down upon expansion for all break points.

cc: @mcoker @christiemolloy

**Comment by gdoyle1** [comment]
To go along with this - our wizard changes the direction of the caret in the dropdown when it is expanded - which we don't do anywhere else. Can we make that consistent with other components and use caret-down the whole time?
<img width="659" alt="Screen Shot 2020-04-08 at 5 08 54 PM" src="https://user-images.githubusercontent.com/30870144/78833963-c938a780-79bb-11ea-81f1-8678508c6ddb.png">

**Comment by mcoker** [comment]
Also just to confirm, the variation of our dropdown/select/etc components that expands the menu upward instead of down has a different arrow, too. It points down when collapsed, and up when expanded. Is that OK?

<img width="460" alt="Screen Shot 2020-04-09 at 7 08 47 PM" src="https://user-images.githubusercontent.com/35148959/78950856-b4304700-7a95-11ea-9b1e-335c936c14dc.png">
<img width="455" alt="Screen Shot 2020-04-09 at 7 08 42 PM" src="https://user-images.githubusercontent.com/35148959/78950858-b4c8dd80-7a95-11ea-8bfa-f5481fa96445.png">

**Comment by gdoyle1** [comment]
@mcoker I think that can stay the way it is since the menu is opening above the toggle!

**Comment by mcoker** [comment]
@gdoyle1 this was fixed in the v4 release. Do you mind verifying and closing the issue if it looks ok?

**Comment by gdoyle1** [comment]
Yes this is fixed! I'll close this @mcoker
