### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#296]
Interaction design and React to first determine which slider will be used.

https://www.patternfly.org/pattern-library/forms-and-controls/slider/

#180 has open questions that also impact this issue. Need to determine where the CSS lives and if we are using a third party library.

**Comment by LHinson** [comment]
Yes, hold tight while I found out more. I'll get back to you asap

**Comment by maryshak1996** [comment]
Thanks @LHinson

**Comment by LHinson** [comment]
@maryshak1996 After talking with Joachim, I think we need to first open an investigation story on React before we can proceed with visuals. Therefore we are going to put this one back on the backlog and hold off. For that reason, I'll also un-assign you for the time being. Apologies about that!

**Comment by maryshak1996** [comment]
Hey @LHinson no worries! Thanks for the update!

**Comment by maryshak1996** [comment]
@mcarrano @gdoyle1 I've put together a handful of different ways to look at (a) discrete sliders, (b) continuous sliders, and (c) codependent slider
I don't recall the codependent slider being in the requirements, but @bmignano and I a codependent slider that the kiali team had a need for, so there is at least some teams that would appreciate this being a part of the patternfly components. 
I'm curious as to your thoughts on if the various options that I'm presenting here for the discrete and continuous sliders are all variations that should be available in PF4, or if we should come to a consensus on have, for example, just top-aligned numeric indicators as opposed to right-aligned. I think that there are arguments to be made for having one for the sake of consistency, but I also think that there are times when the layout of a page might be more conducive to one alignment over another. Here's what I've got:
![screen shot 2019-03-04 at 11 46 25 am](https://user-images.githubusercontent.com/19824574/53814764-429ad680-3f2e-11e9-8bc8-45e10abb32bf.png)

**Comment by gdoyle1** [comment]
@maryshak1996 @mcarrano  I think it would make sense to recommend using the designs that have the percentages to the right of the slider (Option 3 discrete, Option 1 continuous) and then if they don't have enough space, they can use the slider alone (Option 1 discrete, Option 1 continuous). I do think it is worth showing the codependent slider if we needed it beforehand too! Also would show that the slider is customizable if needed.

**Comment by mcarrano** [comment]
I agree with @gdoyle1 . The other thing I've seen is to show a tooltip with the value when the user hovers over the slide handle. The only other thing I'll say is that the text field with the underscore looks a bit odd in this context (I know that's our standard text box). @mceledonia would be interested in your thoughts.

**Comment by maryshak1996** [comment]
@gdoyle1 @mcarrano thanks for your input on this! Ya @mceledonia, I was also curious about your thoughts on if the input field should be treated this way. I figured it would be, because otherwise this would be the only area not using the basic text input field, but I'm interested to see what you think.

**Comment by maryshak1996** [comment]
sorry for how delayed this update is, but @mcarrano @mceledonia @gdoyle1 how do you think that this works?
![Screen Shot 2019-03-19 at 9 34 47 AM](https://user-images.githubusercontent.com/19824574/54609983-67ad4000-4a2a-11e9-85bd-2f95a70e273c.png)

**Comment by maryshak1996** [comment]
@mcarrano my thinking is that the text boxes on the end would provide that ability to track the value being selected. I made mockups that don't have the text input field in case their is a use case for it but for accessability, I feel that we should either (a) always have that text field or (b) require the tooltip when the text input field is not there. 
To address your question about use cases for the codependent sliders and add+subtract sliders, this is something that I had to create for kiali service mesh (screenshot below) as an element of one of their modals, with the main difference being that they wanted to use a pin instead of a lock icon
![Screen Shot 2019-03-19 at 9 42 53 AM](https://user-images.githubusercontent.com/19824574/54610437-67fa0b00-4a2b-11e9-91a3-f42f2cd39f85.png)

**Comment by gdoyle1** [comment]
@maryshak1996 @mcarrano Mary I agree we should always have the text input field at the end of the slider for continuous sliders so that the value can be tracked at all times. I think we should also allow for labels on the end points for continuous sliders - yes you can figure out the same information by using the slider, but it is easy to see it right away if the end points are labeled.

**Comment by maryshak1996** [comment]
Ooooo I think I know what you mean @gdoyle1. are you referring to something like this?
![Screen Shot 2019-03-19 at 10 03 15 AM](https://user-images.githubusercontent.com/19824574/54611921-4cdcca80-4a2e-11e9-8367-5942ab7f32d2.png)

**Comment by gdoyle1** [comment]
@maryshak1996  Yup exactly!

**Comment by maryshak1996** [comment]
@mcarrano here they all are with those labels
![Screen Shot 2019-03-19 at 10 12 18 AM](https://user-images.githubusercontent.com/19824574/54612563-8e21aa00-4a2f-11e9-8e03-cbbd89e225e4.png)

**Comment by mcarrano** [comment]
+1 It's less critical for something like percentage because w know the range is 0-100%. But sliders could be used for things with any range so in that case these labels are helpful.

Regarding the codependent and add/subtract sliders, these are legitimate use cases that we could include in the documentation as examples of slider usage. But I think they are too specific to build into a component. @maryshak1996 I think you can leave them in your Sketch file with a note that these are optional extensions (not required).

**Comment by maryshak1996** [comment]
@mcarrano yup that sounds perfect! 
I'll make that update (optional extensions, more forward-looking work) and put together a spec, if things seem good to you and @gdoyle1

**Comment by gdoyle1** [comment]
@maryshak1996 That sounds great! Send it along to me whenever it's done

**Comment by maryshak1996** [comment]
https://redhat.invisionapp.com/share/SNR36B98TAP
Here's the "final" design and visual spec :) let me know if anything needs to change

**Comment by mcarrano** [comment]
This looks great @maryshak1996 . As a note to implementers, we should have 2 variations of the component - the Discrete slider and  the Continuous slider. The optional extensions may be interesting as a demo for a future date, but these do not need to be part of the basic slider. 

@mcoker does this look good to you?

**Comment by mcoker** [comment]
@mcarrano @maryshak1996 this looks great to me. Just to confirm, this is going to be a completely custom implementation and we are not utilizing a library? I looked at the issue referenced in the description (https://github.com/patternfly/patternfly-next/issues/180) but I don't see anything about the range slider there, just the date/time picker.

**Comment by mcarrano** [comment]
That's a good question @mcoker . @rachael-phillips we should get someone from the React team involved.

**Comment by rachael-phillips** [comment]
Ok sounds good to me. @dlabaj do you mind taking a look at this issue and advising on what we'll need to do from the React side?

**Comment by lwrigh** [comment]
Are there any more updates on this issue? A component like this would be great for some RHV use cases.

**Comment by rachael-phillips** [comment]
Hi @lwrigh this is currently slated for our 2019.10 milestone - check it out here: https://github.com/patternfly/patternfly-next/milestone/26

What release for your product are you targeting?

**Comment by lwrigh** [comment]
@rachael-phillips Great that's good to know! It's not committed to a release yet but I was curious.

**Comment by garrett** [comment]
We still need a PF4 slider in Cockpit and greatly appreciate the forward movement on it by the team, regardless of what stale-bot might "think".

**Comment by mcarrano** [comment]
@garrett This issue is currently on our roadmap targeted for 2020.14 release (end of October).

**Comment by garrett** [comment]
@mcarrano: Thanks! Super happy to hear this. Looking forward to dropping PF3 and adopting PF4 for yet another widget in Cockpit. :+1:

**Comment by mcoker** [comment]
@mcarrano do you want to leave this open?

**Comment by mcarrano** [comment]
Yes. We will get to this eventually!

**Comment by maryshak1996** [comment]
The previously posted invision file is not viewable and is a bit out of date so here is the new design file :) https://www.sketch.com/s/6f81d099-0c11-407a-8962-5672df30dcf2
The latest sketch update is having issues connecting to marvel, hence the sketch cloud link instead of a marvel link

**Comment by garrett** [comment]
We've been waiting on this component for Cockpit for a while and had restyled PF3 to look like these mockups quite some time ago. (Like all the other widgets.)

Meanwhile, we have also been ripping out PF3 and replacing with PF4 as time has gone on. @KKoukiou asked me to look at this today, so I spent some time making the native `<input type="range">` look like the old mockups. With just a few variable tweaks, I have it looking like the revised mockups. And since it's a native widget, it already comes with accessibility baked in.

The plan was to upstream this work to PF4.

Is someone working on the implementation already? I'm happy to donate what I have so far, if we'd want to go this route of a native widget (instead of a bunch of nested divs + JS + ARIA, etc.). I just need to finish polishing it.

**Comment by mcarrano** [comment]
@mcoker ^^^

@garrett sorry this has gotten pushed out so many times, but yes, we are finally getting work started on this.

**Comment by mcoker** [comment]
@garrett to support the current and future enhancements to design and functionality (to do things like enable 2 thumbs down the road), we've gone with a custom implementation instead of using the native HTML select with a11y taken from the [w3.org WAI-ARIA slider example](https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-1.html).

I'm happy to look at your code if you would like to share.

**Comment by garrett** [comment]
FWIW: Here's the work I did today on making a PatternFly-styled `<input type="range">` that works cross-browser @ https://codepen.io/garrett/pen/RwRXGdY

The only JS I have on it is to set a custom property for the progress line, as that's not supported via pure CSS in WebKit/Blink (but it is in Firefox). It's still rendered by CSS, however.

Perhaps some of it could be adapted at least.

**Comment by mcoker** [comment]
@garrett thanks!
