### ISSUE TITLE
PF4 Modal: rethink the the modal position

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#2980]
While we were using PF3 modals the modal position was on the top of the screen while when I tried to switch to PF4 modals I immediately noticed that the modals are moved to the middle of the screen.
Was that a conscious decision?

In [cockpit](https://github.com/cockpit-project/cockpit) we perform the PF3 => PF4 migration in a way that we override the PF3 components with style rules that make them look like PF4, and then slowly port to PF4 component. In order to avoid that the dialogs that are already ported to PF4 (in this case) will behave differently than the ones that are still PF3 we need to overwrite the placement of the PF3 ones.

Before doing that I would like to get some feedback if the dialog placement has been discussed and thus changed.

**Comment by garrett** [comment]
Modals should never be aligned to the center. They should either appear toward the top or centered with a top bias.

---

Here's Apple's `center()` for windows: https://developer.apple.com/documentation/appkit/nswindow/1419090-center

> The window is placed exactly in the center horizontally and somewhat above center vertically. **Such a placement carries a certain visual immediacy and importance**.

---

Here's window placement from Microsoft's docs: https://docs.microsoft.com/en-us/windows/win32/uxguide/win-window-mgt#window-location

> For the following guidelines, "centering" means to bias vertical placement slightly towards the top of the monitor, instead of placing exactly in the middle.

And they're explicit on the values used too (45 above, 55 below):

> Put 45 percent of the space between the top of the monitor/owner and the window top, and 55 percent between the bottom of the monitor/owner and the window bottom. Do this because **the eye is naturally biased towards the top of the screen**.

**Comment by garrett** [comment]
On mobile, it's _a little different_.

Generally, actionable content is placed toward the bottom of the screen:

### iOS
- Action Sheets: https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/
- Activity Views: https://developer.apple.com/design/human-interface-guidelines/ios/views/activity-views/

### Android
- Sheets: https://www.material.io/components/sheets-bottom
- Snackbars (generally bottom-aligned, but may be contextual): https://material.io/components/snackbars

---

_However_, both iOS and Android have traditional dialogs too, and those are vertically centered (dropping the nudge to the top, which is naturally made with a navigation bar (when one exists) and moving it up would also move actionable buttons further from fingers):

- iOS Alert: https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/
- Android Dialog: https://www.material.io/components/dialogs

In the case of iOS, traditional dialogs are used sparingly, mainly for alerts. Most other things use sheets. Android has also moved to this same model in the past few years (preferring bottom-aligned sheets), as seen in many first-party Google apps, such as the recent redesign of Google Maps.

Both generally use secondary full screen views for entering additional content, however.

---

So, for mobile:

I'd recommend investigating a bottom-aligned modal in the case of mobile, with the top always visible (in case the modal goes off the screen, where the content is not scrolled, but the dialog itself should be scrolled). Basically, "emulate" the concept of sheets.

Or consider possibly stretching a dialog vertically if it's smaller than the screen (so title is at top, buttons are at the bottom).

In either scenario the dialog is vertically larger than the screen, either the content would need to scroll with an overflow (which can cause issues with elements that should pop over, like custom non-native selects, popovers, tooltips, and so on), or the whole dialog should be scrollable (as it is in PF3). The whole dialog being scrollable would be a better choice, due to the aformentioned content overflow truncation issues.

**Comment by mcarrano** [comment]
@garrett @KKoukiou It was a conscious decision to center align all dialogs in PF4 and allow then to grow in any direction, as needed, to accommodate more content. We felt that small dialogs like alerts and confirmations were best placed at the center of the screen to get the user's attention, and that this was the best consistent solution to use for all modal dialogs.

I know that Apple has long advised that dialogs be positioned near the top of an application window, but keep in mind that both Apple and Microsoft guidance was generally developed for desktop applications vs. browser-based applications. I do think that you raise some good points about mobile placement and I will admit that our approach can be improved there. This has not been a major issue for us, but if you expect a high level of mobile usage, it's something we can look at more closely.

**Comment by KKoukiou** [comment]
@garrett the dialog position seems to be a conscious decision so I will close this issue.
For mobile specific requests please open separate issues.
