### ISSUE TITLE
Update Notification Drawer beta component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2993]
Want to update the notification drawer component as follows:

* Make ability to display read/unread notifications an optional feature.
* Add optional filtering
* Simplify styling of notification items.

See revised designs here: https://marvelapp.com/4f0341a

cc: @mcoker @LHinson

**Comment by mcarrano** [comment]
After discussion with @LHinson and @mceledonia I'm placing this on hold for now. We still may want to make these styling changes at a later date, but let's try to get the current implementation out there before making any updates that might affect early adopters.

**Comment by mcarrano** [comment]
Let's keep this issue open until I can get more guidance from the Openshift team on whether we want to integrate these changes.

**Comment by mcoker** [comment]
@mcarrano adding the design approved label so it will remain open. Feel free to modify that as you see fit.

**Comment by mcarrano** [comment]
@mceledonia @gdoyle1 This issue was opened last year with some proposed changes to the notification drawer visuals. It was put on hold, but I'm wondering if it would be a good time to reconsider if we are also adding tasks to the drawer. Thoughts?

**Comment by gdoyle1** [comment]
@mcarrano Sounds like a good idea - I'd have to draw that up with the tabs but seems reasonable!

**Comment by nicolethoen** [comment]
It looks like the first and possibly the last items on this issue have been addressed.
@mcoker pointed out that there are 'simpler' notifications included in [the status card with expanded notifications demo](https://www.patternfly.org/v4/components/card/html-demos#status-card-expanded-notifications).

so all that is left of this issue is to build a sort of notification drawer toolbar or filter that can be added under the header.
@mcarrano do you want to add this to a future milestone?

**Comment by mcarrano** [comment]
No one has explicitly asked for these enhancements, although I think adding the filter bar is worth doing as an optional feature. @nicolethoen @mcoker can this be done without breaking anything? If so, I will add it to the roadmap.

**Comment by mcoker** [comment]
@mcarrano yep, should be an easy update.

**Comment by mcarrano** [comment]
OK. Will get this back onto the roadmap for adding optional filtering.
