### ISSUE TITLE
Notification badge enhancements

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#2994]
Update the Notification Badge component to include an optional count field and attention state. Designs here: https://marvelapp.com/4f0341a

cc @mcoker @lhinson

**Comment by mattnolting** [comment]
![image](https://user-images.githubusercontent.com/5385435/85068936-3bc6c000-b181-11ea-82c4-6e2637abf6b6.png)

**Comment by mcarrano** [comment]
@mceledonia ^^^

**Comment by mattnolting** [comment]
![image](https://user-images.githubusercontent.com/5385435/85148503-39ff0a00-b21e-11ea-8881-1a0138663ef6.png)

![image](https://user-images.githubusercontent.com/5385435/85148594-51d68e00-b21e-11ea-9258-000f3fe4b0fb.png)

**Comment by mattnolting** [comment]
@mcarrano @mceledonia http://notification-badge-enhancements.surge.sh/

1) The button border-radius look larger for notifications because the border is applied to the outside of the button in sketch, rather than inside. As a result, I added 5px border radius `--pf-global--BorderRadius--md` to match design.
2) Will unread and attention states ever both apply to a notification? If so, does the `attention` state override the blue border of the `unread` state? That is my assumption.

Please look at look at each of the examples in the demo and let me know if this meets your expectations.

Thanks!

**Comment by mcarrano** [comment]
I think that these are looking good @mattnolting . Just a couple of questions/comments:

* Regarding (2), yes that would be my assumption, too. Attention state implies something critical that's also unread.
* I believe that there are also versions of these that include the count. Is that correct @mceledonia ?
* I like the appearance of the selected states, but it does raise a question. Previously we had defined a round selection state shown for these icons like what's shown here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/notification-drawer  Do you know if that was ever implemented for other masthead icons @mcoker ? I think it would look odd to have the rectangular and circular shading side by side. If it's not implemented everywhere, then I like this effect (the rounded rectangle) better for all masthead icons.
* We have a current Notification badge component that was the original design. Can we just replace that or are we intending to add this as a new variant?

I'll defer to @mceledonia on the visual questions.

**Comment by mceledonia** [comment]
Thanks Matt -

1. Looks good, nice catch and good adjustment.
2. Unread and attention are mutually exclusive. Unread is a classic unread state "you have a new notification(s)" and Attention is "you have new notifications **and** there's something you should really see here. Like an evolution of the unread state.
