### ISSUE TITLE
design question for the split button

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3042]
As a follow-up to #3038 , we want to confirm with design about the states of the dropdown split button variation. 

The component is structured with a `<div>` for the `toggle` element and then a `<button>` for the dropdown button inside of it (with the arrow).

Currently, when you click on the dropdown button, the toggle element receives hover,active,focus styling:

<img width="178" alt="Screen Shot 2020-04-28 at 3 05 47 PM" src="https://user-images.githubusercontent.com/20118816/80527244-0d3b1e80-8962-11ea-9047-dc8528d82557.png">

We want to confirm with design as to whether the dropdown button should have hover,active,focus styling when you click on it, because right now there is nothing. E.g. if you click on the dropdown, but then move your cursor so that you aren't hovering over the toggle element, there will be no styling

<img width="169" alt="Screen Shot 2020-04-28 at 3 08 40 PM" src="https://user-images.githubusercontent.com/20118816/80527390-4a9fac00-8962-11ea-80bd-c2a90477c96c.png">

cc: @mcarrano @mcoker

**Comment by mcarrano** [comment]
@christiemolloy So if I understand your question correctly, you want to know whether the "v" icon should have styling to reflect state, correct? Right now none of the dropdowns do to my knowledge. 

I don't see any reason that they need to, although the Split button is a bit of a spacial case since the down caret takes events separate from the checkbox. I don't feel strongly about this. I wouldn't be opposed to adding hover and active states to the button, but as far as I know, what we have now is not a problem. Thoughts @mceledonia ?

**Comment by mceledonia** [comment]
@mcarrano @christiemolloy I agree for the most part, since there are two targets here I can see where it would be nice but it doesn't seem too necessary. That being said if it's an easy add and doesn't cost us much it could be a nice detail enhancement. If we were to add a hover state for the caret icon I'd suggest: 

Default / not hover: Secondary gray - #6a6e73 
Hover: Primary gray - #151515

**Comment by mcoker** [comment]
I believe @christiemolloy is referring to the blue border at the bottom of the toggle element (div that wraps the checkbox and button with the dropdown arrow). Normally when you hover the toggle, there is a 1px blue bottom border, then when you click/focus on it there is a 2px blue border (also present for the expanded state).

For this split button checkbox example, there is a 1px blue border if you hover anywhere over the toggle wrapper, and a 2px blue border when you click anywhere in the toggle wrapper (the `:active` state), but when you focus on either the checkbox or dropdown arrow, there is no blue border. Should we update any of that behavior? 

The example is here - https://www.patternfly.org/v4/documentation/core/components/dropdown#split-button-checkbox

And here's what happens

![Jun-23-2020 17-15-21](https://user-images.githubusercontent.com/35148959/85470810-2bde2000-b575-11ea-8e22-8a83f1649292.gif)

For comparison, here is what happens with the [split button (action) example](https://www.patternfly.org/v4/documentation/core/components/dropdown#split-button-action)

![Jun-23-2020 17-16-18](https://user-images.githubusercontent.com/35148959/85470913-4dd7a280-b575-11ea-9887-6bb5fec9d192.gif)

**Comment by mcarrano** [comment]
Ah, OK, I see the difference @christiemolloy @mcoker . IMO this is so subtle that I don't think anyone (except developers with a keen eye) will notice :) I have a feeling it's this way because the split checkbox button appears as one element where the split action button has the divider that creates two distinct elements. I'd rather not mess with this unless we are getting user feedback that suggests it's a problem.
