### ISSUE TITLE
Investigation: Third Party Forms

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3174]
@janwright73 asked me to document my experience working with third party forms in products.

When working on the Mobile Developer Console (Aerogear) they were using a third party Form, which we needed to convert to PatternFly. There were two forms, I'm not sure if they were from different third parties.

**Form 1**
We transferred all the functionality from the third party Form to the PatternFly form. It was a little difficult to understand what the Third Party form was doing and then transfer that to PatternFly's Form, but it definitely was achievable.

**Form 2**
This form was in a modal and they were pulling the form in differently so we weren't able to convert it to PatternFly like in Form 1. However, we made CSS overrides by targeting the classes in the third party form and applying PatternFly form styles.

This is my experience so far with third party forms, but hopefully other developers also have experience. My suggestion is to try to convert the form to use PatternFly's functionality, and then if we don't have that functionality, override the CSS of the Third party form.

**Comment by janwright73** [comment]
@jeperry, @TheRealJon - any related efforts to styling 3rd party forms that we can track in this issue?

**Comment by jeperry** [comment]
I'm not sure if Data Drive Forms (DDF) qualifies as third party, but they use PF. I think we could do more to help them stay up to date with PF forms changes and possibly offer some advice. A number of RH products do use DDF. https://github.com/data-driven-forms/react-forms and see https://medium.com/javascript-in-plain-english/data-driven-approach-to-forms-with-react-c69fd4ea7923

**Comment by TheRealJon** [comment]
In my experience with https://github.com/rjsf-team/react-jsonschema-form, overriding the default styles was more complicate and not as well documented as it should be. Here are some pain points I ran into:
- In order to really meaningfully change the styles, you have to override most of the default components used to render the form. 
- It is difficult to know exactly which components to override and how they work together because of the way the docs are structured. 
- The docs focus on specific use cases instead of the overall API. On several occasions I had to dig into the code base to figure out exactly why something was behaving in a certain way. 

That all being said, the reason we chose this package was to dynamically generate forms from JSON Schema data, which it does really well. It just took a little bit of overhead to figure out the quirks, like with any new tool.
