### ISSUE TITLE
Navigation separators don't look right

### ISSUE THREAD

**Issue by jeff-phillips-18** [patternfly/patternfly#3208]
The navigation separators don't take up the full width and are not distinctive:

![image](https://user-images.githubusercontent.com/11633780/85404831-86ec2480-b52d-11ea-8696-a7b855070f3e.png)

**Comment by mcoker** [comment]
@jeff-phillips-18 this was a bug in the react component and fixed in https://github.com/patternfly/patternfly-react/pull/4362

**Comment by jeff-phillips-18** [comment]
Here is what it looks like now:

![image](https://user-images.githubusercontent.com/11633780/86152427-23826980-bace-11ea-83ed-5c9b615b64a0.png)

**Comment by mcoker** [comment]
cc @mcarrano @mceledonia - do we have a recommendation on using dividers in top level navigation?

![image](https://user-images.githubusercontent.com/35148959/86158326-3d23b100-bace-11ea-9232-d13bf6d6eeb8.png)

**Comment by mceledonia** [comment]
All top level nav items should be separated with a single divider. To clarify, is this a second divider meant to divide between main sections of the nav?

**Comment by mceledonia** [comment]
A couple ideas for how to approach this from my perspective...

**1. Switch to the "grouped" navigation style and remove group subheaders, or keep them if they're useful here.** 
My only concern here would be the inconsistency between admin and dev views, as the "grouped" nav variant has different styling. It features divider lines only between groups of items rather than after each item. This inconsistency isn't necessarily a bad thing, perhaps it's useful to help quickly distinguish between perspectives. I'd want more opinions on this though, @beanh66 @gdoyle1 any thoughts?

Example of how that looks, compare to how admin console nav looks. Note only divider lines between major groups rather than all top level items.
![image](https://user-images.githubusercontent.com/30935938/86172938-29d40e00-baed-11ea-8b8d-c5aa69567721.png)

**2. Manually alter the current styling to better represent major groupings**
I'm not sure of the effort or resources involved in this but it's an option. My best suggestion right now is some sort of thicker bar between larger sections, mock up below: 
![image](https://user-images.githubusercontent.com/30935938/86173564-27be7f00-baee-11ea-9a6e-10be03bb7de9.png)


The reason we don't really have a great middle ground solution here is typically we're suggesting using one variant or the other. If there's a need for grouping nav items with no parent item above them, use the group variant, and if there are parent/child items, use expandable. In this case the admin console has a great use case for expandable, and dev console has a great use case for grouped, but it's up to us to decide if the inconsistency between the two is ok or if we should try to augment expandable in order to reach a middle ground solution.

**Comment by beaumorley** [comment]
@mceledonia @jeff-phillips-18 

If we have to do something quick to fix this, I i think the first option you've proposed is better. I don't think we want expand/contract capability because the point of pinned nav is that it is one click accessible. Would the grouped items be indented?

The second option seems distracting (larger stroke between items). The other alternative is to just take out the grouping all together until we can revisit this. 

@serenamarie125 should weight in.

**Comment by beaumorley** [comment]
@mceledonia 

I looked up the design doc around why the Dev navigation is the way it is. 

There are 3 sections in the nav.

1. Task Based navigation : +Add, Topology, Monitoring, Search
2. Object Based navigation : Builds, Pipelines, Helm, Project
3. Items “added” to the navigation

I'm trying to think how we could align with the new Admin convention but retain what we are trying to do here. I think the Task Based on the Dev side is the same as the categories on the Admin Side. 

Could we override the new style for the "added" items? So they have no border?

**Comment by jeff-phillips-18** [comment]
Workaround in OpenShift Console: https://github.com/openshift/console/pull/5971
