### ISSUE TITLE
Select menu with filtering and favorites

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3209]
Need an example of  a Select menu that supports type-ahead filtering and favorities functionality equivalent to what we support for Application Launcher here: https://www.patternfly.org/v4/documentation/react/components/applicationlauncher#with-favorites-and-search

Design mockups below:

![image](https://user-images.githubusercontent.com/6619860/85412902-1a2a5780-b538-11ea-8d42-d5ae7aed406c.png)

We should also consider whether it makes sense to break Favorities out into a modular component that can be reused in multiple places (e.g. tables, etc).

cc @mcoker

**Comment by mcoker** [comment]
@mcarrano 

1. What is the "Create project" text in this menu? Is that part of the feature, or just part of the design?
1. Should items retain the selected state check mark? Assuming so, what would that look like? 
1. Does this need to work with checkbox select?

**Comment by mcarrano** [comment]
Good questions @mcoker .  @gdoyle1 can you help answer the first two?

As for the checkbox select, I have a hard time seeing the use case for favoriting checkbox items, but you never know. I would not include that for now unless it makes things easier in some way.

**Comment by gdoyle1** [comment]
1. "Create project" is an action in this example - trying to say that these can be added into a dropdown so that some items can be favorited and some items can still act as actions
2. I thought we had discussed that we wouldn't allow for two icons in one item @mcarrano ? If that's not true, then I'd expect the checkmark to be to the right of the favorite star here

**Comment by mcoker** [comment]
> "Create project" is an action in this example - trying to say that these can be added into a dropdown so that some items can be favorited and some items can still act as actions

Ah, this issue is to add the feature to the select menu. Just want to confirm we should add this to the select and not the dropdown for this task? @mcarrano 

> I thought we had discussed that we wouldn't allow for two icons in one item @mcarrano ? If that's not true, then I'd expect the checkmark to be to the right of the favorite star here

It seems like you would still want some indication of what item is selected? Here are a couple of screenshots:

<img width="653" alt="Screen Shot 2020-06-30 at 10 13 00 AM" src="https://user-images.githubusercontent.com/35148959/86143702-60446580-baba-11ea-99bc-3c0d728e53ca.png">
<img width="659" alt="Screen Shot 2020-06-30 at 10 11 50 AM" src="https://user-images.githubusercontent.com/35148959/86143704-61759280-baba-11ea-9472-d0b1de3c89fd.png">

**Comment by mcarrano** [comment]
@mcoker Yes, this is to be added to a Select menu and not a Dropdown.

Regarding the Create project action, @gdoyle1 , I must have missed this when we reviewed the design but we currently don't support mixing actions and items in the select menu. Is there a way you can think of for handling the create use case outside of the menu? Otherwise we can investigate adding a Create action to the menu, but to be consistent, this should probably be available as an option for any Select. Typeahead select does support that if the user types a name that's not included in the list, so we could consider something similar.

As for reflecting selection, I like the second option, with the understanding that the check icon is not interactive. It's just there to indicate current selection. What do you think @gdoyle1 ?

**Comment by gdoyle1** [comment]
@mcarrano @mcoker 

We could figure out an area for the create project to go probably (outside the menu)... most importantly we'll need the select menu with favorites so this works!

I like the second option as well!

**Comment by mcarrano** [comment]
Thanks @gdoyle1 Let's just leave the Create project item out of the menu to keep it simple.
