### ISSUE TITLE
Add variable for global blue color

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3271]
The color variable `--pf-global--palette--blue-50` has come up in the Alert, Hint and Label components as a background color... so we think it would be beneficial to add it as a variable in our `scss-variables.scss` file.

What does design think about the naming ? Maybe it could be another "info" variation or a "background" color variation. Here is the file where we have our color variables: https://github.com/patternfly/patternfly/blob/master/src/patternfly/sass-utilities/scss-variables.scss 

@gdoyle1 @mcarrano @mceledonia @maryshak1996 

Related to #3218

**Comment by gdoyle1** [comment]
@christiemolloy I like the idea of adding it in as a background color or another "info" variation - although I think info could be too specific for the Label component since it doesn't _have_ to be an "info" related label. It does work for the hint and alert components though! Interested to hear what others think
