### ISSUE TITLE
Table checkbox UX is not correct

### ISSUE THREAD

**Issue by karelhala** [patternfly/patternfly#3288]
When you hover over a checkbox in table the cursor remains the same (`default`) whereas it should change to a hand (`pointer`). Also the target area for checkbox is incorrect it should be slightly larger than just the checkbox so users has easier time clicking in the area.

**Comment by karelhala** [comment]
ping @mcoker @mattnolting

**Comment by bclarhk** [comment]
I believe industry standard click target is still 44x44. Feel free to ping me with any questions!

**Comment by mcoker** [comment]
cc @jessiehuff @mcarrano we've discussed the clickable area of checkboxes (and radios) in the past. I created a POC PR (https://github.com/patternfly/patternfly/pull/2745) with custom designed checkboxes and radios that increased the target area - https://patternfly-next-pr-2745.surge.sh/documentation/core/components/check

Do we want to consider adding that in? I think the concern was that it could be a breaking change since the elements take up more space and we can't guarantee it won't impact layouts adversely. There are other ways of increasing the target area without changing the checkbox/radio size, too, like this https://codepen.io/mcoker/pen/XWXPRww. In that example, the grey background indicates the clickable area, and you can change its size by modifying the `--inset` value in the top/middle (CSS) pane.

**Comment by mcarrano** [comment]
I know this has come up before and I would be in favor of updating this as long as we can accomplish it in a non-breaking way. I can add this to the roadmap for further investigation.

**Comment by jgiardino** [comment]
I just posted a [comment in a similar issue](https://github.com/patternfly/patternfly/issues/865#issuecomment-663162700) regarding WCAG requirements (TLDR, there aren't any).

@mcoker -  I don't get the larger target area or background color in Firefox in this pen >>> https://codepen.io/mcoker/pen/XWXPRww

Something else to consider is to focus only on checkboxes that display in tables and datalists (i.e. checkboxes that aren't accompanied by `<label>` elements), and wrap the checkbox with a `<label>`. This would allow us to control the size of the clickable area by controlling the size of the label. This seems a bit hacky, but is the best suggestion I have for a major shortcoming of modern web development. If we did this, we might want to move the aria-label from the  `<input>` to a sr-only span inside the label (because it seems wrong to use `<label>` without including an actual label in it). Here's a codepen that illustrates this: https://codepen.io/jenngiardino/pen/Bajbprj

**Comment by mcoker** [comment]
>  I don't get the larger target area or background color in Firefox in this pen

@jgiardino ah hah! I hadn't tested in Firefox and looks like that's an inconsistent implementation of pseudo elements on replaced content, and Chrome allowing them but other browsers do not.

 Another way to keep the radio/checkbox size as it is, but create a larger target area, would be to use a custom design for the checkbox, and set the element's `appearance` to `none` - that will enable the psuedo element. I updated the pen with that - https://codepen.io/mcoker/pen/XWXPRww

> Something else to consider is to focus only on checkboxes that display in tables and datalists (i.e. checkboxes that aren't accompanied by <label> elements), and wrap the checkbox with a <label>. This would allow us to control the size of the clickable area by controlling the size of the label.

👍 that would be my next suggestion, too. We have an issue open to allow either a radio/checkbox to be used on its own using the radio/checkbox component - https://github.com/patternfly/patternfly/issues/3311. Currently the component relies on the `__label` element being present (whether that is a `<label>` or some other element). That PR will enable a structure like `<label class="pf-c-[radio/check]"><input class="pf-c-[radio/check]__input></label>`

**Comment by mcarrano** [comment]
Keep open. I would like to address this.
