### ISSUE TITLE
Bug: Inline Link Button Not working as expected in components 

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/patternfly#3313]
We noticed in the Hint component, that the Inline link button is not working as expected. 

1) You should be able to put the inline link button inside of paragraph text without it wrapping to its own new line, see example below:

<img width="655" alt="Screen Shot 2020-07-09 at 2 28 59 PM" src="https://user-images.githubusercontent.com/20118816/87077089-9ab3ae00-c1f0-11ea-88eb-add59f0edf6e.png">

2) The inline link button should wrap inside of its container just like text does, this is how it appears in the Hint component:

<img width="935" alt="Screen Shot 2020-07-09 at 2 31 52 PM" src="https://user-images.githubusercontent.com/20118816/87077363-039b2600-c1f1-11ea-8537-07ceffe7af41.png">

cc: @mcoker 

Related to patternfly/patternfly#3218

**Comment by mcoker** [comment]
I tried everything I can think of and as far as I can tell, this isn't possible because of how browsers treat buttons and do not allow a `display: inline;` style. More info - https://www.scottohara.me/blog/2018/10/03/unbutton-buttons.html

From there, I also tried `display: contents;`, and while it works to simply allow the text to wrap inline, the limitations around a11y and `display: contents;` are still an issue - it removes the element from the a11y tree. You also lose all of the element's agent styling.

It seems like the best solution might be to use a `<span>` and manipulate the `role`, as suggested in the link above. WDYT  @jessiehuff?

**Comment by jessiehuff** [comment]
@mcoker After taking a look at this, trying a few things, and reading this article, I agree with you. That seems like the best solution. Scott O'Hara is also a fairly well known thought leader in the accessibility space so I feel like it's a solid source to base our approach on.
