### ISSUE TITLE
Tree view follow-ups

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#3358]
This seems like a bit of a UX problem, if you go to click on an item, you may accidentally click the action icon when you hover and it appears.

Also this icon only shows up on hover so it isn't keyboard accessible.

![Jul-31-2020 18-28-11](https://user-images.githubusercontent.com/35148959/89088097-39e54480-d35c-11ea-8e49-12644bf3c91f.gif)

We should also consider a different modifier for `__node.pf-m-active` since we reserve that class for the `:active` state. We can reuse `.pf-m-current` there if we also move that class up to the `__item`. That would mimic what we're doing in the navigation component.

**Comment by christiemolloy** [comment]
Some follow up questions:
1) Based on the designs we were trying to understand why the first item needed to be bold in the tree view? The tree view should be a flexible component that meets all use cases - and we’re not sure that every product would need the first item bolded unless thats a requirement of tree views in general?
2) For the current item, what does “current” mean? does it mean it was the last to be selected or does it mean it is controlling something else in another component ? What happens when someone clicks on checkboxes and has multiple selected, how does the current selection remain “current” ?
3) For the checkbox examples, if you click on the label does this automatically check the checkbox adjacent to it ? This is how the check component works in React.

**Comment by doruskova** [comment]
@christiemolloy Hey, thanks for these questions. I'll try to answer and maybe we can make an easier solution for it. I know that this component is more complex, so it's raising so many questions. 
1. It's bold because I wanted to highlight the chosen categories. Here's the example: https://marvelapp.com/prototype/8cdg211/screen/71733516
The main goal was to be able to easily navigate the user in a large number of items and show the path/location where they selected the item. In this case, you can select just one item and there's no checkbox, so it's easier. Maybe we can make it more clear and highlight just the leaf node with a blue color. Like this: https://marvelapp.com/prototype/8cdg211/screen/71734415
2. It means that it was the last to be selected and it shows relevant content to me. But, I think we need to differentiate two types of a tree view: 
- one without checkboxes, so you can select an item and then see relevant content somewhere on a page. 
- the second when you can select items with checkboxes. 
Because when I select an item and I use the first type of a tree view, I'm assuming that I want to see my location in a menu. When I use the second type, I'm assuming I want to take an action (e.g. apply filters). So, for this type of a tree view, we don't have to highlight the path and I'd do this https://marvelapp.com/prototype/8cdg211/screen/71734415
3. Yes, you can check the checkbox. When you can expand the item, then you have to use the "arrow" icon. 

@mcoker yeah agree that it's not ideal, but I wanted to avoid this situation: 
![84879569-ad244700-b08b-11ea-810d-fb977acba333](https://user-images.githubusercontent.com/32618096/89273885-73f66500-d640-11ea-9761-8ad9cb9d1d99.jpg)
I think we can use it without a hover (show the action all the time) and make a recommendation about the number of items. If the menu is too long and every item has an action > gets messy.

Phew, the comment is so long, haha. Hope that it's more clear and we can agree on changes in highlighted categories and selected items with checkboxes and hover actions.

**Comment by mcarrano** [comment]
Thanks for the detailed comment @doruskova . I hope this helps clarify @christiemolloy @mcoker . 

The tricky thing here is that while there are two variants of the tree, they are not really interchangeable. One is to be used more like a browser in a master-detail type view and the other would be something used more for something like faceted filtering where the user could select multiple values from a hierarchical set. Maybe this is something that would benefit from a demo to illustrate the two different cases? Would be happy to meet if this is still confusing.
