### ISSUE TITLE
Move "Page" html demos into "Navigation" component

### ISSUE THREAD

**Issue by mmenestr** [patternfly/patternfly#3447]
Move the HTML tab demos that are currently under the Page component, to be under the Navigation component, since all the examples are Navigation examples!

The ending result should be that the Page component does not have any Demo tabs, and the Navigation component now has an "HTML demo" tab.

Referring to this file: https://github.com/patternfly/patternfly/blob/master/src/patternfly/demos/Page/examples/Page.md

**Comment by mmenestr** [comment]
@mcarrano @redallen do we still want to do this or should I close this? I notice the labels say "wontfix" so I'm assuming that means I should close, but please confirm!

**Comment by mcarrano** [comment]
That label is being applied automatically by stalebot @mmenestr . We need more discussion about this. @mcoker do you have any thoughts? If we moved HTML demos, same should apply to React demos. They actually are demos of the Page component, but I can definitely see where this would be confusing to most site users, especially to designers who might be looking for examples of navigation options.

**Comment by mcoker** [comment]
I agree with @mmenestr - for the most part, I think they're really only page demos in the same way different table or data list variations are page demos.

Though they can be page demos when you're looking at something like vertical vs horizontal vs tertiary nav, because those show the page sections and layout needed to contain the nav components. 

But certainly between default nav, expandable nav, and grouped nav - the differences are purely with the nav. They don't demo anything about the page other than having the sidebar with some form of vertical nav in it.

**Comment by mcarrano** [comment]
@redallen @evwilkin wanted to bring you into this conversation. Do you agree that we should move the demos that are currently part of the page component into Navigation? We would want to do this for both core and React. I can see arguments both ways, but generally think that most consumers would look for these as part of Navigation. Thoughts?

**Comment by redallen** [comment]
Yes, I think we should move them. All we have to do is change the `id` in Core and React from `Page` to `Navigation`.

**Comment by evwilkin** [comment]
@mcarrano agreed, it makes sense to me for these to be under Navigation

**Comment by mcarrano** [comment]
OK. Let's do it then. Do we need a separate issue for React? Is this something we can do for the next release?

**Comment by redallen** [comment]
Yes, we need an issue in core and an issue in React and then we can do this next release.

**Comment by mcarrano** [comment]
Actually in looking at this more and discussing with @mmenestr , we decided this is not so simple because all of the demos on this page do not reference navigation. So in that case, I's like to see up split this into two separate sets of demos. 

For Navigaton, include:
* Default nav
* Expandable nav
* Horizontal nav
* Tertiary nav
* Grouped nav
* Light themed sidebar and nav

For Page include:
* Sticky tertiary nav
* Sticky breadcrumb
* Sticky section group
* Sticky section bottom
* Overflow scroll

I will also open a corresponding React issue. I realize this creates more work and I'm OK with putting this on the agenda for the next milestone, if needed.
