### ISSUE TITLE
Add Help button to modal header

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3474]
Want to add a Help button to the header for modals per the request here: https://github.com/patternfly/patternfly-design/issues/843

@mceledonia can you add design mocks per our earlier discussions?

**Comment by mceledonia** [comment]
For the design we landed on putting the icon in the top right beside the close, and creating a static amount of space for the close & help button.

![image](https://user-images.githubusercontent.com/30935938/93476764-24a28600-f8c8-11ea-92af-65c5f2902af8.png)

**Comment by mcoker** [comment]
@christiemolloy I think you could just add the help button and absolutely position it like the close button, which should be straight forward... but would you mind doing a quick investigation into whether there is a better way to add an actions section to the modal that can hold the close button, help modal, and other actions that isn't absolutely positioned, so that we can just add actions and not have to create static space to make room for absolutely positioned actions?

**Comment by mcoker** [comment]
@mcarrano @mceledonia modals don't have to have a header/title. Do we still support the help button in those cases? Or does the help button only apply to modals with a header/title?

**Comment by mcarrano** [comment]
Assume that you are talking about this variant @mcoker ? https://www.patternfly.org/v4/components/modal/html#without-title  In my opinion we could require that the help button only applies to modals with a title. What do you think @mceledonia ?

**Comment by mcoker** [comment]
@mcarrano yep. FWIW, the implementation is a lot easier if the button is a part of the title/header rather than an action that can be applied to any sort of modal.

**Comment by mcarrano** [comment]
I'm fine with enforcing that constraint then.
