### ISSUE TITLE
How to change favicon

### ISSUE THREAD

**Issue by QasimRRizvi** [patternfly/patternfly#3496]
I'm new with patternfly. I don't see any public folder in patternfly so I can not use ```%PUBLIB_URL%``` in ```index.hmtl``` to set favicon link.
Is there any other way to add favicon.

**Comment by mcoker** [comment]
Hi @QasimRRizvi! Since the favicon design and where it lives will be specific to your product, we don't ship favicons with PatternFly.

If you're serving your site via index.html, you could add your favicon(s) in the same directory as index.html, and add a `<link rel="icon" type="image/png" href="favicon.png">` tag in the `<head>` of index.html.

If you don't want the favorite icon in the same directory as index.html, you can add it to a directory that is in the same directory as index.html (eg, `images/icon/favicon.png`), then link to it like `<link rel="icon" type="image/png" href="images/icon/favicon.png">`.

Here is a good reference for linking to favicons - https://www.w3.org/2005/10/howto-favicon

Let me know how it goes!

**Comment by QasimRRizvi** [comment]
Hi @mcoker 
I tried both the aforementioned ways to add favicon but they don't work out.

If I add any remote address e.g ```https://abc.xyz/favicon.png``` it works but with favicon in the project directory it doesn't work
Here's the screenshot of my tree structure
![image](https://user-images.githubusercontent.com/17559205/93976029-c8d97080-fd91-11ea-9f91-99f22bab13bc.png)

And I used it in index.html in this way:
![image](https://user-images.githubusercontent.com/17559205/93976202-0f2ecf80-fd92-11ea-810c-bd36e7c07e84.png)

**Comment by QasimRRizvi** [comment]
I think this is a wrong repo (my-bad)
I should ask this question on https://github.com/patternfly/patternfly-react/issues
Closing this issue as it is related to patternfly-react.
