### ISSUE TITLE
Introduce form sections

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3557]
Want to add the ability to include expandable, nested form sections to the Form component per the designs here: https://marvelapp.com/prototype/5e57if3/screen/72963176

**Comment by mcoker** [comment]
@mcarrano a few questions about the design. Can you confirm that:

* Top level groups have 1) an underline that spans under the toggle, title, and actions, and 2) exists between the toggle/title/actions and the expanded content in the group.
* Nested groups have 1) an underline that spans under the title/actions only (doesn't go under the toggle) and 2) exists between nested groups (is not present under the toggle/title/actions when a nested group is expanded).
* The expanded content in the group should be left aligned with the left edge of the group title. The wireframes say the expanded content should be indented 32px... but the group toggle button is 48px wide (16px padding + 16px icon + 16px padding), and I've added an xs margin between the toggle and title, meaning the group title is 52px from the left edge of the group. To get the expanded contents to align with the left edge of the title, the expanded contents need to be indented by 52px.

Here is a screenshot of 32px indentation

<img width="544" alt="Screen Shot 2020-11-05 at 6 56 23 PM" src="https://user-images.githubusercontent.com/35148959/98313100-b65d7400-1f98-11eb-8275-0976ea6865fc.png">

Here's 52px

<img width="401" alt="Screen Shot 2020-11-05 at 6 56 46 PM" src="https://user-images.githubusercontent.com/35148959/98313109-ba899180-1f98-11eb-86ed-c99948197648.png">

One thing I can do is move the toggle button to the left outside of the form with a negative margin, making the icon inside align with the left edge of the container, but since the form doesn't have any built in padding, that could cause unpredictable issues if the negative margin goes outside of the bounds of the form's container. It could also look a little odd because the focus outline won't align with the content around it.

<img width="343" alt="Screen Shot 2020-11-05 at 6 58 05 PM" src="https://user-images.githubusercontent.com/35148959/98313270-148a5700-1f99-11eb-9a38-2a749a04a9ae.png">

**Comment by mcarrano** [comment]
@lboehling can you answer the questions above? Thanks.

**Comment by mcoker** [comment]
Talked to @lboehling and confirmed the borders in the design are correct, though the 32px indentation for expanded contents should just be whatever space is needed so that the left edge of the group title/description aligns with the left edge of the expanded contents.
