### ISSUE TITLE
Scrollspy component

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#3558]
Introduce a new Scrollspy navigation component per the designs here: https://marvelapp.com/prototype/25f068g6 This should include both horizontal and vertical variants.

**Comment by jessiehuff** [comment]
From an accessibility standpoint, I would just want to make sure that these jump links work for keyboard users. I would expect them to append the heading to the url similar to how we currently handle our headings (ex: https://www.patternfly.org/v4/components/about-modal#basic), and I imagine it would shift focus to that section for keyboard users.
It's worth questioning though if there would be a use case where a user would ever want to keep focus in the scrollspy container. Would a user ever want to be able to switch between these links quickly instead of shifting focus? 
For screen reader users, they already have this exact functionality in their headings menu so this would more or less just be extra for them.
