### ISSUE TITLE
Extra tertiary nav padding

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#3559]
The tertiary nav appears to have extra padding? After updating Cost Management, we noticed that the component now appears indented.

**Before**
<img width="380" alt="Screen Shot 2020-07-08 at 2 21 21 PM" src="https://user-images.githubusercontent.com/17481322/86960505-9b374080-c12d-11ea-91f7-18494ce086e8.png">

**After**
<img width="467" alt="Screen Shot 2020-07-08 at 2 21 29 PM" src="https://user-images.githubusercontent.com/17481322/86960515-9f635e00-c12d-11ea-8fb3-27ad53ca82a2.png">

**Comment by dlabrecq** [comment]
The thing is, It wasn't indented like this before updating the milestone (now back in July).

The PatternFly tertiary example below assumes the title, etc. all have the same padding.

**PatternFly example**
<img width="551" alt="Screen Shot 2020-10-05 at 11 26 24 AM" src="https://user-images.githubusercontent.com/17481322/95101353-0c23cf80-0700-11eb-9e8d-b0dc4b2af387.png">

**Cost Management**
<img width="1836" alt="Screen Shot 2020-10-05 at 11 28 04 AM" src="https://user-images.githubusercontent.com/17481322/95101269-f4e4e200-06ff-11eb-97c3-1629a59057ae.png">

**Comment by dlabrecq** [comment]
It looks like the https://patternfly-react.surge.sh/components/page/react-demos/tertiary-nav/ example has the nav in the main body, while the "Main title" is in a `section` tag, which indents items to match the nav.

**Comment by mcoker** [comment]
@dlabrecq in the major release we updated nav component spacing so there is some padding around the nav items. We also have a page section element (`.pf-c-page__main-nav`) that the tertiary nav goes in so that the nav retains proper horizontal and vertical spacing. The react page component puts the tertiary nav in that element when tertiary nav is passed as a prop to the page component: https://github.com/patternfly/patternfly-react/blob/7643fcbea54782df16cdcf587d14e26b3b91e64a/packages/react-core/src/components/Page/Page.tsx#L201-L224

Is it possible to pass the tertiary nav as a prop to the page component? I can see how that may conflict with the design with the dollar value to the right of the tertiary nav. cc @mcarrano

**Comment by dlabrecq** [comment]
Thank you for the suggestion, but we're not using the page component -- the tertiary nav is standalone. And `.pf-c-page__main-nav` only adds more padding.

<img width="414" alt="Screen Shot 2020-10-05 at 12 42 39 PM" src="https://user-images.githubusercontent.com/17481322/95129351-e4952d00-0728-11eb-9c53-2cc9b8eeb4ea.png">

That said, we did have success using your workaround. Thank you!

```
.pf-c-nav {
  margin-left: calc(var(--pf-c-nav--m-tertiary__link--PaddingLeft) * -1);
}
```

**Comment by mcoker** [comment]
@dlabrecq great! @mcarrano created a design issue to follow up and look at making the placement of the tertiary nav more flexible, so we may end up with an enhancement that lets you place the tertiary nav wherever you want without having to add custom CSS. https://github.com/patternfly/patternfly-design/issues/922

Is it OK to close this issue or would you like to leave it open?

**Comment by dlabrecq** [comment]
I'll close this one since 992 has been opened. Thanks!
