### ISSUE TITLE
Touchspin 

### ISSUE THREAD

**Issue by LHinson** [patternfly/patternfly#362]
http://www.patternfly.org/pattern-library/widgets/#bootstrap-touchspin

**Comment by matthewcarleton** [comment]
would this just be implemented in React using a input group? I don't think we'd do anything specific in core for this. @LHinson @jschuler

**Comment by LHinson** [comment]
Makes sense to me. @jschuler @dlabaj if you confirm, we can close here and open over on pf-react.

**Comment by maryshak1996** [comment]
@mcarrano @gdoyle1 
This component seems to be fairly straightforward, but I'm interested to know if you guys have any other use-cases in mind that this might not support (and any other general thoughts of course too!), before I spec it and hand it off to CSS
![screen shot 2019-03-05 at 9 54 23 am](https://user-images.githubusercontent.com/19824574/53814041-e71c1900-3f2c-11e9-85ce-f30cc163699b.png)

**Comment by gdoyle1** [comment]
@maryshak1996 This looks great! I can't think of any other use cases.

**Comment by mcarrano** [comment]
These look good to me. But in seeing these I wonder if this needs to be a distinct component or just an instance of an input group. @mcoker @mceledonia what do you think?

**Comment by mcoker** [comment]
Looks like it doesn't match the input group design in that currently if there are buttons on the ends of an input group, they have rounded borders. The non-rounded borders on elements on the ends of an input group are just "text" elements. That's how it's built in core anyways. I'm not sure if that follows the intended use with design. We can always update core to allow for non-rounded corner buttons.

There is also a thicker bottom-border on the elements at the ends of the input group in core currently.

And I wonder if the +/- buttons in this design should match what we're doing in [copy to clipboard](https://pf4.patternfly.org/components/ClipboardCopy/examples/), with the different bottom border treatment? Copy to Clipboard and this component seem similar in that regard.

**Comment by maryshak1996** [comment]
@mcoker that's a really great point -- I think that it would be worth me mocking this up with the rounded edges like buttons as well as with the styling of 'copy to clipboard'. I'll give that a go and update here early next week!

**Comment by vconzola** [comment]
As I mentioned in the PF General Slack channel and @mcarrano asked me to comment here, why is the "unit" included as part of the component? It looks out of place and I've gotten feedback saying that it adds some confusion (at least in the Bootstrap implementation we picked up for PF3) because it looks too much like a button. I'd prefer that the units just be a text label to the right of the touchspin component. I realize this might not work well for currency, but in that case can't the currency symbol just be appended to the number in the touchspin?

**Comment by maryshak1996** [comment]
Thanks for this feedback everyone - I think that I have a stronger proposal :)
@mcoker I tried styling this with the rounded corners as well as like the 'copy to clipboard' component, and I think that the button styling works a lot better in this component because we would have the flexibility to treat the '-' and '+' icons as icon-buttons and they would have those associated default, hover, disabled, etc. states. So I am in favor of using the button styling, but here are the visuals for both versions: 
![Screen Shot 2019-03-12 at 11 26 00 AM](https://user-images.githubusercontent.com/19824574/54212653-a175c800-44b9-11e9-80b4-7789eea89a5a.png)

and @vconzola I mocked up what you mentioned about having the units included in the component versus outside of it, and I think that you're spot on -- works much better outside!

So overall, here's what I'm proposing:
![Uploading Screen Shot 2019-03-12 at 11.27.23 AM.png…]()

**Comment by mcarrano** [comment]
I like this much better @maryshak1996

**Comment by vconzola** [comment]
Me too. Thanks @maryshak1996

**Comment by maryshak1996** [comment]
Here's my spec for that latest version:
![Screen Shot 2019-03-18 at 4 26 20 PM](https://user-images.githubusercontent.com/19824574/54561264-9da2e380-499a-11e9-8465-95dfdcd50d62.png)

**Comment by rachael-phillips** [comment]
Is there any more work that we'll want to do on this from a visual perspective? Or will this be good to move to CSS when the time comes?

**Comment by maryshak1996** [comment]
@rachael-phillips I don't see any more pushback on this latest design, so I think that this is visually done

**Comment by mcarrano** [comment]
I agree. This can move to CSS.

**Comment by rachael-phillips** [comment]
Great! Thanks for the update!

**Comment by maryshak1996** [comment]
@mcarrano @rachael-phillips 
I'm taking a look at something that uses this component and I'm noticing that my designs above might be a bit out-of-date since later changes to button styling have happened. Given how the input group elements and tertiary button styling looks right now, this would likely be more consistent with what's in PF4. Do you need/want me to take another look at this issue and update some things?
![Screen Shot 2019-08-20 at 5 39 33 PM](https://user-images.githubusercontent.com/19824574/63386744-c7a96900-c371-11e9-9d0f-49e31770c735.png)

**Comment by mcarrano** [comment]
I agree that this styling looks very heavy when placed in the context of an input group. @mcoker raised a similar question here: https://github.com/patternfly/patternfly-next/issues/2172. Maybe we need to take a step back and reconsider how we are implementing these controls and whether there is a better approach. Sounds like a larger conversation.

cc @kybaker

**Comment by maryshak1996** [comment]
@mcarrano ya it's tricky. What's above is more consistent with the input group styling, but is very heavy for such a small component

**Comment by mcarrano** [comment]
@maryshak1996 I've opened a new issue here to update the Input Group styling: https://github.com/patternfly/patternfly-next/issues/2175  This was primarily done in the interst of implementing a textbox filter in the toolbar, but I believe this would solve this also by removing the borders from the "-" and "+" buttons entirely. Let me know what you think.

**Comment by maryshak1996** [comment]
@mcarrano 
I see that very recently the icon button spacing has changed to be a bit tighter, and exactly matches what I had in my initial mocks, which is great! I think that if we could do a lighter grey border, that would be alright in combination with these more tightly-padded icon buttons. I tried removed ing the borders entirely as well, but it started to get a little messy when units are needed (two icons next to eachother without any barrier seemed odd) .
Here's what I have now: 
![Screen Shot 2019-08-29 at 3 17 50 PM](https://user-images.githubusercontent.com/19824574/63969598-2fe20400-ca70-11e9-8ef2-a355173e482b.png)

**Comment by mcarrano** [comment]
These look good @maryshak1996 . A couple of weeks ago we had a discussion about removing the border entirely when a "plain" button is used inside of an input group as summarized here: https://github.com/patternfly/patternfly-next/issues/2175. But I do see what you mean about adding units after the field. Since the Touchspin is a special component, I think we could special case that we we do for the Clipboard Copy to give you the styling you want. What do you think @mcoker ?

**Comment by rachael-phillips** [comment]
I'm following up here. What do you think @mcoker ?

**Comment by mcoker** [comment]
@mcarrano @maryshak1996 sorry for the late reply, that sounds fine to me.

**Comment by maryshak1996** [comment]
@mcarrano @mcoker 
Updating this to reflect the changes needed to the design as a result of https://github.com/patternfly/patternfly-next/pull/2005#issuecomment-533125231

New Design: 
![Touchspin](https://user-images.githubusercontent.com/19824574/65258097-4eb44300-dad0-11e9-90ae-a58707d14efc.png)
Sketch Cloud: https://sketch.cloud/s/romY7

**Comment by mturley** [comment]
It might be too late, but I just want to throw in my $0.02 here: I think we should rename this component to something other than "Touchspin". That name came from the name of the bootstrap library we used in PF3, and it doesn't convey very well what the component is actually for. Maybe we could call it just "Number Input" (since the native browser controls for `<input type="number" />` have the same kind of buttons).

**Comment by rachael-phillips** [comment]
@mcarrano what are your thoughts here?

**Comment by mcarrano** [comment]
I am OK to reconsider the name of this. Will want to think more about alternatives, however. @LHinson do you have any thoughts?

**Comment by andybraren** [comment]
+1 to @mturley's point - I clicked a link to this issue because I had no idea what a "touchspin" was and was curious. This does seem to replicate the functionality of `<input type="number">` so "Number input" would make sense to me, but it's probably worth researching what other systems call similar components/examples.

**Comment by maryshak1996** [comment]
I was poking around Carbon and noticed that what looks to be the equivalent of this is called Number input (https://www.carbondesignsystem.com/components/number-input/code/)

**Comment by mcarrano** [comment]
@mcoker let's consider this again. Does this need to be a new component or is it just another instance of an Input group. One way or other we should support it in the library.

**Comment by mturley** [comment]
Looking at the Carbon example @maryshak1996 posted above, they are adding some custom controls around a plain `<input type="number">` with some special CSS to hide the default step arrows. I think if we want to preserve the DOM semantics of a numeric input we should do something similar instead of expecting users to add those buttons themselves to a regular input. It looks like we also will get the benefit of being able to set min, max, and step increments as native attributes on that `<input>` instead of React logic.

**Comment by mturley** [comment]
Are we ok with renaming this issue from Touchspin to Number input? When I see it come up in my notifications I keep forgetting what it is 😆

**Comment by mcoker** [comment]
@mcarrano to support the custom design, I think this should be a component. Though we could use the input group in the component for the basic layout.

**Comment by mcarrano** [comment]
OK. I will get this on the feature roadmap.
