### ISSUE TITLE
JumpLinks: focus state mimics correct selected state and causes double highlighting

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#3747]
When the user clicks or hits tab/enter to activate the jump link, the link receives the focus state (unless the link is to a focusable element), which is currently the same as the `.pf-m-current` state (blue highlight to the left). Because the JS sets the `.pf-m-current` state to the current scroll position, it can cause two jump links to appear highlighted when the selected section is too far down on the page to scroll to the top. (see video)

After discussion with @mcoker and @redallen we agree the left blue border could be removed from the :focus state and instead match the :hover state

@mcarrano 

![focus-border](https://user-images.githubusercontent.com/19825616/101821093-7c324580-3af5-11eb-95e5-5a531a47e485.gif)

**Comment by mcoker** [comment]
To add to this, the [react jump links demo](https://patternfly-react.surge.sh/components/jump-links/react-demos/scrollspy-h2-elements/) shows the ideal behavior, where clicking on a jump link moves the browser focus to the anchored element on the page, however for that to happen, the user has to enable a `tabindex` on the anchored element (if it doesn't have one already). Since we can't always rely on the user to be able to add a `tabindex`, I think it would be a good idea to update the jump link focus style so focus can remain on a jump link, and another jump link can be updated as the "current" link without conflicting styles

**Comment by mcarrano** [comment]
@mcoker I'm having a hard time reproducing this, but I will accept your judgement and will pull this into the next milestone.

**Comment by mcoker** [comment]
@mcarrano here's a demo - https://codesandbox.io/s/autumn-smoke-tfb2p?file=/index.js

Click on a link, then scroll the page and you'll see that both the item you clicked on (because it has focus) and the section you scroll to (the "current" item) have a blue border. 

Or click on "heading 5" and notice that heading 4 has a border (because it's the "current" item scrolled in the viewport) and heading 5 has a border because it's focused from being clicked on.

We got around this in the react demo by shifting focus from the jump link you click on, to the anchor on the page that the jump link anchors to. However, we can't ensure that a product will make the element the jump link anchors to a focusable/tabable element, resulting in 2 jump links having a blue border.
