### ISSUE TITLE
Defining a <Switch> inside of <FormGroup> is not inline with FromGroup's label prop

### ISSUE THREAD

**Issue by harishsurf** [patternfly/patternfly#3755]
**Describe the issue. What is the expected and unexpected behavior?**
When  `<FormGroup label="name">` has a `<Switch>` as children, the label is slightly positioned down when compared to the inline toggle. There is also no spacing added between different children of `<FormGroup>`. See image below: 

![defaultSources](https://user-images.githubusercontent.com/39300150/100674353-011da200-3333-11eb-8577-16ff545de6f0.png)
 
**Please provide the steps to reproduce. Feel free to link CodeSandbox or another tool.**
```
<Form onSubmit={submit} isHorizontal isWidthLimited>
      <div className="modal-content modal-content--no-inner-scroll">
        <ModalTitle>Edit Default Sources</ModalTitle>
        <ModalBody>
          {operatorHub.status.sources.map((source) => {
            return (
              <FormGroup key={source.name} fieldId={source.name} label={source.name}>
                <Switch
                  id={source.name}
                  key={source.name}
                  label="Enabled"
                  labelOff="Disabled"
                  isChecked={!userSelectedDefaultSourceToggleState[source.name] ?? true}
                  onChange={(checked) => onToggle(source.name, checked)}
                />
              </FormGroup>
            );
          })}
        </ModalBody>
        <ModalSubmitFooter
          errorMessage={errorMessage}
          inProgress={false}
          submitText="Save"
          cancel={cancel}
        />
      </div>
    </Form>
```

**Is this a bug or enhancement? If this issue is a bug, is this issue blocking you or is there a work-around?**
Bug. A temporary workaround is possible (to be added).

**What is your product and what release version are you targeting?**
OpenShift console UI. Target: 4.7.

**Comment by mcoker** [comment]
Hi @harishsurf by default our form group labels are set to align the label text with the text in a form control element (TextInput, TextArea, FormSelect). However you can disable this alignment and just align the label to the top of the group via the `hasNoPaddingTop` prop on `<FormGroup>`. That variant seems to work well - here is a demo https://codesandbox.io/s/lucid-pond-co43u?file=/index.js

Also the `<Form>` component provides the spacing for `<FormGroup>` elements, but it's via CSS grid, which requires `<FormGroup>` be a direct child of `<Form>`. Is there a way you can update the code so that `<FormGroup>` is a child of `<Form>`?

It looks like maybe the reason that `<Form>` wraps the modal content currently is so that the modal submit buttons can be a part of your form. If so, one way to use a submit button outside of a form is to assign an `id` to the `<form>` element, and use that id as the value for the `form` attribute on your submit button. Here's an example of that - https://davidwalsh.name/submit-button-outside-form
