### ISSUE TITLE
Resizable drawer panel box shadow disappears when panel size is small

### ISSUE THREAD

**Issue by DaoDaoNoCode** [patternfly/patternfly#3795]
There should be a box shadow for drawer panel

<img width="829" alt="Screen Shot 2021-01-13 at 4 16 50 PM" src="https://user-images.githubusercontent.com/37624318/104511460-c017df00-55ba-11eb-8c56-d4d754e0b3f0.png">

However, when the panel size is very small (likely `flex-basis` less than 2%), the shadow will disappear.

<img width="829" alt="Screen Shot 2021-01-13 at 4 18 41 PM" src="https://user-images.githubusercontent.com/37624318/104511629-02d9b700-55bb-11eb-96c3-49fb3932c179.png">

----

Also with inline drawers, one of the splitter borders disappears when you resize the panel to 0, and the x-axis scrollbar appears.

<img width="358" alt="Screen Shot 2021-02-04 at 12 22 15 PM" src="https://user-images.githubusercontent.com/35148959/106937644-a2cec000-66e3-11eb-95d7-04b911c5aac5.png">

**Comment by mattnolting** [comment]
@mcoker @mcarrano I can't explain why the box shadow disappears, but it's resolved by setting a panel `min-width` of > 24px. Seems reasonable to me that the panel would have a min-width on resizable. If a user wants to shrink the panel to 0, they should just close the menu.

**Comment by mcoker** [comment]
@mattnolting @mcarrano it's because of the inset/negative spread on our shadows. The box needs to be bigger than the combined left/right insets for the shadows to appear. We could do away with the insets, but then the shadows extend to the edge of the container

With spread (current)

<img width="161" alt="Screen Shot 2021-05-13 at 9 50 07 AM" src="https://user-images.githubusercontent.com/35148959/118143440-f6cafe00-b3d0-11eb-932e-a5d60ec3dc03.png">

Without spread

<img width="163" alt="Screen Shot 2021-05-13 at 9 50 14 AM" src="https://user-images.githubusercontent.com/35148959/118143438-f6cafe00-b3d0-11eb-900c-51d49e9dab98.png">

**Comment by mcarrano** [comment]
I am OK with @mattnolting 's suggestion to have a minimum panel width.
