### ISSUE TITLE
Blue link color for dark mode difficult to read

### ISSUE THREAD

**Issue by katierik** [patternfly/patternfly#3855]
The blue link color for dark mode is very difficult to read, although it passes a11y contrast requirements. 
See an example here: https://marvelapp.com/prototype/5gdjb12/screen/76537421
![image](https://user-images.githubusercontent.com/23172038/107601879-e64e9000-6bf5-11eb-8015-367dad8aaef9.png)

The content on the left side is significantly more difficult to read. 
We suggest a lighter text color in order to be more readable. 

cc @mmenestr @mceledonia

**Comment by natastro** [comment]
Hi @katierik ! May I make a color suggestion or provide a resource to help?

**Comment by terezanovotna** [comment]
Agreed with @kriker

**Comment by katierik** [comment]
@natastro yes! Please do!

**Comment by mceledonia** [comment]
@katierik @terezanovotna @natastro We have been working on a dark theme effort which isn't quite ready yet but it uses a different gray background color palette so it wouldn't be too applicable here anyways. This is a good catch, that is hard on the eyes to put it lightly!

I would suggest just bumping this color up a variable in lightness, so for example if it currently is `$pf-color-blue-300` dropping it down to `$pf-color-blue-200`

@katierik Where did these dark theme colors come from? Were they directly from PF core? I ask because this might be a good opportunity to test our new new dark theme palette. CC @mcoker @mcarrano 

Another quick suggestion unrelated to the issue is making those row divider colors more subtle, they could probably be just a shade or two lighter than the background they sit on.

**Comment by mmenestr** [comment]
@mceledonia I used this text style for it which I understood to be for darker background, and it's pf-color-blue-300:
![image](https://user-images.githubusercontent.com/51165119/107649101-1b390200-6c4b-11eb-9101-76820b0467c8.png)

So yeah, I guess I can drop it to pf-color-blue-200 for now even though it's not an "official" text color haha

**Comment by mmenestr** [comment]
Here's what that looks like! Looks much better to me already: 
![image](https://user-images.githubusercontent.com/51165119/107649672-b205be80-6c4b-11eb-96ee-b931e46f6e92.png)

Does that work with you both? @katierik @terezanovotna

**Comment by mceledonia** [comment]
Yeah that was definitely the right call for what we had available. Did the background colors come defined from PatternFly as dark theme or were they adapted by y'all for this design? If they're straight from PatternFly we should look to update them.

**Comment by mceledonia** [comment]
@mmenestr Agreed, much better!

**Comment by natastro** [comment]
Hi @katierik - I like to use a site called Color Safe (http://colorsafe.co/) which outputs accessible colors based on the background color and what the text size and font family will be 😀 It also gives the hex code and a preview of what the color combo will look like. Hope this helps!

**Comment by terezanovotna** [comment]
The blue looks much better @mmenestr. Thanks for diving into it!
