### ISSUE TITLE
Demo - show table sorting on mobile

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#4019]
Need a demo to illustrate how sorting would move from table headers to the toolbar using a responsive mobile layout. Not sure if this demo belongs to Table or Toolbar.

Design: https://marvelapp.com/prototype/g894bfa

@mcoker any thoughts on where this demo belongs?

**Comment by mcoker** [comment]
@mcarrano I'm inclined to add it to the table demos, since it's a table feature. It seems similar to the bulk select and expand all demos - https://www.patternfly.org/v4/components/table/react-demos

An aside, the expand all demo in core is under the toolbar - https://www.patternfly.org/v4/components/toolbar/html-demos#toolbar-expand-all-collapsed. Seems like those should be the same. (Another aside, noticed an alignment issue in this demo, opened an issue here - https://github.com/patternfly/patternfly-react/issues/5691)
