### ISSUE TITLE
sass: / is deprecated for division

### ISSUE THREAD

**Issue by tetchel** [patternfly/patternfly#4096]
https://github.com/sass/dart-sass/releases/tag/1.33.0

https://sass-lang.com/documentation/breaking-changes/slash-div

If `sass` version 1.33.0 or newer is installed, the console is absolutely flooded by "/ is deprecated for division" errors when patternfly builds.

**Comment by redallen** [comment]
Unfortunately adding `@use "sass:math"; ... math.div` might break the following `node-sass` SASS consumers:
- 3Scale
- Foreman-Console
- Foreman-Tools
- Insights-Curiosity
- Kiali-App
- Kogito
- Konveyor-Shared-Library
- Migration-Analytics
- Migration-Toolkit-for-Containers
- OpenShift-Admin-Console (will break for sure)
- Operatorhub
- Quay
- RHEL-Composer
- Red-Hat-Developers
- Settings-Catalog
- Settings-RBAC

For this reason we've opted not to replace `node-sass` with `dart-sass` but instead find a clever workaround for the division operator.

We want to support `dart-sass` whenever our next breaking change release is. In the meantime we encourage consumers to adopt the [`sass`](https://www.npmjs.com/package/sass) package instead of [`node-sass`](https://www.npmjs.com/package/node-sass) using the [migrator tool.](https://github.com/sass/migrator#readme)

**Comment by nex3** [comment]
Sass team lead here! I wanted to pop in and say, first of all, that we're very sorry for the friction here. We really wanted this transition to be smoother: we actually accepted the proposal for the /-as-division deprecation [two years ago](https://github.com/sass/sass/pull/2704), and [filed a P1 issue with LibSass to support it](https://github.com/sass/libsass/issues/2887) around the same time. We held off landing it in Dart Sass for so long because of how much easier warning-free support for both Dart Sass and LibSass would have been if it were possible to support both platforms.

Unfortunately, the LibSass team (which works basically independently of the rest of the Sass team) has been steadily losing bandwidth over the past five years, and they just don't have the ability to add new features anymore. This is why we eventually [declared LibSass deprecated](https://sass-lang.com/blog/libsass-is-deprecated) and, six months afterwards, started the process of releasing the /-as-division deprecation in LibSass.

I think you're on the right track by encouraging your users to migrate to Dart Sass ASAP. It's likely that staying on LibSass will continue to produce more and more pain, between incompatibilities with changes to the Sass language on one hand and lack of support for new CSS features on the other. But I also understand not wanting to break your existing users if you can help it. To that end, here's a workaround you can use to continue supporting both Dart Sass and LibSass for the time being while also silencing these warnings:

```scss
// _div.import.scss
@use "sass:math";

@function div($number1, $number2) {
  @return math.div($number1, $number2);
}
```

```scss
// _div.scss
@function div($number1, $number2) {
  @return $number1/$number2;
}
```

If you include both these files in your library, you can write `@import "div"` and get a `div()` function that will work on LibSass and avoid producing errors on Dart Sass. It relies on the fact that Dart Sass supports the new module system and LibSass does not, so Dart Sass will prefer files with the extension `.import.scss`. If you want to support older versions of Dart Sass as well, you could also dynamically check whether `math.div` is defined:

```scss
// _div.import.scss
@use "sass:map";
@use "sass:math";
@use "sass:meta";

$-use-math-div: map.has-key(meta.module-functions("math"), "div");

@function div($number1, $number2) {
  @return if($-use-math-div, math.div($number1, $number2), $number1/$number2);
}
```

I wouldn't recommend either of these as long-term solutions, but they can at least get you unpinned from earlier Dart Sass versions until we land support for the [silencing dependency warnings in JS](https://github.com/sass/sass/issues/3065).
