### ISSUE TITLE
Table: Missing padding when no rows expandable

### ISSUE THREAD

**Issue by KevinFCormier** [patternfly/patternfly#4114]
If you have a table that is set up to be expandable, by providing the `onCollapse` function, but there are no expandable rows currently in the table (or in the current page of the table) then the padding on the left is reduced compared to the default.

For example:
https://codesandbox.io/s/brave-bash-y1rh0?file=/index.js

![image](https://user-images.githubusercontent.com/42188127/120233628-45c3c080-c224-11eb-92f2-521977b272be.png)

Compared to a simple table:
![image](https://user-images.githubusercontent.com/42188127/120233676-5e33db00-c224-11eb-9943-2769502289f8.png)

It looks to have about half as much padding.

**Comment by KevinFCormier** [comment]
@mcarrano @mcoker This is another styling issue we've observed with expandable tables.

**Comment by mcoker** [comment]
cc @tlabaj `onCollapse` is creating an empty `<td>` at the beginning of each row, and we remove the padding from empty cells. From the prop description

> When this is used, one expandable toggle button will be positioned in the first cell of a non-expandable row, preceding an expandable row.

The cell is being created, but not a button. If we can also remove the cell if we don't create a button, that will fix the table padding.

**Comment by nicolethoen** [comment]
@KevinFCormier 
As you noted above, when you pass an `onCollapse` function to the `Table`, the table adjusts by explicitly adding a column to the beginning of every row in case the row is expandable and will need an expand/collapse toggle. The table does not monitor how many expandable rows it contains, so it remains primed to contain expandable rows because of the existence of the `onCollapse` function.

I don't know your exact use case, but is it possible to conditionally pass the  `onCollapse` prop only when there are expandable rows?

**Comment by KevinFCormier** [comment]
Hey @nicolethoen. Thank you! I think that should be possible. I'll give it a try and if it works out I guess we can just close this issue.

**Comment by KevinFCormier** [comment]
Yep, that worked perfectly. Thanks again @nicolethoen!
