### ISSUE TITLE
Fix(context selector, dropdown): move ::before border to ::after

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#4155]

**Comment by rhamilto** [comment]
It looks like changes here resulted in a regression in OpenShift as the perspective switcher did *not* have the bottom border prior.

https://user-images.githubusercontent.com/895728/124989965-bfae4d00-e00d-11eb-8034-b24452ddfacd.mov

**Comment by rhamilto** [comment]
^ @mcoker

**Comment by mcoker** [comment]
Thanks for reporting that @rhamilto, looking into it.

**Comment by mcoker** [comment]
@rhamilto thanks for flagging this. We moved the bottom border from `::before` to `::after` so the border looks a little better, and it looks like there is an override to that dropdown toggle in [_nav-header.scss](https://github.com/openshift/console/blob/cb618e6ac594ed3b45da3a63d438e56bda6533d7/frontend/public/components/nav/_nav-header.scss#L52-L54) that removes the border for that toggle by setting `::before { border: none; }`.

Since you've reported this, and I'm sure others will run into an issue as well, we'll roll back that change considering the change isn't necessary and how widely used the dropdown component is.

Between releases we sometimes change the CSS selectors and properties, while preserving the role of the component variable roles. Instead of styling the dropdown elements directly, another option to remove this border would be to set the following variable overrides:

```
.oc-nav-header .pf-c-dropdown {
  --pf-c-dropdown__toggle--before--BorderWidth: 0;
  --pf-c-dropdown__toggle--focus--before--BorderBottomWidth: 0;
  --pf-c-dropdown--m-expanded__toggle--before--BorderBottomWidth: 0;
}
```

Also I would like to introduce a [plain text variant to the dropdown](https://github.com/patternfly/patternfly/issues/4212) for this use case, similar to the one in the [options menu](https://www.patternfly.org/v4/components/options-menu#plain-with-text), that you could use and be able to remove that override.

Another option could be to use the plain text context selector variant, which was just added in core and we have an open [issue for the react enhancement](https://github.com/patternfly/patternfly-react/issues/5932).

**Comment by rhamilto** [comment]
> Since you've reported this, and I'm sure others will run into an issue as well, we'll roll back that change considering the change isn't necessary and how widely used the dropdown component is.

Thanks.  This is a breaking change and it should be reverted.  

I would like to see greater scrutiny on the changes made in PatternFly.  We have become wary of upgrading PatternFly in OpenShift because it seems like every time we do, we find breaking changes.  We need stability from the API so we can upgrade with absolute confidence.  cc:  @spadgett, @christianvogt, @jwforres
