### ISSUE TITLE
Allow Icon on DescriptionListTerm

### ISSUE THREAD

**Issue by ianw** [patternfly/patternfly#4353]
I think it would be great if you could do `<DescriptionListTerm icon={<AnIcon />}>...` in the same way you can do `<ListItem icon={<AnIcon />}>` and have it format correctly.  It feels like they have similar use-cases where some visual indicator of the term can be helpful for quick identification.

![Screenshot_2021-08-16_15-40-22](https://user-images.githubusercontent.com/108448/129516283-d6bb9946-0e42-418b-a8fc-3af5f09ca260.png)

That is an example where I've just put an icon in a span next to the `DescriptionListTerm`.  It's OK, but something feels not quite right and I'm not sure what; which is why it would be nice if PF did this automatically :)

Thanks!

**Comment by mcarrano** [comment]
We will get this on our roadmap. Right now I am scheduling into Q1 of 2022.

**Comment by srambach** [comment]
@mcarrano @mceledonia @mmenestr A few clarifying questions:
1. Should the text wrap under the icon (as shown above), or should the icon be to the left as a list bullet would be?
2. What spacing would you like between icon and text?
3. If some definitions don't have an icon, does the text line up with the other text, or with the icon?

**Comment by mcarrano** [comment]
@srambach As much as possible, I think we should handle this in the same way as we do for a List component with icons. Use the same spacing and wrapping behavior. Does that make sense? Maybe create an example and we can all look at it together. @mceledonia do you have any other thoughts?

**Comment by srambach** [comment]
I've put in some icons, and here are examples with the default format, 2 column, and horizontal. I didn't indent the definition and didn't indent the term if there is no icon. This is the minimal implementation and doesn't require the list to be marked as "has icons," which would likely be needed otherwise. Let me know what you'd like to do.
@mcarrano @mmenestr @mceledonia 

![image](https://user-images.githubusercontent.com/19825616/148836405-70c3754d-464d-46fa-aa1a-754f09b05f43.png)

![image](https://user-images.githubusercontent.com/19825616/148836437-df3cbf51-9e06-48e7-a433-d6db5b4733c8.png)

![image](https://user-images.githubusercontent.com/19825616/148836459-028b93fc-0f37-4a80-a126-029870f57970.png)

**Comment by mcarrano** [comment]
@srambach I am OK with this approach. 

@mceledonia @mmenestr what do you think?

**Comment by mmenestr** [comment]
I almost like having it wrapped under the icon better, instead of indented with the top text, (like we see in the first image at the top of the issue), just because it ends up looking misaligned otherwise. But I'll let Michael weigh in, either way is fine with me!

**Comment by mceledonia** [comment]
Yeah it is tough to choose one without a usage context. Here are my thoughts:

**Icon indented** - This gives a nice emphasis to the icon and makes it easier to find at a glance. I could see this being useful for finding information in a longer or more dense list.

**Icon wrapped** - This keeps the left column nice and straight like @mmenestr mentioned, which could work better for more sparse lists or when column width needs to be conserved. 

I think if I had to choose one it would be the indented, just because if the user wants an icon in the first place then chances are they will want it to be more identifiable and prominent.

**Comment by srambach** [comment]
Here it is inline at the smallest, but indented above the small breakpoint. Is that the preference?

https://user-images.githubusercontent.com/19825616/149006235-33163ec2-f9d4-46dd-93f5-314402f040d0.mp4

https://user-images.githubusercontent.com/19825616/149006276-61db7309-9691-429e-9a26-c407d7aa27ef.mp4

**Comment by srambach** [comment]
Since list has a large icon option, I tried it, but I'm not sure if you actually want that. What do you think @mcarrano @mmenestr @mceledonia ?

![image](https://user-images.githubusercontent.com/19825616/149025869-ea9aa1e2-5ded-46cb-a191-89bd7c598f9d.png)

**Comment by mcarrano** [comment]
I don't think this is something we'd want for description list IMO.
