### ISSUE TITLE
Improve accessibility of form help buttons in examples/demos

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#4453]
Currently all the demos and examples of a field level help button are read as "More info." A user navigating form controls could get many items that are just "more info" so it would be nice to show how to include the label so that it says something like "more info for name."

@jessiehuff @nicolethoen @jgiardino WDYT?

**Comment by jgiardino** [comment]
I think I usually say something like "help" combined with the field label. So if the field label is "Cloud provider" it would get announced as "Cloud provider help". But I'm not really sure if that's the best way to describe the button either. Some of my questions on this have been:
- Is "help" the right label to use? 
- Should we lead with "help" or end with "help"? 
- Should there be some punctuation somewhere in between?

Adding @abigaeljamie to weigh in on this from a content perspective.

The one thing I know is a criteria that might be somewhat helpful is that whenever we have an accessible label accompany a visible label, that the visible text should be announced first. That isn't really the case with the popover icon (i.e. there is no visible text), but even so, that could be a reason to consider using that pattern so that we have consistent structure when used for an icon or text. For example:

- If a (?) icon displayed next to a form input label "Cloud provider", then the accessible label could be "More information for cloud provider"
- If a [More information](#) link displayed in a card with a title "Cloud provider", then the accessible label could also be "More information for cloud provider"

**Comment by abigaeljamie** [comment]
I love your suggestions, @jgiardino ! Including the field label followed by "help" sounds like a good pattern (and I wouldn't add any punctuation). 

However, I understand wanting to align with the visible text pattern for consistency across the board, even though there's no visible text here. So in that case, "More information for {{field label name}}" makes sense to me, or we can shorten it to "Information for {{field label name}}." 

If we were to break from that pattern, we could try something like "{{field label name}} information," similar to the "help" pattern. Example: "Cloud provider information" 

I don't have a strong preference on any option — I'm curious to hear opinions on which ones might be the most accessible :)

**Comment by srambach** [comment]
Still valid. 
https://www.patternfly.org/v4/components/form/html-demos

**Comment by mcarrano** [comment]
@mcoker are you OK with adding this to the core backlog?

**Comment by mcoker** [comment]
@mcarrano yes
