### ISSUE TITLE
Dual List Selector "selected" count is confusing when returning to one with saved selections.

### ISSUE THREAD

**Issue by arburka** [patternfly/patternfly#4505]
The term "selected" in the Dual List Selector feels overloaded in this context. 

The Dual List Selector displays what is currently selected relative to the total shown in either the left or right side list. The counts are independent of one another and are reasonably clear when starting with nothing on either side.

The contents of the right-side list can also be considered "selected" as they have been moved from Available to Chosen. This issue causes the most confusion when one returns to the picklist with previously added items visible in the Chosen list. 

Suggested Update:
When nothing is selected, the lists show how many total items there are:
![image](https://user-images.githubusercontent.com/88330245/141139482-96418c43-f8a4-4163-8e44-d98893eaff07.png)

When something is selected, the count updates to show how many are selected:
 ![image](https://user-images.githubusercontent.com/88330245/141139663-d82ee8e2-93be-4df8-8bbd-dbbd3e3693a7.png)

Please, let me know if I can do anything to help.
Thanks

**Comment by nicolethoen** [comment]
Hi @arburka!

On the React side, we do have two ways which would allow for the user to have more fine tuned control over the status of the pane.

The first way is to use the `DualListSelector`'s `chosenOptionsStatus` and `availableOptionsStatus` props.[ I have wired up a code pen to demonstrate doing this](https://codesandbox.io/s/exciting-firefly-hv6f0?file=/index.js) while also using the `DualListSelector`'s `onOptionSelect` prop to update the statuses like you have described. Note - it does require a bit of additional logic to keep track of the number of selected items, because by default that is something completely managed inside the dynamically built component. But this is still the most basic way to implement this if you enjoy the rest of the Dual List Selector's features right out of the box.

The second way gives the product much finer tuned control over the whole Dual List Selector and is the best way to build a Dual List Selector in a more customizable way. Most feature enhancements which will be requested of the Dual List Selector outside of its basic use cases will be implemented composably. [Here is a link to the Composable Dual List Selector documentation](https://www.patternfly.org/v4/components/dual-list-selector/#composable-dual-list-selector) if you'd like to play with that. I'm happy to answer any of your questions.

**Comment by arburka** [comment]
Hello @nicolethoen!

Thanks for the feedback/solution. We will implement the solution you suggested.  

Is there a process for vetting a change like this for the component itself? 

adding @mmenestr for her visibility/input

**Comment by nicolethoen** [comment]
@arburka
Opening an issue - as you have done - is the best way to get a conversation going.

As far as we are able - we have been trying to ship our components with as little fixed, built in functionality as we can, because then we get issues like this which asks us to iterate on the scenario and further complicate the component - which complicates further enhancements and long term maintenance. So building composable components, which give the consumer the maximum flexibility tends to be the approach we've been leaning into.

The dual list selector is a complicated enough solution, that we have built a fully functional, dynamically built base case solution. However, as products want to stretch it outside its base case, it will likely become more and more appealing to move toward the composable/flexible solution. But it's all an ongoing conversation.

**Comment by arburka** [comment]
Following up here. @nicolethoen We created a Composable Dual List Selector that addressed our needs.

@mmenestr and I think it might be helpful to share it ando see if any of the customizations is valuable to any other PF users. What might be the best forum for that?

**Comment by mmenestr** [comment]
@arburka the PF design share next Wednesday would probably be a good place to start! Are you able to attend/present?

**Comment by arburka** [comment]
I can do that @mmenestr.

I'll add myself to the list.
