### ISSUE TITLE
Update date picker to improve handling of typed or pasted text

### ISSUE THREAD

**Issue by jeperry** [patternfly/patternfly#4507]
https://www.patternfly.org/v4/components/date-picker

Currently if users enter a date manually they need to type the hyphens, otherwise an error is displayed. This is a request to not require users to type or paste dates with hypens (or whatever delimiter is required) so that dates are easier to manually enter. e.g. user can type only the numbers `20210311` and the control will display as `2021-03-11`

![image](https://user-images.githubusercontent.com/2206023/141139981-8c28b8aa-a4e2-4e39-8ee2-87bcf9e91a18.png)

Additional details:
- The control should allow typing or pasting data formatted with a different common delimiter like `/` or spaces and have that 'just work.' E.g. Paste `2021/11/10` and display in the standard way  `2021-11-10`
- The control should ignore invalid characters (non-numbers)

**Comment by mturley** [comment]
Implementation thoughts: if this convert/sanitize operation runs on every keystroke, we should make sure it doesn't block the user from backspacing the text (e.g. they delete a "-" character and it puts it back, so they can't delete the whole field without selecting it all first). Learning from a similar experience :)

**Comment by mturley** [comment]
Also @jeperry I think maybe this should be in the patternfly-react repo? If the consumer is using the HTML version this will be up to their app code to implement, but if they are using React we can do it for them.

**Comment by nicolethoen** [comment]
Hi @jeperry 
We have built the DatePicker to do some basic parsing of date strings by default, however we have exposed the functions for parsing dates on the React side so that I believe a product should be able to override it however they see fit.

This is important because some systems will be handing in date+time stamps that are pure millisecond values, while others might expect user input to be copy pasted from a source that has already formatted the input to be in an American format,[ as in this example](https://www.patternfly.org/v4/components/date-picker#american-format)

Here is [a code sandbox](https://codesandbox.io/s/headless-frost-7jb1c?file=/index.js) I quickly built that demonstrates some of how it might be possible

**Comment by nicolethoen** [comment]
Hi @jeperry, I'm not sure if you've had a chance to look at my code sandbox above.
I _think_ this reported issue should already have a solution.
Let me know what you think.
