### ISSUE TITLE
page: demo: the icon group in the toolbar in the masthead top is not clear when focused / selected

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#4524]
I am following https://www.patternfly.org/v4/components/page/react-demos/sticky-section-group/ for adapting cockpit's top panel to PF4.

I think when the background is dark, like here, we need some classes which will outline / highlight the elements which are focused/active. 
In this example, the icons on the top, when focused, have almost no difference for the user.

**Comment by mcoker** [comment]
cc @mcarrano wdyt? The attention bell should probably be a notification badge, assuming it should toggle a notification drawer.

**Comment by mcarrano** [comment]
Yes, that's true @mcoker . I checked some of the other React demos and looks like they all have the same problem except for the Notification drawer demo that uses the correct badge. I don't see this in the core demos though. I'm wondering if we should just remove the notification icon from all demos except for the ones directly related to Notification drawer. Thoughts?

But I'm not really sure that addresses the issue that @KKoukiou raises. It's true that the focus/hover effect for these icons is very subtle and hard to notice. But it's been that way since we introduced PF4. @mceledonia any thoughts?

**Comment by mceledonia** [comment]
Yeah we need some focus states here and I would argue the active state is the drawer/menu itself, but not opposed to keeping the hover styling while active. 

For focus states, is there a reason we aren't applying our usual focus states on these icons?
