### ISSUE TITLE
add icon only variant for Progress button

### ISSUE THREAD

**Issue by jgiardino** [patternfly/patternfly#4561]
We have a refresh button in a toolbar that we would like to replace with a spinner while we're fetching the latest data. I included some screencaps below of our storybook component. 

We were able to implement this using what's available today, but the current react component isn't really optimized for this icon-only implementation where we remove the icon when the spinner displays. This implementation results in some shifting (i.e. the dimensions of the button change, and the spinner isn't centered with the original position of the icon).

Because of this, we are limited in where we can use this button. Originally when we right-aligned these elements in a toolbar, we noticed some jumping in the UI when clicking on the button. We're able to avoid this in our current implementation, but thought this might be a common pattern that would be good to support. It would also be good to address this issue so that we have more flexibility in where we place this type of button. 

![image](https://user-images.githubusercontent.com/21063328/145442990-22b6931d-ade4-4234-8dcf-f862e5d2c013.png)

![image](https://user-images.githubusercontent.com/21063328/145443191-f405e715-82ac-4b9c-8189-d5b078ea900c.png)
![image](https://user-images.githubusercontent.com/21063328/145443234-b9f1ea2e-ae29-40b3-8f96-ba65cf744828.png)

**Comment by mcoker** [comment]
Hey @jgiardino! One idea would be to attach an animation to the existing icon, which would also work well here. I created a codepen - https://codepen.io/mcoker/pen/VwMbxbX

Although if you are able to retain the button and just want to replace the icon with the spinner, you can do that by setting a custom diameter of the spinner icon to inherit the font-size, since the preset spinner diameters are based on global icon font-sizes (not text font-sizes). You can do that by setting `--pf-c-spinner--diameter: 1em;` or `--pf-c-spinner--diameter: var(--pf-global--FontSize--md);` (or whatever size you're using). Here's a codepen - https://codepen.io/mcoker/pen/ZEXKoVe

Do either of those options work?

**Comment by mcoker** [comment]
@jgiardino yep! Just set `--pf-c-spinner--Color` to whatever you want it to be. Updated this codepen with an example -  https://codepen.io/mcoker/pen/ZEXKoVe
