### ISSUE TITLE
List component does not support HTML5 `start` attribute

### ISSUE THREAD

**Issue by starpit** [patternfly/patternfly#4562]
`<ol>` in HTML5 may have a [`start` attribute](https://www.w3schools.com/tags/att_ol_start.asp)

However, the PatternFly List component does not seem to support this. As a result discontiguous source elements can not be rendered into a sequentially numbered PatternFly List.

**Comment by mcoker** [comment]
Hey @starpit you should just be able to pass the attribute inline with the component like this - https://codesandbox.io/s/festive-cloud-i7eb2

**Comment by starpit** [comment]
Wow, nice! Maybe we could add it to the [docs](https://www.patternfly.org/v4/components/list#list)? I notice that the List docs specify the `type` HTML5 attribute, but are missing `start` and `reversed`.

**Comment by mcoker** [comment]
Typically we only document attributes that the component has specific support for - in the case of `type`, it's because its value should be one of the values in the `orderType` enum that maps different names to the various HTML values for the `type` attribute - https://github.com/patternfly/patternfly-react/blob/3ed7b56d09464d825db5e8e9af2d3b9a3a841f7a/packages/react-core/src/components/List/List.tsx#L5-L11

In the case of `start` and `reversed`, those are just regular HTML attributes, and most (or all?) regular attributes can be passed inline with the component as in the example above.

Though if you'd still like to see it in the docs, or maybe the component have its own method of support for those attributes, we can transfer the issue to the [patternfly-react repo](https://github.com/patternfly/patternfly-react/) for more consideration.
