### ISSUE TITLE
Options menu - entire plain text toggle should be clickable

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4629]
@mmenestr @mcarrano currently only the arrow is clickable in a plain/text options menu. A good example of that variation in use is in pagination - https://www.patternfly.org/v4/components/pagination

Do you know if there is a reason we created it that way? Seems like the whole thing would be clickable like our other plain/text toggles. Also matches the vertical/expandable additions we made to tabs and jump links recently.

**Comment by mcarrano** [comment]
If I recall correctly, we did this for Paginiation because unlike standard dropdowns, the text in the toggle changes as a result of selecting a new items per page but items per page is not reflected directly in the toggle. Not sure if that's a good reason, but this is what I recall. Does that make sense? Agree it seems a bit odd taken out of context.

**Comment by mmenestr** [comment]
Yeah, I would assume it's because of what Matt said. The page numbers don't match up with the dropdown options that are shown. (ie: the toggle doesn't say what the menu options say) so to me, it kind of makes sense that in this case only the arrow would be clickable.

**Comment by mcoker** [comment]
>  (ie: the toggle doesn't say what the menu options say)

I thought that was the general idea of the options menu, and how it's different from the select component. Both maintain a selection state, but while the select component's toggle always represents the current selection, the options menu doesn't - though I think I've usually seen it used with some sort of static text in the toggle (like a dropdown).
