### ISSUE TITLE
Sticky column has higher z-index than select

### ISSUE THREAD

**Issue by rvsia** [patternfly/patternfly#4646]
We are using table sticky column with a table filter, but sticky table has higher z-index than the select, so the select is hidden behind the first columns:

![Screenshot 2022-01-28 at 15 44 42](https://user-images.githubusercontent.com/32869456/151567808-5662df2c-7696-40e9-bf83-d568badfee9a.png)

`pf-c-dropdown__menu`  `var(--pf-c-dropdown__menu--ZIndex);` `200` (same applies for `pf-c-select__menu`)
`pf-c-table__sticky-column` `var(--pf-c-table__sticky-column--ZIndex);` `300`

**How it should look**

![Screenshot 2022-01-28 at 15 53 30](https://user-images.githubusercontent.com/32869456/151568489-ea20bdd0-4c97-4fc3-80c3-a4d149687b5f.png)

**Comment by rvsia** [comment]
The same issue applies for table actions dropdown

![image](https://user-images.githubusercontent.com/32869456/153183645-8312e5a3-b2af-4749-b2f9-907946d6ab52.png)

**Comment by mcoker** [comment]
@rvsia the reason for that is because we don't want elements that will scroll behind a sticky column/header to pop out on top of the sticky column/header. We're trying to avoid something like this:

https://user-images.githubusercontent.com/35148959/153511237-7628814b-eb32-4b25-bb12-777eb9f9f8a0.mp4

I believe in these cases if you know you want the menu to appear on top of the elements around it, you can use the `menuAppendTo` prop to append the element to the `<body>` element.

Another way to do it could be to assign a higher `z-index` to those particular elements, or a lower `z-index` to the element adjacent to the menu that you want the menu to appear on top of, creating a stacking context. For example, using a `z-index` that is lower than the dropdown menu (eg, `z-index: 199`) on the entire table that you want the dropdown in the toolbar to appear on top of will create a stacking context for the table, and preserve any existing `z-index`es in the table.

Will one of those solutions work?

**Comment by mcoker** [comment]
@rvsia Thanks, great suggestions! We'll be working on this next sprint so hopefully we can improve on what's there currently.
