### ISSUE TITLE
Custom style for TextInputGroup within a MenuToggle

### ISSUE THREAD

**Issue by jeffpuzzo** [patternfly/patternfly#4666]
**Objective:** Leverage Menu's components to achieve a similar visual representation of a typeahead select.

**Issue Description:**
Using a TextInput inside of a MenuToggle leads to excess padding and a border that is undesired around that input. 

**Possible Solution:**
Create a custom style/class for a borderless input specifically for use inside of a MenuToggle that has negative margins to offset the padding MenuToggle already has.

Once completed the following can be worked on:
https://github.com/patternfly/patternfly-react/issues/6888

**Comment by nicolethoen** [comment]
@jeffpuzzo does the text input group need to go inside a menu toggle? Could you just append a menu to a text input group?

One of the reasons I ask is because I believe a menu toggle is a button - and you cannot have buttons inside buttons, so the controls of the text input group would not be valid inside a menu toggle as it is currently defined.
