### ISSUE TITLE
Tree view: Checkbox variant has misleading hover state

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#4725]
The checkbox variant works differently than other Tree view variants because for all the others, clicking anywhere in the row expands or collapses the children. If the row is displaying a hover state, and you click, the row will toggle.

For checkbox variants, if you click on the expand/collapse button, the row toggles. If you click on the checkbox OR the text, the checkbox is selected. If you click on the space to the right of the text, nothing will happen. Nothing happens BUT the hover styles are still there (along with a pointer cursor) making the user think that something will happen if they click... 

I believe in this case, the row should expand/collapse if the user is clicking in the empty space beside the text - like it would for the non-checkbox variants.

![Mar-01-2022 15-53-48](https://user-images.githubusercontent.com/26305082/156247238-e06e7345-bfd8-4c70-bda7-0d69aa36e875.gif)

**Comment by mcoker** [comment]
With this issue and https://github.com/patternfly/patternfly/issues/4724, we decided to update tree view nodes so that on any row that is selectable and has a toggle (checkbox or the "tree navigation" from #4724), only the toggle arrow and anything to the left of it should be clickable to expand the row, and anything to the right (except for actions) should select the row. Also as part of this update, we should update the toggle icon to be color-200 by default and color-100 when hovered/focused/expanded. Use a plain button there if that makes sense.
