### ISSUE TITLE
Wrong font for titles used in Card components 

### ISSUE THREAD

**Issue by doruskova** [patternfly/patternfly#4737]
@mcarrano @mcoker Our CCX team noticed that our Advisor card is using Red Hat Display font for titles. The OCM is using Red Hat Text font for other cards such as "Telemetry, CPU and Memory Utilization" which is not correct for titles. It causes inconsistency in a UI and it's not visually ok. However, the issue is that these cards with the wrong titles are using card components and this component is using Red Hat Text for the header. On the typography page, we say that RHD is used for titles and RHT for body text. It leads to confusion between designer and developer. What is the meaning behind the header with RHT and not RHD here? 

<img width="1319" alt="Snímek obrazovky 2022-03-16 v 16 08 30" src="https://user-images.githubusercontent.com/32618096/159266483-4719e46f-fbb4-448c-8173-bb6adc57078d.png">
 
![Snímek obrazovky 2022-03-21 v 13 55 41](https://user-images.githubusercontent.com/32618096/159266846-22e9f54f-e100-458b-9339-26d813013789.png)

cc @gkarat @fewwy

**Comment by mcarrano** [comment]
@doruskova we discussed this today during our issue triage. We did intentionally deviate from that guidance in our Card examples. Can you sync with @mcoker on this to figure out what is the best solution.

**Comment by mcoker** [comment]
Hey @doruskova, apologies for the delay. Traditionally we only use RHD in either the title component, or when using [headings in the text component](https://www.patternfly.org/v4/components/text#headings), which is very similar to the title component. Pretty much everywhere else we have a "title" built into a component, we use RHT.<sup>*</sup>

Without seeing the code, my guess about the inconsistency with card titles on this dashboard is that some cards are using the default card title built into the card component (which will use RHT), and the ones using RHD are using the title component to create the card title. If you have a link I can view or way to reproduce it in the browser, I'm happy to look and tell you exactly what the difference is.

<sup>*</sup> Exceptions:
* Modal - traditionally, the title in the modal was using the title component, but we wanted more CSS control over the presentation of that title in the modal component, so we stopped using the title component and use a regular element built into the modal now. Because the title is really large and it traditionally used RHD, it still uses RHD.
* Popover - the default title in the popover uses the title component, as that's how the component was originally built. However, we enabled the ability for a user to specify their own title without using the title component, and when that happens, we set the font family to RHD for consistency. The popover is built very similarly to the modal (like a little modal).
* Accordion (large/display variation) - I'm assuming this uses RHD because it is for web/marketing purposes - RHD was specified in the design.

**Comment by doruskova** [comment]
@mcoker Thank you for your answer. :)  Here's the link https://console.redhat.com/openshift/overview 
There should be an Advisor recommendations card (let me know if you don't see it from your account) that is using RHD and other cards are using RHT because as you mentioned, the OCM team used the default PF card with RHT.

**Comment by mcoker** [comment]
Hey @doruskova sorry (again!) - this fell off my radar. I went to the page and don't see it on the overview dashboard, but I poked around a bit and found it on the cluster details overview panel:

<img width="2033" alt="Screen Shot 2022-05-16 at 5 29 28 PM" src="https://user-images.githubusercontent.com/35148959/168693133-5aa4a589-a22d-4336-82ea-d7ecb759b38a.png">

On this page, all of the cards are using the `<Title>` component instead of the card title element, so they're all using the same font family, however the advisor recommendations title is using a different size title, so the font size is different than the other cards. "advisor recommendations" uses a "large" title, and the other cards use an "XL" title, but the font-size is manually overridden to be the medium/default font-size.

<img width="2033" alt="Screen Shot 2022-05-16 at 5 29 18 PM" src="https://user-images.githubusercontent.com/35148959/168693257-aba859df-1591-4c25-a389-ac65059bcb65.png">

For what it's worth, cards in the developer sandbox have a completely different layout. They use our `<Text>` component to define a title that's sized based on the heading level, with manual spacing between that title and the content below. I don't know if that's intended or not, but if we wanted those cards to be more inline with regular cards, we have a [horizontal split card demo](https://www.patternfly.org/v4/components/card/react-demos#horizontal-split) that achieves that same basic layout

<img width="2033" alt="Screen Shot 2022-05-16 at 5 30 48 PM" src="https://user-images.githubusercontent.com/35148959/168693430-352613ec-bf99-4a18-ac75-34830175ed12.png">
 
So the reason the titles are different is some cards use the card's built in title (RHT), and others use the `<Title>` component or `<Text>` component to define the title, which use RHD. I'd be happy to help come up with a solution, though I think the best solution depends on why those are like that in the first place and if there are any sort of requirements or limitations for the styling or elements used that we would need to work within.

**Comment by doruskova** [comment]
@mcoker Thank you! 
@gkarat FYI

**Comment by gkarat** [comment]
@mcoker, @doruskova, thank you. There are no special requirements or limitations for the elements' styling in OpenShift Cluster Manager (OCM, the app you were browsing). However, the confusion is in the behavior of the `<CardTitle>` component: as a developer, I expect the enclosed text will have RHD font assigned. However, it keeps RHT. 

I tried to take a look again at docs: https://www.patternfly.org/v4/components/card, and found this: in the "Examples" section, all cards have RHT, whereas the examples in the `React demos` tab have RHD. This is because the examples from the demo additionally encapsulate text in the `<Title>` component which applies RHD font to its contents.

So my proposal is actually to make `CardTitle` apply RHD to its contents too. For now moment, we will rework the problematic cards found in OCM and wrap their titles with `Title`s unless there is any reason to keep RHT. @doruskova

**Comment by doruskova** [comment]
@gkarat I agree with you.

**Comment by mcarrano** [comment]
@mcoker I don't feel strongly about this and could go either way. @mceledonia what do you think?

**Comment by mceledonia** [comment]
> There is no requirement that the card title has to be a section heading.

I think this is where I'm having trouble making a decision here. If we can clearly distinguish between header titles and non-title headers then it would be ok to use RHD for the former. Ideally the uses of RHT in the header section would never resemble a title and thus never run into apparent consistency issues. 

From a design perspective it is simple to say – Any large text (greater than body) used as a headline gets RHD. Typically I've recommended against using it for smaller text subheaders due to readability issues at smaller sizes (it was designed primarily as a display font), so we use RHT for those. 

Is there a world where we have both? A title header section (RHD) and a non-title header section (RHT) variant?

**Comment by mcarrano** [comment]
Per discussion in design sync meeting on Jul 21, let's update the Card component to make the card title/header use Red Hat Display by default.

**Comment by blfetche** [comment]
@mcarrano @doruskova @mcoker 

Looked into this today appears the variable --pf-c-card__title--FontFamily is not defined so the title is picking RHT

Current Screenshot on Patternfly.org
![image](https://user-images.githubusercontent.com/96086344/187820141-b116546c-5dd1-4aae-b5ef-ed86829c2fdf.png)

I went ahead and added a value for --pf-c-card__title--FontFamily, hopefully, this solves it. 

From my Local (CORE) Environment
![image](https://user-images.githubusercontent.com/96086344/187820584-37d409de-6bb8-44a6-82c9-e40af9882e99.png)

**Comment by blfetche** [comment]
Adding surge link here

https://patternfly-pr-5069.surge.sh/components/card
