### ISSUE TITLE
Bug - Text - <code> and <pre> elements do not use --pf-global--FontFamily--monospace

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#4763]
**Describe the problem**
Currently generic `<code>` and `<pre>` elements default to the browser user agent monospace. 
Should they instead be assigned to `font-family: var(--pf-global--FontFamily--monospace)`

The Openshift console has many locations where generic `<code>` and `<pre>` elements are used.

**What is your product and what release date are you targeting?**
Openshift V4.11

**Comment by mcoker** [comment]
@mcarrano @mmenestr this seems like a good update to me. WDYT about updating the font family for `<code>` and `<pre>` globally? Here's a demo of what that might look like - https://codepen.io/mcoker/pen/XWVeMNP

A problem that may arise (and you can see in the line with `function stuff($var)`) is that lines may now wrap where they previously did not since the width of the characters is different. I suspect that may not be ideal, just in general, but particularly with these elements as they often contain formatted text. That could be offered as a global opt-in until our next breaking change release if we consider that a breaking visual change.

Another approach may be to add support for these elements in the text/content component. I created a sandbox here that adds them under the "third level" section, with buttons in the bottom/right to toggle the mono font (between the current liberation mono stack and our new red hat mono font) and the page/section background (between background-100 and background-200) - https://codesandbox.io/s/cool-lake-s7ef75?file=/index.html

**Comment by mcarrano** [comment]
@mcoker I agree that this would be a good update to make. Not sure what I think about making this a global change vs localizing to the Text component. What do you think is better?

@mceledonia feel free to also chime in regarding design implications.

**Comment by mcoker** [comment]
@mcarrano I think updating the text component would be a safer approach, since that's basically opting into a new style. I'm not sure what kinds of problems may arise if we made a global change now. I think a great time to make that global change would be when we make the new red hat mono font the default monospace font in patternfly, so in our next breaking change.

**Comment by mcarrano** [comment]
Per discussion in Leads meeting on Apr 8, lets make this a global update.
