### ISSUE TITLE
Wizard - cannot append select menus to parent in a wizard

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#4794]
setting the Select `menuAppendTo` prop to be the parent - both cause issues with overflow and stacking context. This does work in a plain modal.

[This codesandbox demonstrates the side effect of appending to parent.](https://codesandbox.io/s/bold-worker-6ggke3?file=/index.js)

[This additional sandbox demonstrates an attempted work around of appending the menu to the wizard main body - not ideal](https://codesandbox.io/s/objective-hugle-84nzc6?file=/index.js)

note: both of the code sandboxes above use the menu + menuToggle rather than a select. Cost management needs the select to work for now

The footer's shadow currently needs to appear on top of the content of the wizard. If it can be drawn differently, then the menu does not need to be under the footer.

**Comment by mcoker** [comment]
I looked into this, and I can't wrap my head around a way to do this without changing the look of the wizard. The crux seems to be with the mobile layout.

* The nav needs to appear on top of whatever may be in the main wizard content area since the nav expands on top of the main content. So so need to establish a stacking context between nav and main so that the nav always appears on top of content in main, so both the nav and main content need a `z-index`, and nav needs to be higher than main.
* The footer needs to ideally stack higher than the main content and nav because the footer has a top shadow that appears on top of the content<sup>[1]</sup> and nav when expanded<sup>[2]</sup>, and per the design we don't want the shadow from the expanded nav to show on top of the footer.

That's essentially it. We could:

* Change the footer's shadow to a border, which removes the need for the footer to appear on top of the content<sup>[3]</sup>. However, this still leaves you with the shadow from the nav extending on top of the footer<sup>[4]</sup>. Maybe that's OK?
  * We use shadows to communicate depth, so you would lose that, which goes against the design recommendations.
* Use some kind of inner shadow on the main content element to create a faux shadow from the footer. However, I think this is still going to present z-index issues where the shadow's z-index is going to need to compete with the content in main since they're part of the same scrollable container. Also has the same problem as above of the nav's shadow appearing on top of the footer.
* Use a border on the footer and let the nav extend all the way to the bottom of the wizard, covering the footer<sup>[5]</sup>. The border removes the need for the footer's shadow to appear on top of content in the main area, and letting the nav extend the full height of the wizard keeps the nav's shadow from appearing on top of the footer (not sure how big of a deal that is). Personally I think that would be OK - mobile menus often cover all of the content of a thing like that anyways, and it seems fair that if the nav is open, you want to navigate by the nav links - otherwise, you'll navigate by the footer buttons, and it seems fair for the nav to need to be closed for that.

I don't know that any of these are ideal, but I think that's the basic predicament. 

[1]
<img width="964" alt="Screen Shot 2022-05-06 at 4 54 13 PM" src="https://user-images.githubusercontent.com/35148959/167221250-98682a15-f69c-4b8d-9847-0d0f2f261a1e.png">


[2]
<img width="781" alt="Screen Shot 2022-05-06 at 3 20 23 PM" src="https://user-images.githubusercontent.com/35148959/167220976-1672224b-b30f-442c-a869-40b8c45ae311.png">


[3]
<img width="1023" alt="Screen Shot 2022-05-06 at 4 32 26 PM" src="https://user-images.githubusercontent.com/35148959/167221316-cc62ed0c-9707-4e0c-bb67-8fcb725d44fb.png">


[4]
<img width="1037" alt="Screen Shot 2022-05-06 at 4 38 37 PM" src="https://user-images.githubusercontent.com/35148959/167221342-f8061ad7-a627-4403-bcb4-34a9bfca9c1c.png">

[5]
<img width="947" alt="Screen Shot 2022-05-06 at 4 57 50 PM" src="https://user-images.githubusercontent.com/35148959/167221574-78594198-3b36-4e26-9780-88fcac9b25b6.png">

**Comment by dlabrecq** [comment]
Just to be clear, not being able to append to the parent breaks keyboard navigation. This is currently a blocker for Cost Management, since we cannot push to production.

**Comment by nicolethoen** [comment]
With regards to the keyboard navigation issue:
Modal uses a focus trap, which is why appending the select menu to the document body was breaking the keyboard navigation. The workaround = appending it to the wizard itself as done in [this codesandbox](https://codesandbox.io/s/gifted-antonelli-f8h2s9?file=/index.js).

It's also worth noting that if anything spills out of a wizard or modal so far that it falls out of the viewport, then it will be unreachable by the user because the modal prevents page scrolling by design.

**Comment by sg00dwin** [comment]
> It's also worth noting that if anything spills out of a wizard or modal so far that it falls out of the viewport, then it will be unreachable by the user because the modal prevents page scrolling by design.

OpenShift has a story to transition their custom modals to use the PatternFly modal component and this will cause several form to have dropdown menu issues, so I opened a separate issue. https://github.com/patternfly/patternfly/issues/4957

**Comment by mcoker** [comment]
Looking at this a bit more, the wizard main section (with overflow) isn't "`position`ed" (it uses the default `position: static`, or is unset actually), so we could just tweak the existing `z-index` values and pull this off. https://codesandbox.io/s/elated-jerry-1xl9m5

I'm basically putting the wizard-toggle, wizard-nav (mobile menu), and wizard-footer at the same `z-index` and leaving everything else without a `z-index`. So long as a menu (or whatever) has a higher `z-index` than the footer, it will show up on top of it. And the footer still shows up on top of the mobile nav because they have the same `z-index` and the footer comes later in the DOM.

That said, a menu from the main section (and anything else with a higher `z-index` than the footer) will show up on top of the nav, too. Meaning if the nav is open and someone toggles a menu open from the main section, it will show up above the nav. As long as that sort of thing can't happen, this solution is probably OK? It's a bit fragile, but I think it's fine if we want to try and do this sort of thing going forward. It may not always be possible if the section with overflow has a `position` other than `static`.

cc @mattnolting @srambach if you want to verify and you don't see any other holes.
