### ISSUE TITLE
Bug - Table Composable - Expanding table cell changes width of columns

### ISSUE THREAD

**Issue by leSamo** [patternfly/patternfly#4837]
**Describe the problem**
Using Table Composable with expandable changes table columns width when expanding/collapsing if expandable text spans more than a single line. I believe this applies to Legacy Table as well.

**How do you reproduce the problem?**
1. Open [Table Composable Expandable demo](https://www.patternfly.org/v4/components/table/#composable-expandable)
2. Change `single cell - fullWidth` to expandable content long enough to overflow a single line
3. Expand/collapse the above row
4. Notice width of column changing slightly

Or look at this code sandbox where the description is changed to overflow a single line
https://codesandbox.io/s/weathered-pond-vmztog?file=/index.tsx

**Expected behavior**
A clear and concise description of the expected behavior.

**Is this issue blocking you?**
Just a visual bug, not a blocker

**Screenshots**
Screen capture with reproduction.

![pf-column-width](https://user-images.githubusercontent.com/8426204/166303977-700953bf-ea37-4312-a1f1-5d02a23a82ef.gif)

**What is your environment?**
 - OS: Fedora
 - Browser: Chrome
 - Version: 100.0

**What is your product and what release date are you targeting?**
Red Hat Insights - Vulnerability, [Jira ticket](https://issues.redhat.com/browse/VULN-1732)

**Comment by mattnolting** [comment]
@leSamo Thanks for raising this issue!

> [By default, most browsers use an automatic table layout algorithm. The widths of the table and its cells are adjusted to fit the content.](https://developer.mozilla.org/en-US/docs/Web/CSS/table-layout#auto)

We could set `table-layout: fixed`, but we would then have to set widths on `pf-c-table__toggle`, `pf-c-table__check`, and `pf-c-table__action`. Those cells should respond to user agent styles, consumer customizations, font-size, etc.  

The solution, (which is already available, but not highlighted) is to manage column header and/or data cell behavior. In the [this example](https://codesandbox.io/s/infallible-curie-xvrkg7?file=/index.tsx), `pf-m-width` and `pf-m-fit-content` are applied to generic `<th>` cells. This prevents visible/hidden content from adjusting their layout. 

@mcoker @mcarrano the default behavior should be preserved, otherwise the table layout is going break when customized. However, this solution isn't obvious in the documentation. I think it might be good to call this out in the documentation and provide an example where the cell widths don't change, wdyt?

**Comment by mcoker** [comment]
@mattnolting sounds good to me!
