### ISSUE TITLE
Bug - Dark Theme - $pf-color-blue-400 is not defined

### ISSUE THREAD

**Issue by skobyda** [patternfly/patternfly#4906]
**Describe the problem**

An update from patternfly `4.194.4` -> `4.196.7` breaks importing `@patternfly/patternfly/components/Alert/alert.scss`, which we import at [our scss](https://github.com/cockpit-project/cockpit-machines/blob/main/src/machines.scss#L8) in order to add custom ct-`popover-alert` overrides.
It seems that [src/patternfly/sass-utilities/themes/dark/scss-variables.scss](https://github.com/patternfly/patternfly/blob/861d9e0e26be18e74c8950a84f907dc05c085638/src/patternfly/sass-utilities/themes/dark/scss-variables.scss#L17) uses variable `$pf-color-blue-400`. But no such variable is defined at [src/patternfly/sass-utilities/themes/dark/colors.scss](https://github.com/patternfly/patternfly/blob/861d9e0e26be18e74c8950a84f907dc05c085638/src/patternfly/sass-utilities/themes/dark/colors.scss). Altough I have no experience with patternfly's code, so take my theory with a grain of salt.

**How do you reproduce the problem?**

1. Update to the following dependency versions:
```
    "@patternfly/patternfly": "4.196.7",
    "@patternfly/react-core": "4.221.16",
    "@patternfly/react-icons": "4.72.16",
    "@patternfly/react-styles": "4.71.16",
    "@patternfly/react-table": "4.90.16",
```
2. Add import to your scss: `@import "../../node_modules/@patternfly/patternfly/components/Alert/alert.scss";`
3. Webpack fails:
```
ERROR in ./src/machines.scss (./src/machines.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./src/machines.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
   ╷
17 │ $pf-global--primary-color--300: $pf-color-blue-400; // primary blue with white text on top for contrast
   │                                 ^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@patternfly/patternfly/sass-utilities/themes/dark/scss-variables.scss 17:33  @import
  node_modules/@patternfly/patternfly/sass-utilities/themes/dark/_all.scss 2:9              @import
  node_modules/@patternfly/patternfly/components/Alert/themes/dark/alert.scss 1:9           @import
  node_modules/@patternfly/patternfly/components/Alert/alert.scss 251:9                     @import
  src/machines.scss 8:9                                                                     root stylesheet
```
Full log can be seen [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-740-20220614-134327-3d481433-fedora-36/log.html)

**Expected behavior**
`@import "@patternfly/patternfly/components/Alert/alert.scss";` would not break compilation

**Is this issue blocking you?**
Its blocking cockpit-machine's [package.json refresh](https://github.com/cockpit-project/cockpit-machines/pull/740). 

**What is your environment?**
 - OS: fedora-35

**What is your product and what release date are you targeting?**
cockpit-machines

**Comment by mcoker** [comment]
Hey @skobyda! Dark theme styles are overrides of default styles, and `$pf-color-blue-400` is defined in our default SCSS in [src/patternfly/sass-utilities/colors.scss](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/colors.scss).

There are a bunch of SCSS base vars, mixins, etc in [src/patternfly/sass-utilities](https://github.com/patternfly/patternfly/tree/main/src/patternfly/sass-utilities) needed to compile component SCSS. 
 For example, in the alert stylesheet, the [pf-line-clamp()](https://github.com/patternfly/patternfly/blob/53539639ef305b90fcfe9576b6962d8c1a5247be/src/patternfly/components/Alert/alert.scss#L204) mixin defined in [src/patternfly/sass-utilities/mixins.scss#L155-L162](https://github.com/patternfly/patternfly/blob/53539639ef305b90fcfe9576b6962d8c1a5247be/src/patternfly/sass-utilities/mixins.scss#L155-L162).

Are you currently importing any of the base PF SCSS so that `alert.scss` default/light theme styles compiles? I would expect so if `pf-line-clamp()` is compiling fine. 

FWIW import the base SCSS, you can import [src/patternfly/sass-utilities/_all.scss](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/_all.scss).
