### ISSUE TITLE
Bug - Modal - long dropdown menus can overflow out of view and are unreachable without scroll.

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#4957]
**Describe the problem**
Modals that have dropdown elements, towards the bottom of the content, and with the browser viewport at a small height, can cause the menu to extend off the screen. And be inaccessible since the entire modal itself doesn't enable scrolling.

**How do you reproduce the problem?**
Resize viewport to a short height and open dropdown. 
https://www.patternfly.org/v4/components/modal/#with-dropdown

**Expected behavior**
A couple of options*...

1. Since the default scrolling behavior for a PatternFly modal is to enable scroll on the `.pf-c-modal-box__body` then it would seem the menu should be within that scrollable area. Either making the `.pf-c-modal-box__body` height taller or when the content is tall and scrolled down to the bottom then switch the menu `DropdownDirection` to up.
2. Or continue to have the drowdown menu extend outside the modal and enable scrolling of the entire modal view.

OpenShift has a story to transitioning from their custom modals to use the PatternFly modal component and this will cause several forms to have dropdown menu issues. 

![PF-modal-dropdown-bug](https://user-images.githubusercontent.com/1874151/178070577-80f8eb1a-e976-4508-9a5b-0e083e6f7948.gif)

![PF-modal-dropdown-bug-tall](https://user-images.githubusercontent.com/1874151/178071505-6fa2dcfe-c1b0-4e84-a205-7219836a7b58.gif)

_*side note - Bootstrap 5 modals have both behavior options_

**Comment by nicolethoen** [comment]
Hello @sg00dwin thank you for opening this issue!
We do offer many variants and features in dropdowns and menus to accommodate these sorts of scenarios.
Menus can be appended so that they open in a direction where they will have more room. They can also be given a height so that they are scrollable if their contents are too long.

I was wondering if those features might aid you in this request. Currently, the design for the modal which overlays the content of the viewport and centers itself there based on its size, is a constraint that is not something we can update until PatternFly has a breaking change update.
