### ISSUE TITLE
Bug - [Dark Theme] - [Need Color Distinction for Read-Only Code Editor between Light and Dark Themes]

### ISSUE THREAD

**Issue by heyethankim** [patternfly/patternfly#4985]
**Describe the problem**
There is no color differentiation for the read-only code editor between light and dark themes.

<img width="1810" alt="image" src="https://user-images.githubusercontent.com/84546841/179760708-3097dbd4-264b-4590-a363-702676d00594.png">
<img width="1810" alt="image" src="https://user-images.githubusercontent.com/84546841/179760794-e15364e9-c782-49f0-b535-7d0345f7618d.png">

**How do you reproduce the problem?**
Provide steps to reproduce. A [codepen](http://codepen.io) or [codesandbox](https://codesandbox.io/) demonstrating the problem is appreciated.

**Expected behavior**
A clear and concise description of the expected behavior.

**Is this issue blocking you?**
List the workaround if there is one.

**Screenshots**
If applicable, add screenshots to help explain the issue.

**What is your environment?**

**What is your product and what release date are you targeting?**

**Any other information?**

**Comment by heyethankim** [comment]
FYI, @mceledonia

**Comment by mcarrano** [comment]
@heyethankim @mceledonia not sure exactly what's going on here, but I wanted to note that the Code Editor has it's own dark theme setting (https://patternfly-org-pr-3090-v4.surge.sh/v4/components/code-editor#basic). Although in dark mode, I'm not sure what we expect the read-only appearance to look like.

**Comment by heyethankim** [comment]
Just checked on this page. https://patternfly-pr-3686.surge.sh/components/code-editor. It seems it is a little darker. 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/84546841/179982318-a4ab3f27-9d50-4026-96f0-7b2569474a52.png">

@mcarrano Would you please confirm if this is the final color the team should use for the read-only code editor?

**Comment by mcarrano** [comment]
@mceledonia can you address this question? (above)

**Comment by mceledonia** [comment]
In the [light theme code editor](https://www.patternfly.org/v4/components/code-editor/design-guidelines#displaying-code-in-a-code-editor) we apply an inner gray border for read only. It seems as though it would make sense to do the same for dark theme. That border could be a shade lighter than the code editor background.

However in @heyethankim's screenshot above it looks like even in light theme the whole background is changing from white to gray, rather than just the border. Is this an intentional change in design? We can suggest a different background color for the product to use, but should be consistent with our documentation/implementation approach either way. CC @mcarrano

**Comment by mcarrano** [comment]
@heyethankim I am going to close this out as it looks like the gray background is a customization from product. You might consider whether the dark theme should be set in the code editor itself if you want this to also display as dark.
