### ISSUE TITLE
Button - Need new variant that retains state for opening and closing a drawer

### ISSUE THREAD

**Issue by mcarrano** [patternfly/patternfly#5012]
A request has been made to create a button variant to be used as a drawer toggle. Contingent on completion of: https://github.com/patternfly/patternfly-design/issues/1173

**Comment by srambach** [comment]
Copying the Marvel link here for reference: https://marvelapp.com/prototype/idfijd4/screens
I have a few questions:
- The number badge shown in the design is taller and rounder than the badge component. Is this intended, or should it be the same as a badge? If not the same as the badge, what are the dimensions?
- Depending on the previous answer, what should happen if the number of digits increases so that the width must increase?
- Assuming the hover/active/focus states are similar to a link button, is there any other state required, such as when the drawer is expanded?
@mcarrano @simontalusan @mmenestr

**Comment by mcarrano** [comment]
@srambach answers to your questions:

> The number badge shown in the design is taller and rounder than the badge component. Is this intended, or should it be the same as a badge? If not the same as the badge, what are the dimensions?

If this is the case, that's an oversight in the design. It should use a standard badge.

> Depending on the previous answer, what should happen if the number of digits increases so that the width must increase?

I guess it would grow the width of the button, unless you see another way.

> Assuming the hover/active/focus states are similar to a link button, is there any other state required, such as when the drawer is expanded?

We decided that this was not necessary since the user can close the drawer by clicking its (x) button. So basically all we are requesting is the ability to add a badge inside a button. In this use case we are displaying that as a plain button, but do you think we should support that for any kind of button? I think so, but not sure if that will result in other complexities.

**Comment by srambach** [comment]
@mcarrano I wonder about plain button vs any kind. I sort of think we should make it work for any, but you tell me if you want to allow that or not.

**Comment by mcarrano** [comment]
> @mcarrano I wonder about plain button vs any kind. I sort of think we should make it work for any, but you tell me if you want to allow that or not.

Yes, I agree that we should enable this option for any type of button.

Good question about what the disabled state should be. @simontalusan @mmenestr thoughts? It wasn't a requirement to support read vs unread status, but I guess we should allow that. Not sure how that factors into the hover state though. Not sure the badge itself needs a hover state.

**Comment by srambach** [comment]
@mcarrano @mmenestr @simontalusan The mockup shows a hover state on the (unread) badge matching the link color. Let me know if you don't want that because if it doesn't need that and the alignment/spacing is ok, then no css is actually going to be needed.

**Comment by mmenestr** [comment]
**For the disabled state:** I think it should just be whatever the button disabled state it + the read version of the badge maybe, since it's grey? 

**For the hover:** If the badge component has a hover state, then I'd add it, if not then I'd say no need! I'd just follow the original component implementation for simplicity. As long as the words change color it should be fine I feel like.
