### ISSUE TITLE
Bug - Form Group - Labels with icons should be on the same line

### ISSUE THREAD

**Issue by agagancarczyk** [patternfly/patternfly#5063]
**Describe the problem**
There needs to be a way to keep the label and the icon on the same line, and Patternfly currently doesn't support this with its current Form styling. 

**How do you reproduce the problem?**
This issue is described in detail in our Keycloak UI https://github.com/keycloak/keycloak-ui/issues/2073

It can be reproduced in Keycloak UI with the following steps: 
1. Run Keycloak 19: `docker run --rm -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin [quay.io/keycloak/keycloak:latest](http://quay.io/keycloak/keycloak:latest) start-dev`
2. Go to `Clients` from the left-side menu
3. Create a new client
4. Select created client, go to `Authorization` > `Export` tab
5. Observe that icon is on its own on the next line

**Expected behavior**
The labels with icons should be on the same line. 

**Is this issue blocking you?**
Yes, please see https://github.com/keycloak/keycloak-ui/issues/2073

**Screenshots**
![Screenshot 2022-08-31 at 17 19 32](https://user-images.githubusercontent.com/4890675/187728801-7f25a4c6-bb11-4f0b-b49e-0ef0d8d7a2cf.png)

**What is your environment?**
 - OS: macOS Monterey v12.5 
 - Browser Chrome Version 104.0.5112.101 (Official Build) (x86_64)

**What is your product and what release date are you targeting?**
Keycloak UI

**Any other information?**

**Comment by jenny-s51** [comment]
cc @mcoker

**Comment by mattnolting** [comment]
The solution to this issue is to omit returns in the html and use `&nbsp;` instead of a standard space (currently rendered in the markup). 

Instead of
```
<div class="pf-c-form__group-label">
  <label class="pf-c-form__label">
    <span class="pf-c-form__label-text">Label with very long text lorem ipsum</span>
    <span class="pf-c-form__label-required" aria-hidden="true"> *</span>
  </label> 
  <button>
    <svg>
  </button>
</div>
```

It needs to be written and rendered as
```
<div class="pf-c-form__group-label"><label class="pf-c-form__label"><span class="pf-c-form__label-text">Label with very long text lorem ipsum</span>&nbsp;<span class="pf-c-form__label-required" aria-hidden="true">{remove space here}*</span>&nbsp;<span {change button to span, display: inline}><svg></span></label></div>
```

A couple of things to note
- Button will not render an `inline` display value. https://html.spec.whatwg.org/multipage/rendering.html#button-layout, Therefore a `<span>` should be used in its place with `role="button"`
- There is a space before the required asterisk. This should be removed and a non-breaking space `&nbsp;`, before the element, should be used in its place.
- Help button should move to inside the `__label` element

**Comment by DaoDaoNoCode** [comment]
@mattnolting I have pushed some changes to your PR.
1. Remove the spaces before and after `&nbsp;`
2. Create a handlebars helper named `removeWhiteSpaceForPrettier`, you can use it anywhere in your .hbs file and it could remove the white space where you use it. Because we use `prettyhtml` to format the code, it's impossible to do the formatting when compiling the handlebars files. Even if we remove the white spaces between the tags, the `prettyhtml` will add it back, that's why I decide just to create a hardcoded string as a flag and remove the flag along with the white spaces after the formatting is done.
3. I only applied `removeWhiteSpaceForPrettier` at one place, you could add it to other places to make the final output you want as the comment above.
