### ISSUE TITLE
Update to latest RedHatFont

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5114]
We can clean up our old font files, and remove the need for `.pf-m-updated-font` and go ahead and add support for the latest RHT/RHD/RHM files. 

@mcarrano @mmenestr @mceledonia should we add tabular number support for any components by default? Maybe things like input fields? Or should that be something a user opts in to? For reference, here's a comment with a quick blurb on what that is - https://github.com/patternfly/patternfly/pull/4476#issuecomment-975894979

Also do we want to use the variable font by default (with optional opt-in to the regular font?) or use the regular font with an opt-in for the variable font? I'm inclined to use the variable font by default, I think that's the way to go. We can run some quick tests, too, to see the page weight difference bundling the variable font on a typical page versus using regular fonts.

**Comment by markcaron** [comment]
Thanks for adding this @mcoker!

Wondering if we can align on font stacks too. Currently, we're adding both naming schemes (i.e. `RedHatText` and `"Red Hat Text"`) in [our design tokens](https://github.com/RedHat-UX/red-hat-design-tokens/blob/main/tokens/font/family.yml) in order to cope with the varying ways the fonts are defined. And, when we pull in PF Core—referencing our local RH fonts or those defined on static.redhat.com—things get hairy.

We're totally open to adjusting/aligning however we need. Might be a discussion in our DPO.

Note: we're planning on removing `Overpass` from the stack altogether after Brand requested we do so, since "falling back to Helvetica is a closer match" to our Red Hat font.

CC: @bennypowers and @zeroedin

**Comment by nicolethoen** [comment]
We will need a follow up issue to track implementation of adopting/using the variable font
