### ISSUE TITLE
Introduce stateful button

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5129]
The immediate use case for this is with the notification badge. Right now the notification badge in core is its own element designed to be placed in a plain button. Since the notification badge maintains state for expanded/open, we will need to introduce state to the button, which seems like a reasonable approach. As @mcarrano [mentioned below](https://github.com/patternfly/patternfly/issues/5129#issuecomment-1371384046), Carbon is doing this, too - https://www.lightningdesignsystem.com/components/buttons/#Stateful

This task will will add a stateful button with examples and mark the examples as `isBeta`.

Then it can be part of the same task or a new issue, we should either update or add new examples of notification badge using the stateful button instead of notification badge, and ideally mark those demos as `isBeta` along with a comment that they are using the stateful button. We don't typically do that with demos, but I think it might be useful - wdyt @mcarrano @nicolethoen?

**Comment by mcarrano** [comment]
@mcarrano @thatblindgeye @nicolethoen @tlabaj I'd like to have more discussion about this one before proceeding. I've done a bit more research and thinking about this since the planning meeting and reached the following conclusions:

* The Menu Toggle component should be left as is - meaning that it is exclusively intended to toggle a menu using our composable approach. In other some design systems, a "Toggle" is what we call a Switch. I think renaming the Menu Toggle to just Toggle might cause some confusion here.

* Instead, I propose that we add a stateful button variation that can be used for use cases like opening a drawer. For reference, I found this example in the Lightening Design system: https://www.lightningdesignsystem.com/components/buttons/#Stateful We did recently add a Button with Count variation that is almost this: https://www.patternfly.org/v4/components/button#button-with-count

So we would still plan to deprecate the Notification Badge, but use the stateful button variant vs a menu toggle.

Thoughts? If you agree with this approach, I can detail the states we should support.

**Comment by nicolethoen** [comment]
My initial reaction is that this stateful approach makes sense.

**Comment by thatblindgeye** [comment]
I do like the idea of offering stateful buttons similar to what Lightning Design has. With that sort of approach, assuming we would continue using `aria-expanded` on the button for a notification badge (it would make more sense than `aria-pressed` I think), we'd just need to document when to use that stateful button vs a menu toggle (though that would probably be easy enough).

Overall I echo Nicole's initial reaction, though.

**Comment by mcoker** [comment]
That works for me, fwiw we already have an expanded class for the "control" button, which mimics the menu toggle - https://github.com/patternfly/patternfly/blob/196aa1c3294163aa569512f07a93fce5ec077dbd/src/patternfly/components/Button/button.scss#L533-L541 

Although I noticed their menus just use their button component - https://www.lightningdesignsystem.com/components/menus/. Also buttons for the [table row dropdown](https://www.lightningdesignsystem.com/components/data-tables/). Though they have something they call an "input faux" for a basic menu toggle with text. I suspect it's named that way because they mimic select menus (form selects, in PF), which is probably our most typical use case for a menu toggle. You can see that toggle here - https://www.lightningdesignsystem.com/components/expression/. Though I can't find any docs on that input faux component.

If our buttons can be stateful, could they replace the menu toggle? At least under the hood and in core anyways, since there is so much overlap. That's probably too much to try and squeeze in for v5 even if we wanted to do that, but wanted to mention it.

**Comment by tlabaj** [comment]
@mcoker I like the idea of using the stateful button under the hood for the menu toggle.   I agree that we should not try and squeeze it into v5 at this point.

**Comment by nicolethoen** [comment]
@thatblindgeye @mcoker 
my understanding is that rather than using a menu toggle for the notification badge, this issue should be changed to adding stateful button variants and then either as part of that issue, or as a follow up issue, we build demos to replace the notification badge showing how to use a stateful button instead

**Comment by mcoker** [comment]
@nicolethoen @thatblindgeye updated the issue title/description - feel free to make changes as you see fit.
