### ISSUE TITLE
Questions - usage of updated variable fonts

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#5273]
**Describe the problem**
I just tried switching cockpit to use variable fonts, and I noticed some weirdness. Seems all elements that used to use `--pf-global--FontWeight--bold` RedHatText the now get displayed with bigger font weight than before.

## Screenshot with the variable fonts
See the description list labels in this screenshot for example
![Screenshot from 2022-12-03 17-20-12](https://user-images.githubusercontent.com/14921356/205451036-1bdf7b07-ac98-4556-ae25-188c894f8b81.png)

## Screenshot before starting using variable fonts
![Screenshot from 2022-12-03 17-19-09](https://user-images.githubusercontent.com/14921356/205451045-d778b2df-d255-4427-a4e5-2e7074b58876.png)

You can see in the inspector, in the first case the font used us RedHatText VF Regular and in the other case RedHatText Medium Regular. Although I don't see any difference in the font-size in the inspector, it's clear to me that the old font is  a 500 font weight in the same VF font. 

I also found https://github.com/patternfly/patternfly/issues/4859 but this did not bring me more forward. Please some help here?

**Comment by nicolethoen** [comment]
We have thus far been unable to determine if we can custom compile a version of the variable font that includes the font weights we want for PF?
If we CAN custom compile - we could allow products to opt into using the variable font in the future.
Otherwise, this would need to be done during a breaking change release. We'd need to create tokens for unique font weights.
