### ISSUE TITLE
Bug - [Page] - [Page section should not change background color in dark mode if its sticky]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#5301]
**Describe the problem**

Please take a look at the first page section where the breadcrumb is located. This first screenshot is without using sticky.
![Screenshot from 2023-01-04 12-20-11](https://user-images.githubusercontent.com/14921356/210545599-4746ddad-e58e-40df-945c-17d3a745cc1e.png)

This following scrrenshot is when we add the pf-m-sticky class to the page section. See how this affects the background color of the component.
![Screenshot from 2023-01-04 12-20-41-sticky-top](https://user-images.githubusercontent.com/14921356/210545592-fe35ce85-8a9f-47fa-88a4-ed49e3380e84.png)

**Expected behavior**
I believe this is not the expected behavior. In white mode there is also not background change when stikcy. In cockpit we use sticky page sections heavily, and  we expect it to look like the non sticky mode. If this does not work for patternfly, cockpit can keep using local workaround.

![Screen Shot 2023-01-04 at 12 36 05](https://user-images.githubusercontent.com/14921356/210546894-94b268fd-d277-4e53-8ab6-940ddaae3f95.png)

**Is this issue blocking you?**
No

**Comment by mcoker** [comment]
cc @mceledonia

**Comment by mceledonia** [comment]
Good catch, this is actually an intentional deviation from light theme. In dark theme we use background color change to represent elevation rather than relying solely on shadows, since shadows are more difficult to see against dark background colors. So as the elevation gets higher, the background gets lighter. This third background color was introduced for "floaty" elements like the sticky header we see here.
