### ISSUE TITLE
Bug - List - List Item and Icon are not aligned properly

### ISSUE THREAD

**Issue by sumitridhal** [patternfly/patternfly#5454]
**Describe the problem**
When using the icon component within the List item, the icon and text are not properly aligned.
check the last item in list (screenshot).

**How do you reproduce the problem?**
Alignment issue when using icons in the list:
```
<ListItem icon={<Icon status="warning">
   <ExclamationTriangleIcon />
</Icon>}>Third</ListItem>
 ```

**Expected behavior**
Both text and icon should be aligned

**Screenshots**
<img width="398" alt="image" src="https://user-images.githubusercontent.com/2717960/228224861-47aa1d14-d003-4a3a-b367-f0f9d21cb3a8.png">

**Comment by mcoker** [comment]
Hey @sumitridhal - this should be fixed in our upcoming v5 release. The icon component was updated to inherit its size/font-size, line-height, and color by default, which should address issues like these. Here is a codesandbox if you'd like to confirm - https://codesandbox.io/s/hardcore-blackburn-mhllld?file=/index.tsx
