### ISSUE TITLE
Bug - Toolbar - examples with selects misaligned on firefox

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#5532]
Seems to be an issue with how MenuToggles are rendering

![Screenshot 2023-04-27 at 7 59 39 AM](https://user-images.githubusercontent.com/26305082/234855467-b199e250-d163-4945-96aa-7ed5fbb05b56.png)
![Screenshot 2023-04-27 at 7 59 43 AM](https://user-images.githubusercontent.com/26305082/234855470-6443e883-4323-4060-b712-b13722822671.png)

**Comment by mcoker** [comment]
Looks like this is due to the baseline alignment introduced in https://github.com/patternfly/patternfly/pull/5201, and isn't limited to just selects. Here is a dropdown next to a text input group that are misaligned:

<img width="705" alt="Screenshot 2023-05-04 at 10 08 31 AM" src="https://user-images.githubusercontent.com/35148959/236250024-05c6444a-f587-486f-be44-b49a5a55f0d7.png">
