### ISSUE TITLE
Bug - [modifier classes] - [Modifier classes are missing v5 prefix]

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly#5606]
**Describe the problem**
PF5 switched the class prefix to `pf-v5` for mostly everything. However, modifier classes are still using the old prefix. This is a bit annoying for the consumers, and it's also creating inconsistency. Is this oversight or a desired behavior?

**Comment by nicolethoen** [comment]
Indeed - modifiers do not need to be versioned. so anything with `pf-m-[x]` can stay as it is.

**Comment by KKoukiou** [comment]
@nicolethoen so I guess you mean that the code from the modifier classes it promised to stay the same or at least backwards compatible with PF4.
That's fair reasoning, but still I think naming should be consistent by using a single prefix for everything.

**Comment by nicolethoen** [comment]
it's because modifier classes modify versioned components. Their styles are directly tied to the versioned component classname and don't apply styles in isolation.

Changing the name of a modifier would be a breaking change so we wouldn't do that outside of a major release. 
We could always add modifiers in the future.

But a modifier that has an effect on a v4 component will always have that same effect on that v4 component.
That same modifier might have a slightly different effect on a v5 component if the design has been updated.

**Comment by KKoukiou** [comment]
@nicolethoen I still don't see the argument pro for not changing the classnames so that everything in PF5 is prefixed the same way. I see your point that it's not necessarily needed but I also don't see a reason to not do it. Anyhow - it's not a strong opinion here, but makes Patternfly and custom overrides code in projects much cleaner. (I used in the past few days much 'sed' command to automatically update our custom CSS to be using the v5 prefix. But I had to make sure I don't my mistake auto-update the 'pf-m' classes.)

**Comment by nicolethoen** [comment]
I'll definitely note the thought. 
And @mattnolting @mcoker @srambach want to make sure you note the thought as well.

**Comment by mattnolting** [comment]
> it's because modifier classes modify versioned components. Their styles are directly tied to the versioned component classname and don't apply styles in isolation.

@KKoukiou  @nicolethoen That's the rationale we employed being that our codebase was designed to provide overridable css variables, rather than overridable selectors. Leaving modifiers unversioned simplifies maintenance and, because the modifiers focus on updating css variables and are attached directly to their prefixed counterpart, there would be no conflict in applying them to alternative versioned components. One argument is that, for core users, it's less repetition and less code.  @mcoker and @srambach WDYT?

**Comment by srambach** [comment]
I can see the case for consistency. However, @mattnolting has a good point - that customizations should be done with CSS variables.  Given that all modifiers are used with versioned class names, and they adjust versioned variables, there's no technical reason to version the modifiers. So leaving them as is makes it read a little more cleanly. My preference leans to leaving them unversioned.

**Comment by KKoukiou** [comment]
So I see a small preference towards keeping the names for modifiers as is. From my side feel free to close to the issue as 'WONTDO".
