### ISSUE TITLE
Spike - Determine plan for implementing RTL

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5674]
Create a plan for implementation of RTL support. 
- Breaking change or could it go into a release? E.g. Opt in via Sass function that does or doesn't add the logical property? 
- What to do about things that don't reverse? Consider items like directional icons (carets, arrows) and things that are positioned left/right, like tooltips and dropdowns.

**Comment by mcoker** [comment]
Initially I think we would:
* Identify properties we want to update - margin, padding, border positions, insets, text-align. Here's a full list https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_logical_properties_and_values
  * Ensure they have full browser support
  * Should we consider logical properties that may not be an immediate need for RTL? Maybe width/height -> size could be one.
* Identify other things we might want to have RTL support for that either aren't currently possible or may need to be manual - flipping toggle icons, or updating something that uses any of the `transform` functions, for example. Is there a solution there?
* Add a mixin that can take the existing style (eg, `margin-top: 4px`) as property and value arguments and can spit out the logical property (or different property) in its place. It could do something like `[dir="rtl"] .pf-icon-element { transform: rotate(180deg); }` to flip an icon. 
* Discuss whether we want to
  * Include styles as an opt-in in base patternfly (like we do now for opt-in styles) - this would add quite a bit of weight
  * Create a separate stylesheet testers can use to validate if anything breaks

We also need to have a visual regression tool (screenshot comparisons would be great) since this will touch a ton of code, and nothing should change visually with this update with either our legacy properties or logical properties when using LTR.

**Comment by srambach** [comment]
Notes from RTL lessons learned meeting with @KKoukiou @garrett @mcoker @mattnolting @andrew-ronaldson @nicolethoen @srambach 

Cockpit has overrides for padding/margin/inset to use logical properties
Some icons needed to be flipped (carets/arrows). They've used `transform: scaleX(-1)` with care so that no text gets flipped accidentally
Where PatternFly uses margin for spacing rather than flex/grid with gap is the biggest problem
Cockpit tests by manually flipping to RTL, but with English
Graphs are challenging. In some cases, they've mirrored the entire graph and then flipped the text back around
Spinners do not need to be reversed, as clocks universally move clockwise.
Margin-trim and subgrid, when available, will be useful for solving some remaining problems
Recommendations:
- Use gap instead of margin/padding
- Use logical properties
- It's not necessary to change all the variable names, but just use them in the logical properties

Overrides: https://github.com/cockpit-project/cockpit/blob/main/pkg/lib/patternfly/patternfly-5-overrides.scss
Victory charts issue: https://github.com/FormidableLabs/victory/issues/739
