### ISSUE TITLE
Bug - v5 preview testing - Select arrow (deprecated) 

### ISSUE THREAD

**Issue by dlabrecq** [patternfly/patternfly#5702]
While testing Cost management with pf-v5, I noticed our Select component has odd borders around the down-arrow.

Before the selection
<img width="422" alt="Screenshot 2023-06-28 at 1 23 47 PM" src="https://github.com/patternfly/patternfly-react/assets/17481322/b32ba5af-4c7d-4452-964d-fd4a18679681">

After the selection
<img width="452" alt="Screenshot 2023-06-28 at 1 24 55 PM" src="https://github.com/patternfly/patternfly-react/assets/17481322/8026b411-67aa-44cb-8bb4-185d689989f6">

Code
https://github.com/dlabrecq/koku-ui/blob/pf-v5/src/routes/components/groupBy/groupBySelect.tsx#L146

**Comment by mcoker** [comment]
Transferred to core after identifying with @gitdallas that it's a styling issue. The select container sizes itself down smaller than the text input inside of it, and the select container should maintain its size based on the size of its children. 

However, it's worth nothing that this is also an existing issue in PF4, it just isn't as visible because of the extra border visible in dan's example above. That extra border should be fixed in v5 now via https://github.com/patternfly/patternfly/pull/5698, so AFAIK the deprecated select is now behaving the same way the pf4 select behaves now.

<img width="937" alt="Screenshot 2023-06-30 at 3 40 05 PM" src="https://github.com/patternfly/patternfly/assets/35148959/41a575e4-7e15-40cd-bceb-ef78f937e869">

<img width="445" alt="Screenshot 2023-06-30 at 3 39 55 PM" src="https://github.com/patternfly/patternfly/assets/35148959/bdb5954c-d070-4fef-9a6b-3b4c60994b60">

**Comment by nicolethoen** [comment]
This will be fixed in this PR https://github.com/patternfly/patternfly/pull/5698, so once we have updated RCs, we can double check this.

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/pull/5698
