### ISSUE TITLE
Bug - FormSelect - Applying "pf-m-placeholder" causes all root level options to grey out on chrome

### ISSUE THREAD

**Issue by phill-85** [patternfly/patternfly#5751]
**Describe the problem**
Setting `pf-m-placeholder` on the wrapping span of a `FormSelect component` causes all the options not in optgroups to grey out on chrome.

The first image is chrome (note option 5 & 6 are grayed out), the second one is firefox.
![image](https://github.com/patternfly/patternfly/assets/4619659/92a7d031-9ab0-4144-ba90-a59d89cf69e2)
![image](https://github.com/patternfly/patternfly/assets/4619659/7c5a2008-697a-46ec-8aa9-70a07c6f9bc3)

**What is your environment?**
 - OS: Ubuntu 23.04
 - Browser 114.0.5735.198 (Official Build) (64-bit) & Brave browser

**Comment by mcoker** [comment]
Hey @phill-85! Thanks for reporting this issue. I'm unable to reproduce this using chome and brave. Can you share a codepen or codesandbox that replicates the bug you're seeing? Or link to an example on one of our documentation sites if you're seeing it there, too?

FWIW, @srambach has a PR up that changes some code that looks like it could be related, I'm curious what you're seeing in that PR preview. Here's the PR - https://github.com/patternfly/patternfly/pull/5752, and here is a link to the form select from that PR - https://patternfly-pr-5752.surge.sh/components/forms/form-control#select

**Comment by phill-85** [comment]
> FWIW, @srambach has a PR up that changes some code that looks like it could be related, I'm curious what you're seeing in that PR preview. Here's the PR - #5752, and here is a link to the form select from that PR - https://patternfly-pr-5752.surge.sh/components/forms/form-control#select

On that link you supplied ^ removing the `pf-m-placeholder` from the span wrapping the select with the `id="select-selectable-placeholder"` causes all the options to change from grey to black. See: https://drive.google.com/file/d/1u1qYtju0EpR4voJz16HHD1MIRlh9kti1/view?usp=sharing for a video.

It doesn't appear to affect child `option's` of an `optgroup`

**Comment by phill-85** [comment]
I've had a play and I don't know if this is fixable...

i changed `--pf-v5-c-form-control--m-placeholder--Color` to red. The style inspector shows the `.pf-v5-c-form-control.pf-m-placeholder > select` rule as overridden on the option tag. 

Even adding `!important` didn't make a difference.

See that attached screenshot.

![image](https://github.com/patternfly/patternfly/assets/4619659/d924c4ef-74ff-4ca9-8389-cb415521a0f8)

**Comment by ferhoyos** [comment]
I have the same issue, being able to reproduce in 'Validated' example of https://www.patternfly.org/components/forms/form-select/:

![image](https://github.com/patternfly/patternfly/assets/122779323/da5ffcb6-22b6-43d7-afe5-b6fba6c35c75)

My environment is:
OS: RHEL 8.7
Browser: Chrome 115.0.5790.170

Taking a look to Chrome Dev tools a weird thing happens:
`color`value is `var(--pf-v5-c-form-control--Color);`, but instead of taking the good one at the top (`var(--pf-v5-c-form-control--m-placeholder--child--Color); -> #151515`, it takes the overwritten one in the middle (`var(--pf-v5-c-form-control--m-placeholder--Color);) -> #6a6e73`.

![image](https://github.com/patternfly/patternfly/assets/122779323/5e5c8faf-e744-4629-a5ba-a5cb30c7b3d6)

I don't know why this is happening, maybe due to the fact that color is an inherited property from `span.pf-v5-c-form-control...

My proposal is to add same color definition to the CSS class `.pf-v5-c-form-control.pf-m-placeholder > select > *` and overwrite the inherited one. Doing this the color value takes the correct variable.
![image](https://github.com/patternfly/patternfly/assets/122779323/e37bac1f-aade-421f-a39d-447b7eea2ff2)
