### ISSUE TITLE
Global: Create a mixin to handle logical directions (RTL)

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5758]
Create a mixin that can be used in components to handle using logical directions (inline/block start/end etc).

This does not include applying it to all components, but can include one or two components to validate the method.

**Comment by mcoker** [comment]
Closing for now. After chatting about the deliverable goal with @nicolethoen and @srambach, as long as we don't introduce any regressions in LTR, dropping the logical properties directly in the styles should be fine, and we can consider it beta so that we can continue to iterate on the details in subsequent releases.
