### ISSUE TITLE
Implement RTL: button, toggle group, and notification badge

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#5820]

**Comment by thatblindgeye** [comment]
Button and ToggleGroup dont seem to require any more updates. Only updates that would be needed would probably be more to do with individual icons that need to be reversed. Button could possibly use an update to mirror the spinner for the progress variant, but that depends on whether we're mirroring spinners across the board.

For Notification Badge, there's an issue with the markup that prevents the icon from being rendered to the right of the count text (like in something like Alert, where simply applying `dir="rtl"` causes the severity icon to render to the right of the alert title). Looks like it's because Notification Badge doesn't have any sort of wrapper around the icon; wrapping it with an inline-block div results in the expected behavior.

Default notification badge with RTL enabled:

![image](https://github.com/patternfly/patternfly/assets/70952936/5372ab29-31e6-4f40-8bc8-131df4705566)

Adding a wrapper around the icon:

![image](https://github.com/patternfly/patternfly/assets/70952936/e9907a5c-ae03-47d5-9fe3-d461e9227500)


In React applying `dir="rtl"` works fine, causing the icon to render to the right of the badge count, so it's only an issue in Core with the `i` element being used for the icon. This also isn't tied to the badge using numbers (applying RTL to text that includes numbers may cause the number to appear on our right, e.g. "24 minutes ago" would render as "minutes ago 24"). Making the badge count a string like "text" has the same result.

**Comment by thatblindgeye** [comment]
Per convo the issue above with the notification badge should be resolved when text is in an RTL based language, as the icon gets flipped in those cases. No other updates are needed at the component level for this issue.

**Comment by mcoker** [comment]
✅

**Comment by mcoker** [comment]
✅
