### ISSUE TITLE
Spike - investigate need to version penta tokens

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5929]
We should put together a demo and see if we need to version tokens.

**Comment by srambach** [comment]
It does seem that best practice is to version tokens, and in order to make sure that changes in tokens don't cause errors if two versions of PatternFly are used, we should version the tokens.

Proposal is to use `--pf-t-vX--` as the prefix, where X is the version number. This version should be distinct from the PatternFly version, as tokens could be updated independently from core/react.

I've put v1 into the tokens in this PR https://github.com/patternfly/patternfly/pull/5980

**Comment by srambach** [comment]
The plan is to version tokens separately from PF versions.  For the time being, we'll use `--pf-t-` for simplicity of development, and near the end of the token work, we'll replace this with a versioned prefix, probalby `--pft-vX--` recognizing that tokens live in their own repository independent of core, and maintaining the established syntax pattern for versioning.
