### ISSUE TITLE
Bug - Pagination - bottom pagination broken on small screens

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly#6016]
<img width="482" alt="Screenshot 2023-10-25 at 11 07 11 AM" src="https://github.com/patternfly/patternfly/assets/26305082/2e102cef-a06a-4a0e-ad12-e2cfcf5e1d6b">

Reported by Ansible

**Comment by mcoker** [comment]
@nicolethoen looks like this is 2 things.

In core, our examples reference the deprecated options menu. We just need to replace the options menu component in our examples with the menu toggle, and that will take care of it.

In react, looks like there is a `<div>` that wraps the menu toggle that should ideally be removed or set to `display: contents`. The toggle's positioning relies on being a direct child of the `.pf-v5-c-pagination` element parent since the layout is controlled via flex.

**Comment by mcoker** [comment]
replaced the options menu with a menu toggle in this PR https://github.com/patternfly/patternfly/pull/6586
