### ISSUE TITLE
Find a way to round corners that doesn't use border-radius

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6045]
**Describe the enhancement or change**
To apply rounded corners with `border-radius`, we also need to add `overflow:hidden`, or else something square inside the container will bump out of the corner. And hiding the overflow means that things like dropdowns will not extend outside the border of the container.

Therefore, we would like to find a solution that rounds the corners as desired without requiring `overflow:hidden`.

Possible solution along these lines: `clip-path: inset(45% 0% 33% 10% round 10px)`

**Comment by thatblindgeye** [comment]
Possibly could be split into 2 issues:

- Find elements where a wrapper is needed, similar to the Page component having a wrapper around main (Card may be one)
- Find an alternative to overflow hidden (dropdowns in Cards will get clipped e.g.)

**Comment by thatblindgeye** [comment]
In terms of scenarios where a container that has rounded corners has overflow scrollbar, adding a new wrapper similar to page may be the best bet to not have the overflow scrollbar "overflow" the edge of the container/cause the rounded corners to be lost beneath the scrollbar.

Customizing the `::-webkit-scrollbar` and `::-webkit-scrollbar-thumb` styles wouldn't really be an option because 1) it would only apply to Chromium browsers, 2) would differ from expected styling (especially if we're not updating the scrollbar in *every* PatternFly space), and 3) it still wouldn't totally solve the issue as from what I can tell, we can't adjust the scrollbar/thumb itself positioning wise so it would still cover the rounded corners.

`overflow: hidden`/clip sort of works in terms of preventing the scrollbar from covering the rounded corners, but if the scrollable area is very large, the scroll thumb gets smaller to the point where it may end up being hidden/difficult to click/look a little "off/funky" depending on the size of the border-radius (on top of issues with menu content then being cut off). The following image is from About Modal:

![Scrollbar thumb being partially hidden by an overflow property of hidden on the scrollable container](https://github.com/patternfly/patternfly/assets/70952936/83c516e5-b901-4769-b84f-294bc2766e9e)

While here is the Menu component where the rounded scrollbar doesn't look too bad even as the thumb gets smaller (About modal has a border radius of 24px while menu only has 6px):

![image](https://github.com/patternfly/patternfly/assets/70952936/7ace3c15-fcc8-4b76-b450-14bb191ec878)

So the following components, where the entire container is either intended or may be expected to have a scrollbar (vs just the body content) could benefit from a wrapper similar to Page (may not be an exhaustive list, more based on what either by default or via secondary styling has rounded corners easily visible):

- About modal
- Accordion (the `__expandable-content` element specifically)
- Drawer
- Dual List Selector
- Text Area (currently the overflow hidden is causing the scrollbar to look rounded, though we may want to consider using a consistent solution if it makes sense rather than some components have a wrapper and some just clip the scrollbar)
- Menu (similar to TextArea, currently using overflow hidden to clip the scrollbar)
- Panel (will depend on if https://github.com/patternfly/patternfly/issues/6732 is a valid issue)

Depending on the component, we could also consider (either in addition to or instead of) ensuring elements inside the rounded-corner element also have rounded corners where applicable. [Example of inheriting border radius](https://codepen.io/thatblindgeye/pen/ExzmKQW), though we could also just assign whatever CSS var to the specific border radius properties of children as well e.g.` ..._someChildElement--BorderStartStartRadius: var(--someVar);`. For things like a Card having a CardHeader, we could apply the border radius to the topleft/right of the CardHeader as well.

Worth noting that some components that we don't currently handle overflow ourselves, and may be more an issue if consumers apply one or for a very specific scenario:
- Alert: possibly more an issue with mobile and smaller sized viewports when a single alert has a lot of content, and really more for a toast alert group
- Code block (specifically the __content element): more an issue for the bottom-end corner if there'sa scrollbar, since the top-start corner is "square" due to the header having the rounded corner
- Hint: more if there's a scroll on the outermost element instead of the `__body`
- Popover

<hr/>

So onto the second part of this issue: menu-like content that should flow outside the container it's visually contained in and `overflow: hidden` or clip - while working for instances like scrollbars - breaks since it clips the menu/popup.

A super quick solution React side would be to essentially update our usage of menu-like components in React so that the get appended to document body/something outside the container that has border-radius. Doing that would mean possibly being able to keep the overflow hidden trick wherever necessary, since the menu is no longer actually rendered inside the container with overflow hidden. This kinda goes against our idea of appending these sorts of components as close to the trigger as possible, and we'd need to be more strict about ensuring keyboard focus is handled properly, otherwise we get into the issues with appending things too far away from the trigger.

Another solution - which would require more of a markup change + possibly some more styling updates from Core - could revolve around the wrapper solution to resolving the whole scrollbar overflowing the rounded container. Essentially having an outermost wrapper element that is just a container with `position: relative` (and any other styles), and inside of that would be basically what the existing component markup looks like (except removing `position: relative` where applicable). So using Card as an example, currently the outermost `pf-v6-c-card` element has `position: relative`. Adding another wrapper around that element and moving the position property to it would allow clipping other content so that it doesn't overflow the rounded corners, allow a menu to overflow the card itself visually, and allow the menu to be appended in the DOM closer to the trigger. This would at least possibly pair a bit nicer with the overflow hidden/clip that we're currently using in spots if that's something we really want to keep (so that the scrollbar itself looks rounded and matches the container better).

**Comment by thatblindgeye** [comment]
For the first part of this issue, we should update components so that the scrollbar is included in the overflow hidden/clip path, to achieve a "rounded" scrollbar. This will also require updating the page main/main-container so that the scrollbar is no longer spaced away from the container.

For the second part of the issue, taking into account that the above changes would be made, the best solution looks to be updating React-side so that Poppe appends to the document body by default

**Comment by thatblindgeye** [comment]
Closing per discussions above, opening a new issue for core work
