### ISSUE TITLE
Pagination - refactor to use menu toggle/menu instead of options menu

### ISSUE THREAD

**Issue by thatblindgeye** [patternfly/patternfly#6094]
**Describe the enhancement or change**
Followup to https://github.com/patternfly/patternfly/pull/6089 

Currently core is still using options menu components for the `pagination-options-menu.hbs` file. We need to refactor it to use menutoggle/menu, similar to React

**Is this request originating from a Red Hat product team? If so, which ones and is there any sort of deadline for this enhancement?**

**Any other information?**

**Comment by mcoker** [comment]
The update from https://github.com/patternfly/patternfly/pull/6586 should do most of the work, but at least one enhancement I'd like to see is wrapping the menu/menu-toggle in a pagination structural element (`div.pf-[v]-c-pagination__per-page-menu` or something like that) and toggling `display` on that instead of having to mess with `display` on the menu-toggle directly.

**Comment by thatblindgeye** [comment]
Closed by #6607
