### ISSUE TITLE
Penta - convert values to relative units

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6123]
Currenty most (all?) values that come from figma and are in our CSS tokens are in px values, but at least for typography we want to use rem/em values, but probably retain them for spacing and other sizes of things as well. We have an SCSS function for that now, `pf-size-prem()` https://github.com/patternfly/patternfly/blob/87d4503cbf1d4b0c5da82a03e26bfbefac48c69c/src/patternfly/sass-utilities/functions.scss#L10-L12

We use that for a lot of our [global vars](https://github.com/patternfly/patternfly/blob/main/src/patternfly/sass-utilities/scss-variables.scss), and throughout components, too.

We should review our sizes and see what all it makes sense to have in fixed vs relative units and how to best handle that conversion and deliver the converted values.

cc @wise-king-sullyman @thatblindgeye @srambach @lboehling @andrew-ronaldson

**Comment by thatblindgeye** [comment]
A tl;dr is that it becomes more difficult to try and rem-ify things when those things are stored in CSS variables. 

Sass functions will run before those variables compile to an actual value (like "12px" or 'rgba(...)" etc), so we can't use a Sass function on the CSS vars being created from the token files. So any function would be trying to run some operation on the CSS var name, e.g. `--pf-t--some--var / 16 * 1rem` rather than `14 / 16 * 1rem` or `@if type-of(--pf-t--some-var)` rather than `@if type-of(12px)`.

Another issue is that because font sizes and spacers and such are unit values, we can't run a calc on them since CSS has an issue with dividing unit values by unitless values (hence the reason we were using that `pf-strip-unit` function inside our `pf-[keyword]-prem` functions).

Using a [custom style dictionary transform](https://amzn.github.io/style-dictionary/#/transforms) may be something to look into, if possible. 

Otherwise it may require hacking something a little more convoluted together using Sass. One thought was something along the lines of:

- Instead of defining a mixin in each token file, output a Sass map in those files. So `$tokens-default: (...map here)` instead of `@mixin pf-vy-tokens {...css vars here}`
- From those maps, create a mixin that will run an `@each` over the map items to create our CSS vars
  - This would require running our `pf-[keyword]-prem` functions if the map item `$key` has "font--size" in its name and map item `$val` is a unit (number) value and returning that `prem`d val, otherwise just return the val (we'd want "12px" to be converted to rem, but not "rgba(...)" or "var(--pf-t--some--token)" etc).

Or something like the above, except instead of doing any calculations inside a mixin, just converting the map to a mixin and then wherever we want to use a rem value in a component `.scss` file we get the token value from the map (with `map.get`) rather than using whatever CSS var was created from the mixin. Would probably result in some CSS vars just not being used, though, as we'd most likely want all font vars to be converted to rem.

<hr/>

Some like the above may be easier for font sizes since as mentioned we'd most likely want all of those converted to rem. Maybe a little tricker if we need spacer/other px values converted to rem, but not all of them. 

For reference, I've included some screenshots of our Button component in Firefox, using various browser settings (zoom, default font size) and/or styling (using the default px values vs rem).

With the default styling, the first screenshot is a Button with browser @ 120% zoom while the second screenshot is @ 200% zoom, both at 16px browser font size and "Zoom text only" disabled:

![Button in Firefox at 120% zoom, 16px browser font](https://github.com/patternfly/patternfly/assets/70952936/498d1848-2fdd-46ec-908d-959bf639de32)
![Button in Firefox at 200% zoom, 16px browser font](https://github.com/patternfly/patternfly/assets/70952936/e4f1f502-f809-4dbf-83b7-c4b0d0a65ee1)

Updating the browser font size doesn't really have any affect, but here is the button @ 200% zoom, 16px font size, and "Zoom text only" enabled:

![Button in Firefox at 200% zoom, 16px browser font, and "Zoom text only" setting enabled](https://github.com/patternfly/patternfly/assets/70952936/054daf65-e93b-4519-9bbd-c169e9c9cf04)

After updating a button's font size to be converted to a rem value, the first screenshot is @ 120% zoom and the second @ 200% zoom, both using 24px browser font size (only on the "primary" button, including the "secondary" button for comparison here):

![Button in Firefox at 120% zoom, 24px browser font, and CSS updated to rem values](https://github.com/patternfly/patternfly/assets/70952936/0967fce8-afd3-4860-8159-d209c4a6ae2f)
![Button in Firefox at 200% zoom, 24px browser font, and CSS updated to rem values](https://github.com/patternfly/patternfly/assets/70952936/99d7ca90-8fac-4f3e-8de4-2db63d3ac9ca)

And then with the same settings, but enabling "Zoom text only" setting (first screenshot @ 120% zoom, second screenshot @ 200% zoom):

![Button in Firefox at 120% zoom, 24px browser font, CSS updated to rem values, and "Zoom text only" setting enabled](https://github.com/patternfly/patternfly/assets/70952936/3c3568c4-b604-4ba1-bc55-afd13f94f5b4)

![Button in Firefox at 200% zoom, 24px browser font, CSS updated to rem values, and "Zoom text only" setting enabled](https://github.com/patternfly/patternfly/assets/70952936/0f2a2ccf-7de7-4fac-baf4-a79aac033039)

Lastly, I updated the padding to use rem values in addition to using rem on the font size. Browser is @ 120% zoom with a browser font of 24px, "Zoom text only" disabled (paddings aren't 100% the same, maybe some decimal places off since I just threw it together):

![image](https://github.com/patternfly/patternfly/assets/70952936/d48d40d9-23f6-480a-9253-5f7091252020)

**Comment by srambach** [comment]
Follow up to look at using a transform to generate token variables with rem values at https://github.com/patternfly/design-tokens/issues/47
