### ISSUE TITLE
Menu toggle followup

### ISSUE THREAD

**Issue by mattnolting** [patternfly/patternfly#6257]
Menu toggle has several needed updates. 

- [ ] standardize the layout. There are layout inconsistencies involving buttons and buttons with icons. All `icon`s should be wrapped in a `menu-toggle__button` to support consistent syling.
- [ ] clean up css
- [ ] add .#{$menu-toggle}__main to house extra elements, like .#{$menu-toggle}__icon, .#{$menu-toggle}__text, .#{$menu-toggl e}__count, .#{$menu-toggle}__controls, and spacing should be controlled by `gap` properties
- [ ] transition to row/column gap instead of margins
- [ ] abstract `button` v `control` styling to affect any/all variants
- [ ] move controls to wrap buttons, not the other way around
- [ ] update text-input-button to use gap

**Comment by mcoker** [comment]
Closing for the time being, we're past the point of making breaking changes and have made a bunch of improvements since this issue was created. AFAIK there is nothing in this issue that is high priority and needs to be addressed with the current menu toggle. We can re-open if needed for any of the items in the issue description.
