### ISSUE TITLE
Remove global Sass variables in V6

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6312]
Sass variables should have been removed from components, so we should be able to remove them completely now.
Exception: `--#{$pf-global}--spacer--form-element` is used and will need a replacement.

**Comment by mcoker** [comment]
I don't think `--#{$pf-global}--spacer--form-element` should be a blocker or anything, we have updated the form elements and buttons and what-not to use the small spacer.

Worth noting though that we will also need to keep the
* breakpoint vars
* font paths
* breakpoint/spacer maps (need to be updated to reference tokens instead of the sass global vars)
* we're still referencing some of the transition global vars, but I guess we can just create CSS tokens for those for the time being?

**Comment by srambach** [comment]
Depends on #6315 and #6316

**Comment by mcoker** [comment]
global sass vars have all been removed
