### ISSUE TITLE
Bug - [Masthead] - Hamburger disappears in Light Variant

### ISSUE THREAD

**Issue by ChrisLee5000** [patternfly/patternfly#6390]
**Describe the problem**
Masthead-> Light and Light 200 Variant.
The hamburger is white on white (invisible) when hovering, and in default mode is of a very low contrast.

**How do you reproduce the problem?**
https://www.patternfly.org/components/masthead/html/light-variant/
Visit that example

**Expected behavior**
The hamburger should be of a high contrast black color

**Is this issue blocking you?**
Override the class

**What is your environment?**
 - OS: Windows 10
 - Browser Chrome
 - Version 121.0.6167.185

**Comment by mcoker** [comment]
Hey @ChrisLee5000! Can you share your use case of using the light variant of the masthead? A link or just a screenshot would be great.

**Comment by ChrisLee5000** [comment]
Hi mcoker, I can't share my application, but the usage and bug is as shown in the example. I guess what I'm expecting is the hamburger should be a higher contrast color when using the light variant.

**Comment by mcoker** [comment]
@ChrisLee5000 sorry for the delay in getting back. And I'm sorry you've run into this bug, this is a pretty big oversight on our part. That said, we discussed [the fix I put up](https://github.com/patternfly/patternfly/pull/6418) as a group and would prefer seeing if we can give you a workaround. The reasons being, 1) this bug has been there for over a year, so if anyone is using the light variant of the masthead, they've likely already worked around it. Pushing a fix at this point would likely be disruptive to any existing workarounds. 2) The light variant of the masthead was added without a use case and isn't currently recommended by our design teams for use in PF apps. 3) We're currently working to release a new major version of PF later this year, which includes a new look/feel from design, and this variant is going to be removed, so it isn't something we continue to plan on supporting.

The override would look like this:

```
.pf-v5-c-masthead .pf-v5-c-button.pf-m-plain {
  --pf-v5-global--Color--100: var(--pf-v5-global--Color--dark-100);
  --pf-v5-global--Color--200: var(--pf-v5-global--Color--dark-200);
  --pf-v5-global--BorderColor--100: var(--pf-v5-global--BorderColor--dark-100);
  --pf-v5-global--primary-color--100: var(--pf-v5-global--primary-color--dark-100);
  --pf-v5-global--link--Color: var(--pf-v5-global--link--Color--dark);
  --pf-v5-global--link--Color--hover: var(--pf-v5-global--link--Color--dark--hover);
  --pf-v5-global--BackgroundColor--100: var(--pf-v5-global--BackgroundColor--light-100);
  --pf-v5-global--icon--Color--light: var(--pf-v5-global--icon--Color--light--dark);
  --pf-v5-global--icon--Color--dark: var(--pf-v5-global--icon--Color--dark--dark);

  color: var(--pf-v5-c-button--m-plain--Color);
}
```

Can you try that and let me know if the override works, and if this solution will work for you?

**Comment by ChrisLee5000** [comment]
Hi @mcoker, thanks for that and acknowledging it as a bug. I tried the snippet, and it did not work. However, I have already written my own overrides that fix the problem.

Happy for you to close this and I look forward to Patternfly 6, which I've had a look at and am happy with the visual direction. One thing I would like to see is better animation for things like the navigation drawer that come out without transitions. However, the <Drawer> component itself has a nice smooth transition.

**Comment by mcoker** [comment]
@ChrisLee5000 great! Glad you have a way around the bug, and are looking forward to PF6! And good news - we are working on an animation story for PF6. Right now the tentative plan is to implement and release with some basic, consistent animations, and continue to iterate and implement more over time.

If you're override is working, there is no reason to change it IMO, but if you run into issues and want to reference any of the declarations in the override above, I'll mention that it does need to be applied after the styling from PF because the specificity of the override block matches the specificity of the the block that's causing the bug in the PF CSS. If you are unable to control the loading order of the override, you can also increase the specificity of the `.pf-v5-c-masthead .pf-v5-c-button.pf-m-plain` selector - for example, add `html .pf-v5-c-masthead .pf-v5-c-button.pf-m-plain` or whatever way makes sense for your page.
