### ISSUE TITLE
Bug - [Drawer] - Scroll bar is added unexpectedly

### ISSUE THREAD

**Issue by ChrisLee5000** [patternfly/patternfly#6391]
**Describe the problem**
The Drawer component adds a scroll bar even when the content is not long enough to scroll.

**How do you reproduce the problem?**
https://www.patternfly.org/components/drawer/react/basic/
Visit that example

**Expected behavior**
There should be no scroll bar.

**Is this issue blocking you?**
Override the class 
```
.pf-v5-c-drawer {
    height: auto;
}

```

**Comment by mcoker** [comment]
Hey @ChrisLee5000! Thanks for reporting this. The drawer is designed to consume 100% of the height of its container and uses `height: 100%` to do this by default. For most cases, that means the drawer's parent element should have some sort of height, and the drawer should be the only child in that element. The example you linked to has a scrollbar due to the presence of the "toggle drawer" button at the top of the example, which is something we can address by putting the drawer in its own container with a height set.

I'm curious if this is showing up somewhere in your UI with an unnecessary scrollbar, or were you just reporting the bug you saw in that example? If it's also in your UI, are you able to share a link to somewhere I can see it?

**Comment by ChrisLee5000** [comment]
Hi mcoker, thanks for your reply. It is showing up in my application, however I cannot post screenshots due because of the nature of the project. I am using the inline variant of the drawer.

I'll try your fix to put the drawer in its own container. Would you recommend a <PageSection> component ?

**Comment by mcoker** [comment]
Gotcha. There are a number of ways you can do it, it really just depends on your ideal UI for how you want the drawer to display in relation to other things. Here are a handful of codesandboxes with various techniques to get rid of that scrollbar. 

If none of these are helpful, if you can describe or even just sketch out the UI you're going for, I'll do my best to come up with something that should work.

https://codesandbox.io/p/sandbox/romantic-hooks-wv86n7?file=%2Findex.tsx%3A52%2C22
* This is the same demo as you see, I just removed `height: 100%` from the parent `#root` div that wraps the rendered content (in the `index.html` file)
* The drawer height now is just as tall as its content. The drawer still has `height: 100%` in the CSS, but it doesn't do anything since its parent doesn't have a defined height.

https://codesandbox.io/p/sandbox/adoring-heisenberg-x7lpms?file=%2Findex.tsx%3A60%2C13
* Leaves `height: 100%` on the parent `#root` div in `index.html`, but wraps the `<Drawer>` in a `<div>`. Ends up basically the same as the previous codesandbox - the drawer's `height: 100%` doesn't do anything since its parent doesn't have a defined height.

https://codesandbox.io/p/sandbox/nice-kowalevski-yp5y35?file=%2Findex.tsx%3A56%2C26
* Flex layout wraps the button and drawer
* Flex layout is set to `height: 100%` to fill the height of the viewport
* FlexItem that holds the drawer is set to grow (fill the available space), so the drawer also fills all of that available space, too.

https://codesandbox.io/p/sandbox/loving-driscoll-fm7yk9?file=%2Findex.tsx%3A57%2C19
* Toggle is in the drawer content - this works since the panel has its own close icon (needed on smaller screens when the panel is the full width of the drawer content)
* Drawer is only as tall as the content it opens on top of - including the toggle

**Comment by ChrisLee5000** [comment]
Thank you @mcoker, that is very helpful.
