### ISSUE TITLE
Table - remove extra border on mobile collapsed expandable rows

### ISSUE THREAD

**Issue by srambach** [patternfly/patternfly#6556]
Per Kayla's comment below, remove the extra 1px border under collapsed expandable rows.  

Additional info from dupe https://github.com/patternfly/patternfly/issues/6667#issue-2299104805

> Double bottom-border on non-expanded rows in expandable tables. Here's where the borders are coming from
> 
> https://github.com/patternfly/patternfly/blob/c11387c8b1dea7e573beb0a7f5c4c12a51c1080a/src/patternfly/components/Table/table.scss#L1060-L1062
> 
> https://github.com/patternfly/patternfly/blob/c11387c8b1dea7e573beb0a7f5c4c12a51c1080a/src/patternfly/components/Table/table-grid.scss#L185-L188
> 
> <img alt="Screenshot 2024-05-15 at 7 54 16 PM" width="625" src="https://private-user-images.githubusercontent.com/35148959/331001608-33cc8cc6-45d2-4824-9383-316c1c6b382a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTI5OTMsIm5iZiI6MTcxNTk1MjY5MywicGF0aCI6Ii8zNTE0ODk1OS8zMzEwMDE2MDgtMzNjYzhjYzYtNDVkMi00ODI0LTkzODMtMzE2YzFjNmIzODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDEzMzEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YTc4MjUyNzE1YzEzMjdjMmNiMTkyNjRkZTYzNzE1YjdjM2JjOTA5NmQ3MGUxZTA2M2Y4YmVmNWFlOWRmYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rMiPwHxH1vRMJC7PvkoquEl5F_CC3pPIfnvhKZJ3MQc">

**Comment by kaylachumley** [comment]
@evwilkin That looks correct! The comment about the table borders changing color was only for data list not table. I think I confused everyone with my [design issue comment](https://github.com/patternfly/patternfly-design/issues/1290) sorry about that! 

Thanks for calling out that double border when expanded. By double border, do you mean 2px width instead of the normal 1px? Looks like the "double border" is 2px on expansion and the single border is just 1px on default. Lets change the borders to be 1px on default and expansion.

**Comment by mcoker** [comment]
Sorry just saw these comments - FYI I opened an issue for the double border yesterday in case we want to close it in favor of this one @evwilkin - https://github.com/patternfly/patternfly/issues/6667

**Comment by mcoker** [comment]
closed by https://github.com/patternfly/patternfly/pull/6698
