### ISSUE TITLE
Masthead items overflowing container

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6568]
We have a bunch of examples/demos that have items overflowing the masthead on super small screens. As an example https://pf6.patternfly.org/components/notification-drawer/html-demos/expanded-read/

<img width="564" alt="Screenshot 2024-04-24 at 2 44 56 PM" src="https://github.com/patternfly/patternfly/assets/35148959/3a4510ab-deb0-41b7-9a3e-be82b831e3c6">

An outline to get started might be:
* Test the masthead in a bunch of configurations and make sure items overflow as expected, and that may be just ensuring things behave the way they did in v5 since that's the current expected behavior
* Fix the examples/demos 
  * They may fix themselves automagically if we find any bugs from ^
  * Update our common masthead template used across examples/demos if needed to fix any issues
    * Core and react also have, generally speaking for most examples/demos, the same basic masthead template/layout. We should aim to maintain that - and if we need to update that, we should loop the react team in so we can maintain as much parity as makes sense.

**Comment by thatblindgeye** [comment]
A solution may depend on what we want the visuals to end up as.

- In the masthead template files, we could wrap the two menu toggles ("Services" and "Overview") in a toggle group so that they wrap, then apply a nowrap modifier to the icon group:
    ![image](https://github.com/patternfly/patternfly/assets/70952936/da5632b0-8644-4909-9d60-299004d78b7c)

  Though maybe better to keep wrapping since at smaller viewports the nowrap would become an issue. Extreme example of ~200px width viewport, but here's what this solution would look like with wrapping still:

    ![image](https://github.com/patternfly/patternfly/assets/70952936/57814074-a4e5-4f1b-adb2-97963dcddbb7)

- Somewhat similar, we can wrap the menu toggles in a toggle__group, and apply a wrap modifier to the toolbar_content-section wrapper so that the icon buttons wrap beneath the menu toggles, then change the `align-end` modifier to apply only at a certain breakpoint. With something like this the expected tab order would match the visual (the above screenshots may make it seem like the tab order would be menu toggle > icon button > menu toggle > icon toggle, when it's really menu toggle > menu toggle > icon button > icon toggle):

    ![image](https://github.com/patternfly/patternfly/assets/70952936/07633384-761d-4ef5-bf3d-9b7a8908d512)

- We could also possibly do something similar to the [toolbar filter on mobile demo](https://pf6.patternfly.org/components/toolbar/html-demos#toolbar-attribute-value-search-filter-on-mobile), and have the two menu toggles ("Services" and "Overview") be visible at X viewport and above, and some other toggle visible at below X viewport. Possibly more of a lift Reactside to handle clicking the new toggle + not entirely sure if we should fiddle with focus/tab management, as DOM wise the expanded content would be rendered after the menu toggles + icon buttons, which may not make sense (having to Tab through unrelated content just to get to the content you caused to dynamically render)
- Just have the menu toggles not visible below a certain threshold, similar to how the "Dropdown" toggle only renders at lg and up in the [masthead with context selector and dropdown demo](https://pf6.patternfly.org/components/masthead/html-demos/with-context-selector-and-dropdown/)

Just to note, some demos that are similar-but-different-enough include:

- [Masthead with toolbar filters](https://pf6.patternfly.org/components/masthead/html-demos/with-toolbar-filters/): has a search input + menu toggle instead of 2x menu toggles. Though this demo looks similar to the masthead with toggle group demo, except the latter handles the issue better. Should we keep both or rename the demos? Seems like maybe the former is more of a "on desktop" demo and the latter is maybe meant to be "on mobile" or "responsive"
- [Masthead horizontal nav demo](https://pf6.patternfly.org/components/masthead/html-demos/horizontal-nav/) has the 2x menu toggles + nav. Worth mentioning that as the viewport shrinks the horizontal nav becomes impossible to use (screenshot below) as the actual nav items aren't really visible, which is an issue I'm noticing just on v6 Core staging's horizontal nav as well. Flex wrapping things may help here.
    ![image](https://github.com/patternfly/patternfly/assets/70952936/495888c3-20fb-4a38-984f-69b15776c1d8)
- The [mobile examples demo](https://pf6.patternfly.org/components/masthead/html-demos/with-toggle-group-filters-expandable-content-expanded-mobile/) has the input group overflow at smaller viewports. The solution could either be replace the "Name" menu toggle with just an icon toggle, or remove the demo completely (if there's use case in product worth keeping, but considering the masthead has such little room does it make sense to show an input group like this in it?)

**Comment by thatblindgeye** [comment]
Per convo closing this as it should be resolved by removing the Overview and Services toggles.
