### ISSUE TITLE
Bug - Card - Card header actions take up more than 50% width 

### ISSUE THREAD

**Issue by jschuler** [patternfly/patternfly#6575]
**Describe the problem**
When the window width is reduced, the card header actions take up more than 50% of the horizontal width.

Before (PF4):
<img width="620" alt="Screenshot 2023-12-12 at 3 59 56 PM" src="https://github.com/patternfly/patternfly-react/assets/869106/4c6a14cb-de5e-41a5-a783-466b06c42a96">

After (PF5):
<img width="619" alt="Screenshot 2023-12-12 at 4 00 08 PM" src="https://github.com/patternfly/patternfly-react/assets/869106/5270e9e9-68fb-4759-a896-501a2f5ea820">

**How do you reproduce the problem?**
https://codesandbox.io/p/sandbox/card-header-space-issue-p2g5sn?file=%2Findex.tsx%3A7%2C8
Slide the preview window smaller

**Expected behavior**
Would expect to see the actions take up no more than 50% of the horizontal width

**What is your product and what release date are you targeting?**
OCM, Q4 2022

**Workaround**
```
.pf-v5-c-card__header-main {
    flex-basis: auto;
  }
```

**Comment by mcoker** [comment]
Looks like the difference is that we've added `flex: 1` to `__header-main`, which is also setting `flex-basis: 0` https://github.com/patternfly/patternfly/blob/88cf5072ed9f664795468accc89dd8d69116b8f5/src/patternfly/components/Card/card.scss#L367-L369, making it shrink relative to the actions element, and it should likely be the other way around. I think the goal of `flex: 1` is just to have `__header-main` fill the space.

That said, I'd propose:
* We update that style to just use `flex-grow: 1`, which should solve this bug and allow header-main to fill the space
* Since this could have unintended side effects for v5 users, I'd also propose we fix this in v6

wdyt @srambach @mattnolting 

@jschuler would you be OK with the local style workaround you provided for v5, and we fix this in v6?

**Comment by mcoker** [comment]
closed via https://github.com/patternfly/patternfly/issues/6575
