### ISSUE TITLE
Dropdown inside of Modal with scrollable content can cause double scrollbars and overlay the top heading.

### ISSUE THREAD

**Issue by sg00dwin** [patternfly/patternfly#6777]
An example of a modal with scrollable content that contains a `Dropdown` with 20 items can cause double scrollbars and the menu items will overlay the title and buttons.

**Are there visuals for this issue? Please provide screenshots**
![Screenshot 2024-06-11 at 4 27 43 PM](https://github.com/patternfly/patternfly/assets/1874151/9c7470e2-8a7d-4dbc-bf82-3b2d62784105)

Video of behavior
![PF6-dropdown-in-modal-with-overflow-bugs mov](https://github.com/patternfly/patternfly/assets/1874151/8d0ec19d-4817-42d9-bce8-0015570586e7)

**Sandbox test case**
https://codesandbox.io/p/sandbox/dark-dew-cgfrqh?file=%2Findex.tsx%3A54%2C11

**Comment by thatblindgeye** [comment]
@sg00dwin thanks for mentioning this! With the new penta styling as well as the uncertainty of exactly what may trigger an overflow scrollbar (either something in the Modal header causing the Modal itself to scroll or something in the Modal body causing only the body to scroll are 2 examples), this might be expected behavior.

There are a couple of workarounds to this on the React side:

- one is to change where the Dropdown is appended via `popperProps={{appendTo: () => document.body}}` or similarly (note that we actually have a PR up in React to make this the default)
- or to pass isMenuScrollable to Dropdown so that the Dropdown menu height will be contained and have a scrollbar attached to itself

Would either of these be viable solutions on the React side for you?

**Comment by sg00dwin** [comment]
> @sg00dwin thanks for mentioning this! With the new penta styling as well as the uncertainty of exactly what may trigger an overflow scrollbar (either something in the Modal header causing the Modal itself to scroll or something in the Modal body causing only the body to scroll are 2 examples), this might be expected behavior.
> 
> There are a couple of workarounds to this on the React side:
> 
> * one is to change where the Dropdown is appended via `popperProps={{appendTo: () => document.body}}` or similarly (note that we actually have a PR up in React to make this the default)
> * or to pass isMenuScrollable to Dropdown so that the Dropdown menu height will be contained and have a scrollbar attached to itself
> 
> Would either of these be viable solutions on the React side for you?

@thatblindgeye these options are workable solutions. thanks
