### ISSUE TITLE
Time picker: Add min-width to time picker

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly#6793]
In the new [Date & time picker](https://staging-v6.patternfly.org/components/date-and-time/date-and-time-picker) the time picker menu matches the width of the menu toggle and truncates the text to 1 character. Can we please add a min-width so the full time is visible.
<img width="451" alt="Screenshot 2024-06-13 at 4 07 29 PM" src="https://github.com/patternfly/patternfly/assets/28658548/cc931655-87a0-4469-9f79-1c59cde731d6">

**Comment by thatblindgeye** [comment]
@andrew-ronaldson since Popper is controlling the width/minWidth/maxWidth in this demo, it's expected that by default the time options will have a width matching the menu toggle. This would probably need to be an update in React, but woudl we instead want to set the width of the menu in a way that by default, the width or minWidth equals the trigger width OR however wide the menu content is, whichever is larger?

So if the MenuToggle is only 68px like in that demo from the screenshot above, the menu itself will be either 68px to match the toggle, or the width of however wide the menu content is (83.5px in that demo).

**Comment by mcoker** [comment]
@andrew-ronaldson do you mind verifying that this issue still exists? I'm looking at https://patternfly-react-v6.surge.sh/components/date-and-time/date-and-time-picker and it looks ok now

<img width="753" alt="Screenshot 2024-07-03 at 2 10 42 PM" src="https://github.com/patternfly/patternfly/assets/35148959/d5175cbf-7c2f-4027-9780-635cda403263">

**Comment by andrew-ronaldson** [comment]
Closing as resolved
