### ISSUE TITLE
Drawer with sticky content isn't sticky

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#6994]
These do not work like they did in v5

https://staging-v6.patternfly.org/components/drawer/html-demos/expanded-drawer-with-jump-links/
https://staging-v6.patternfly.org/components/jump-links/react-demos/with-drawer/

**Comment by evwilkin** [comment]
It looks like the breadcrumb/jumplinks aren’t sticky in those demos because we now need to add `overflow-y: hidden` to the `<main class="pf-v6-c-page__main">` element, and I believe it’s because of the new `.pf-v6-c-page__main-container` wrapper around that element which also scrolls.

![Screenshot 2024-08-28 at 11 10 54 AM](https://github.com/user-attachments/assets/4a186c9e-9cd9-4fdd-be28-7b61ed8fe802)

FYI the JumpLinks `scrollableSelector` prop previously took that `.pf-v6-c-page__main` for scroll spy behavior but now also needs to accommodate the new wrapper and instead target the `.pf-v6-c-page__main-container` element.  Also - does the `.pf-m-resize-observer` need to be updated at all due to this?
