### ISSUE TITLE
Bug - documentation - HTML documentation is broken

### ISSUE THREAD

**Issue by GregJohnStewart** [patternfly/patternfly#7071]
**Describe the problem**
This is an issue with 
- [x] Patternfly 5  

The documentation displaying how to use interactive elements for patternfly for react seems fine. However, for plain HTML seems fundamentally broken. None of the interactive elements seem to function for the HTML example, specifically looking at modal and accordions. This applies to both cases of attempting to interact on the documentation page as well as pasting the example snippet into my own page.

**How do you reproduce the problem?**

Attempt to interact with HTML examples from following pages, or use the code snippets:

 - https://www.patternfly.org/components/accordion/html
 - https://www.patternfly.org/components/about-modal/html
 - https://www.patternfly.org/components/action-list (seems broken for react as well? Unclear if meant to have interactive functionality)
 - https://www.patternfly.org/components/alert/html
 - https://www.patternfly.org/components/clipboard-copy/html
 - https://www.patternfly.org/components/code-block/html
 - https://www.patternfly.org/components/code-editor/html
 - https://www.patternfly.org/components/date-and-time/calendar-month/html (and the other date and time elements)
 - https://www.patternfly.org/components/drag-and-drop/html
 - https://www.patternfly.org/components/drawer/html
 - https://www.patternfly.org/components/dual-list-selector/html
 - https://www.patternfly.org/components/expandable-section/html
 - https://www.patternfly.org/components/file-upload/multiple-file-upload/html (ans single file)
 - https://www.patternfly.org/components/forms/checkbox/html (no select children functionality)
 - https://www.patternfly.org/components/forms/form-select (no html example)
 - ... Most examples with any kind of interactive functionality either have nonfunctional html examples or none at all

**Expected behavior**

HTML examples for all components should be present and functional

**Is this issue blocking you?**

There is no workaround in my view, without extensive effort to inspect functional examples from the react side.

**What is your environment?**

 - any; tested on Firefox

**What is your product and what release date are you targeting?**

A product that isn't built with react

**Comment by mcoker** [comment]
Hey @GregJohnStewart, the HTML examples are static by design, and illustrate the HTML structure and styles of PatternFly components. In the HTML and HTML demos tabs for a given component on https://www.patternfly.org/, you'll find documentation about the markup needed to build components - including the structural HTML elements, classes, variations/modifiers, etc. At the bottom of most/all components, you'll see a [component usage table](https://www.patternfly.org/components/card/html#usage) that provides additional info about the structural elements. Some of the more complicated components, like the [table component](https://www.patternfly.org/components/table/html#basic-table-usage) have multiple usage tables.

PatternFly's primary use case is in react-based applications, so that is the framework we officially support. We do not provide client-side code to make the components interactive beyond what you'll find in the react and react demos pages on patternfly.org. That said, a lot of products use both the HTML and react examples (like you've mentioned), along with [component design guidelines](https://www.patternfly.org/components/card/design-guidelines) and [component accessibility guidelines](https://www.patternfly.org/components/card/accessibility) to integrate PatternFly components into other frameworks/environments, so it sounds like you're on the right track 👍

Are there any specific questions re: using PatternFly components in your project that the team can help out with? FWIW we also have an active slack workspace at patternfly.slack.com (you can also find a link in the footer of any page on https://www.patternfly.org/), in case you have questions or are looking for guidance that you can't find in our documentation.
