### ISSUE TITLE
Page notification drawer breaks sticky behavior on page sections

### ISSUE THREAD

**Issue by leroytromp** [patternfly/patternfly#7141]
Adding a notification drawer to a page, following the example provided in the documentation breaks sticky behavior on all elements in the main page  area. For example, without the notification drawer sticky behavior on these tabs work as expected:

![Image](https://github.com/user-attachments/assets/fd87e92f-94b6-45bc-82a5-68797bc68475)

With the notification drawer, sticky behavior is broken, and the tabs just scroll away as if they were not sticky:

![Image](https://github.com/user-attachments/assets/8e8863ff-5e2c-4ac5-884f-8ad2c79ba139)

This issue exists in all tested branches (even PF5)

**Comment by mcoker** [comment]
Hi @leroytromp! Thanks for reporting this, it should be fixed in our latest pre-release version [`6.0.0-prerelease.21`](https://www.npmjs.com/package/@patternfly/react-core/v/6.0.0-prerelease.21)

https://codesandbox.io/p/sandbox/unruffled-surf-ty5555?workspaceId=07141946-d08a-457d-9ab8-bb9ea5eff2b7

Can you let me know if you're still seeing the issue on that version?

**Comment by mcoker** [comment]
@leroytromp this should be fixed now for v6 which was just released - https://www.patternfly.org. If you're still seeing this bug or need help with a fix, feel free to reply back and re-open this issue.
