### ISSUE TITLE
Can't resolve font files in sass build 

### ISSUE THREAD

**Issue by guillaumevincent** [patternfly/patternfly#720]
Hello,
I'm using webpack to build my application

```js
{
  test: /\.scss$/,
  use: [
    { loader: "style-loader" },
    { loader: "css-loader" },
    {
      loader: "sass-loader",
      options: {
        includePaths: [
          path.resolve(
            __dirname,
            "node_modules/@patternfly/patternfly-next"
          )
        ]
      }
    }
  ]
}
```

I try to import in my `App.scss` file `patternfly-base.scss` file:

```scss
$pf-global--enable-reset: false !default;
@import "~@patternfly/patternfly-next/patternfly-base.scss";
@import "~@patternfly/patternfly-next/components/Button/styles.scss";
```

Got a lot of errors like this one:

```terminal
./src/App.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js??ref--6-2!./src/App.scss)
Module not found: Error: Can't resolve './assets/fonts/overpass-mono-webfont/overpass-mono-bold.eot' in '/home/guillaume/workspace/dci-dev-env/dci-ui/src'
```

Any idea how to solve this?

**Comment by seanforyou23** [comment]
Hi @guillaumevincent, try defining the following sass vars;

`$pf-global--font-path: '../../node_modules/@patternfly/patternfly-next/assets/fonts/';
$fa-font-path: '../../node_modules/@patternfly/patternfly-next/assets/fonts/webfonts/';
$pf-global--image-path: '../../node_modules/@patternfly/patternfly-next/assets/images/';`

Of course adjust the paths to work based on your applications directory structure. Looks like the problem is that you're referencing the import from `/home/guillaume/workspace/dci-dev-env/dci-ui/src`, and because `$pf-global--font-path` is still set to its default value, sass-loader is looking for the font in `.../dci-dev-env/dci-ui/src/assets/fonts/...`.

By pointing those vars to where these files exist, either under node_modules or in a custom directory you craft together yourself, the references should then resolve. I imagine you'll need the images and FA icons as well, so I included similar examples of how to define those.

https://github.com/patternfly/patternfly-next/blob/master/src/patternfly/sass-utilities/scss-variables.scss#L105

From what I've seen so far, `options.includePaths` property isn't required in your webpack config for patternfly-next sass to work, that was a PF3 sass thing. Are you using PF3 at all? If not, I'd be interested to know if you can drop that custom sass-loader config. I will update our docs/readme with better info on exactly this subject after you're squared away here.

**Comment by dgutride** [comment]
@guillaumevincent  - we are investigating a bit more about the paths in pf4 - for now, I'd recommend using the variables @seanforyou23 mentioned but depending on how you are compiling, there are a few things to keep in mind.  The paths in the root are set for our compiled patternfly.css (and work from there) -if you are pulling in component level css or sass, you'll have to change the pathing system to work for you.  

Do you have a sample create-react-app set up anywhere we can collaborate on?  If not, we'll be creating one w/patternfly-next in the next couple of days to work through this together on.

**Comment by guillaumevincent** [comment]
@dgutride if so, we need to update our upgrade guide https://pf-next.com/upgrade-guide

**Comment by guillaumevincent** [comment]
So my solution:

 * install create-react-app version 2
 * install `patternfly-next`, `react-core` and `node-sass`
 * replace `App.css` with `App.scss`

```
$pf-global--font-path: '~@patternfly/patternfly-next/assets/fonts/';
$fa-font-path: '~@patternfly/patternfly-next/assets/fonts/webfonts/';
$pf-global--image-path: '~@patternfly/patternfly-next/assets/images/';
@import "~@patternfly/patternfly-next/patternfly-base.scss";
@import "~@patternfly/patternfly-next/components/Button/styles.scss";
```

 * edit `App.js`

```
import React, { Component } from 'react';
import {Button} from "@patternfly/react-core"
import './App.scss';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Button>test</Button>
      </div>
    );
  }
}

export default App;
```

Note: 

 * create-react-app version 1 build doesn't works. An issue with `button.css.js`
 * `patternfly-base.scss` is enough to get the css for button
